const R=String.raw;
export default {id:'kompaktheit',title:'Kompaktheit',description:'Heine–Borel, Folgen und offene Überdeckungen.',priority:'Schwerpunkt',source:'Lecture Notes · §1.2; Blatt 3; T.4.1',visual:'compact',generator:'compact',goals:['Kompaktheit und Folgenkompaktheit exakt definieren.','Heine–Borel im richtigen umgebenden Raum formulieren.','Abgeschlossenheit und Beschränktheit einzeln begründen.','Gegenbeispiele mit Folgen angeben.'],theory:[
{id:'metric',kind:'Definition',title:'Metrik und offene Kugel',text:R`Eine Metrik auf $X$ ist eine Abbildung $d:X\times X\to[0,\infty)$ mit $d(x,y)=0\Leftrightarrow x=y$, $d(x,y)=d(y,x)$ und $d(x,z)\le d(x,y)+d(y,z)$. Für $r>0$ ist $B_r(a)=\{x\in X:d(x,a)<r\}$.`,source:'Grundbegriffe für §1.2',checks:['Definitheit, Symmetrie, Dreiecksungleichung.','Offene Kugel: strenge Ungleichung.']},
{id:'closed-bounded',kind:'Definition',title:'Offen, abgeschlossen, beschränkt',text:R`Sei $(X,d)$ metrisch. $U\subseteq X$ heißt offen, wenn zu jedem $x\in U$ ein $r>0$ mit $B_r(x)\subseteq U$ existiert. $A$ heißt abgeschlossen, wenn $X\setminus A$ offen ist. Äquivalent: Jede in $X$ konvergente Folge in $A$ hat ihren Grenzwert in $A$. Für $X\ne\varnothing$ heißt $A$ beschränkt, wenn $A\subseteq B_R(a)$ für ein $a\in X$ und $R>0$ gilt.`,source:'Grundbegriffe für §1.2',checks:['Umgebenden Raum nennen.','Nicht jede Folge in einer abgeschlossenen Menge muss konvergieren.']},
{id:'compact-def',kind:'Definition',title:'Kompaktheit',text:R`Sei $(X,d)$ ein metrischer Raum. $K\subseteq X$ heißt kompakt, wenn jede offene Überdeckung von $K$ eine endliche Teilüberdeckung besitzt: Für jede Familie $(U_i)_{i\in I}$ offener Teilmengen von $X$ mit $K\subseteq\bigcup_{i\in I}U_i$ existiert eine endliche Menge $J\subseteq I$ mit $K\subseteq\bigcup_{i\in J}U_i$.`,source:'Lecture Notes · Definition 1.5, S. 3; T.3.2(a)',checks:['Jede offene Überdeckung.','Endlich viele Mengen aus derselben Überdeckung.']},
{id:'sequential',kind:'Definition und Satz',title:'Folgenkompaktheit',text:R`$K\subseteq X$ heißt folgenkompakt, wenn jede Folge $(x_k)$ in $K$ eine Teilfolge $(x_{k_j})$ besitzt, die gegen einen Punkt $x\in K$ konvergiert. In metrischen Räumen gilt: $$K\text{ kompakt}\Longleftrightarrow K\text{ folgenkompakt}.$$`,source:'Lecture Notes · Definition 1.5 und Satz 1.9; T.3.2(b)',checks:['Teilfolge, nicht gesamte Folge.','Grenzwert in K.']},
{id:'heine-borel',kind:'Satz',title:'Heine–Borel',text:R`Sei $K\subseteq\mathbb R^n$ mit der euklidischen Metrik. Dann gilt: $$K\text{ kompakt}\Longleftrightarrow K\text{ abgeschlossen und beschränkt}.$$ Allgemeiner gilt dies in jedem endlichdimensionalen normierten Raum.`,source:'Lecture Notes · Satz 1.11, S. 10; T.4.1(b)',checks:['Endlichdimensionaler normierter Raum.','Abgeschlossen und beschränkt.'],note:'In jedem metrischen Raum sind kompakte Mengen abgeschlossen und beschränkt. Die Umkehrung gilt dort im Allgemeinen nicht.'},
{id:'stability',kind:'Satz',title:'Kompaktheit erhalten',text:R`In metrischen Räumen gilt: Abgeschlossene Teilmengen kompakter Mengen sind kompakt. Endliche Vereinigungen und endliche kartesische Produkte kompakter Mengen sind kompakt. Ist $K$ kompakt und $f:K\to Y$ stetig, so ist $f(K)$ kompakt. Durchschnitte einer nichtleeren Familie kompakter Teilmengen desselben metrischen Raumes sind kompakt.`,source:'Lecture Notes · Satz 1.12; B.3.3–B.3.4',checks:['Vereinigungen: endlich.','Bilder: stetige Abbildung.','Durchschnitte: Familie nichtleer.']},
{id:'cantor',kind:'Satz',title:'Cantors Schnittmengenkriterium',text:R`Für $K\subseteq X$ in einem metrischen Raum sind äquivalent: (i) $K$ ist kompakt. (ii) Für jede Familie $(C_i)_{i\in I}$ abgeschlossener Teilmengen von $X$ gilt: Wenn $K\cap\bigcap_{i\in J}C_i\ne\varnothing$ für jede endliche Menge $J\subseteq I$, dann ist $K\cap\bigcap_{i\in I}C_i\ne\varnothing$. Der Fall $J=\varnothing$ bedeutet $K\ne\varnothing$.`,source:'Lecture Notes · Satz 1.6; T.4.1(a)',checks:['Abgeschlossene Mengen.','Alle endlichen Schnitte mit K nichtleer.']}
],exercises:[
{id:'compact-disk',title:'Kreisscheibe mit und ohne Rand',source:'Grundaufgabe im Stil des Prüfungsberichts',prompt:R`Untersuche $K=\{(x,y):x^2+y^2\le1\}$ und $U=\{(x,y):x^2+y^2<1\}$ auf Kompaktheit in $\mathbb R^2$.`,hint:'Prüfe Beschränktheit und Abgeschlossenheit getrennt. Verwende für U eine Folge zum Rand.',steps:[R`Für beide Mengen gilt $\|(x,y)\|_2\le1$. Sie sind beschränkt.`,R`$h(x,y)=x^2+y^2$ ist stetig, $K=h^{-1}(( -\infty,1])$ ist abgeschlossen. Nach Heine–Borel ist $K$ kompakt.`,R`$z_k=(1-1/k,0)\in U$, aber $z_k\to(1,0)\notin U$. Somit ist $U$ nicht abgeschlossen und daher nicht kompakt.`],pitfall:'„Der Rand fehlt“ durch eine konkrete Folge belegen.'},
{id:'compact-sequence',title:'Eine Folge als Menge',source:'Lecture Notes · Beispiel 3, S. 4',prompt:R`Zeige die Kompaktheit von $K=\{0\}\cup\{1/n:n\ge1\}$ mit offenen Überdeckungen. Warum ist $K\setminus\{0\}$ nicht kompakt?`,hint:'Eine offene Menge um 0 deckt alle bis auf endlich viele Folgenglieder ab.',steps:[R`Sei $(U_i)$ eine offene Überdeckung von $K$. Wähle $U_{i_0}$ mit $0\in U_{i_0}$. Es gibt $\varepsilon>0$ mit $(-\varepsilon,\varepsilon)\subseteq U_{i_0}$.`,R`Wähle $N$ mit $1/n<\varepsilon$ für $n\ge N$. Wähle für jeden der endlich vielen übrigen Punkte eine überdeckende Menge. Zusammen mit $U_{i_0}$ ergibt dies eine endliche Teilüberdeckung.`,R`In $K\setminus\{0\}$ konvergiert $1/n$ gegen den fehlenden Punkt $0$. Die Menge ist nicht abgeschlossen, also nicht kompakt.`]},
{id:'compact-union',title:'Vereinigung und Durchschnitt',source:'B.3.3 · Indexmenge in (a) nichtleer',prompt:'Beweise: Der Durchschnitt einer nichtleeren Familie kompakter Mengen und die Vereinigung endlich vieler kompakter Mengen in einem metrischen Raum sind kompakt.',hint:'Der Durchschnitt liegt abgeschlossen in einer kompakten Menge. Für die Vereinigung Teilüberdeckungen kombinieren.',steps:[R`Sei $I\ne\varnothing$, $i_0\in I$. Alle $K_i$ sind abgeschlossen. Daher ist $C=\bigcap_{i\in I}K_i$ abgeschlossen und $C\subseteq K_{i_0}$. Als abgeschlossene Teilmenge einer kompakten Menge ist $C$ kompakt.`,R`Sei $(U_i)$ eine offene Überdeckung von $K_1\cup\cdots\cup K_m$. Für jedes $K_j$ existiert eine endliche Teilüberdeckung. Ihre Vereinigung ist endlich und überdeckt die gesamte Vereinigung.`],pitfall:R`$\bigcup_{n\ge1}[0,n]=[0,\infty)$ ist nicht kompakt.`},
{id:'compact-images',title:'Summen, Differenzen, Produkte',source:'B.3.4(a–c)',prompt:R`Für $A\subseteq\mathbb R$ kompakt zeige, dass $A+A$, $A-A$ und $A\cdot A$ kompakt sind.`,hint:'Stetige Bilder von A × A.',steps:[R`$A\times A$ ist kompakt. Die Funktionen $s(x,y)=x+y$, $d(x,y)=x-y$, $p(x,y)=xy$ sind stetig.`,R`Die gesuchten Mengen sind $s(A\times A)$, $d(A\times A)$ und $p(A\times A)$, also stetige Bilder einer kompakten Menge.`]},
{id:'compact-quotient',title:'Quotienten: fehlende Voraussetzung',source:'B.3.4(d) · Quellenfehler',prompt:R`Ist $Q=\{x/y:x,y\in A,\ y\ne0\}$ für jedes kompakte $A\subseteq\mathbb R$ kompakt?`,hint:'Halte den Zähler bei 1 und lasse den Nenner gegen 0 gehen.',steps:[R`Für $A=\{0\}\cup\{1/n:n\ge1\}$ gilt $n=1/(1/n)\in Q$ für alle $n\ge1$. $Q$ ist unbeschränkt, also nicht kompakt.`,R`Mit $0\notin A$ ist $(x,y)\mapsto x/y$ auf $A\times A$ stetig. Unter dieser Zusatzannahme ist $Q$ kompakt.`]},
{id:'compact-local-test',title:'Kompakte Testmengen',source:'B.3.5(b)',prompt:R`Sei $X\subseteq\mathbb R^n$ und $X\cap K$ für jede kompakte Menge $K$ kompakt. Zeige: $X$ ist abgeschlossen.`,hint:'Ergänze die Menge einer konvergenten Folge um ihren Grenzwert.',steps:[R`Sei $(x_k)\subseteq X$ mit $x_k\to x$. $K=\{x\}\cup\{x_k:k\ge1\}$ ist kompakt: Eine offene Menge um $x$ enthält alle bis auf endlich viele Folgenglieder.`,R`Nach Voraussetzung ist $X\cap K$ kompakt und damit abgeschlossen. Wegen $x_k\in X\cap K$ folgt $x\in X\cap K\subseteq X$. Das Folgenkriterium liefert die Behauptung.`]},
{id:'compact-distance',title:'Abstand zum Komplement',source:'B.3.5(a)',prompt:R`Sei $K\subseteq U\subseteq\mathbb R^n$, $K$ kompakt, $U$ offen. Zeige: Es gibt $\varepsilon>0$ mit $x\in K$, $\|x-y\|<\varepsilon\Rightarrow[x,y]\subseteq U$.`,hint:'Überdecke K durch Kugeln, deren doppelte Radien noch in U liegen.',steps:[R`Für $K=\varnothing$ ist alles klar. Sonst wähle zu jedem $a\in K$ ein $r_a>0$ mit $B_{2r_a}(a)\subseteq U$. Endlich viele $B_{r_i}(a_i)$ überdecken $K$. Setze $\varepsilon=\min_i r_i>0$.`,R`Für $x\in B_{r_i}(a_i)$ und $z\in[x,y]$ gilt $\|z-x\|\le\|y-x\|<\varepsilon$, also $\|z-a_i\|<\varepsilon+r_i\le2r_i$. Somit liegt die Strecke in $U$.`]},
{id:'heine-proof',title:'Heine–Borel beweisen',source:'Lecture Notes · Sätze 1.10–1.11',prompt:'Beweise Heine–Borel mit Folgenkompaktheit und Bolzano–Weierstraß.',hint:'Beschränktheit liefert eine Teilfolge; Abgeschlossenheit den richtigen Grenzwert.',steps:[R`Sei $K$ kompakt. Für $x_k\in K$ mit $x_k\to x$ besitzt die Folge eine Teilfolge mit Grenzwert in $K$. Wegen Eindeutigkeit ist dieser Grenzwert $x$. Also ist $K$ abgeschlossen.`,R`Wäre $K$ unbeschränkt, wähle $x_k\in K$ mit $\|x_k\|\ge k$. Keine Teilfolge kann konvergieren. Widerspruch zur Folgenkompaktheit.`,R`Umgekehrt besitzt jede Folge in einer beschränkten Menge nach Bolzano–Weierstraß eine konvergente Teilfolge. Ist $K$ abgeschlossen, liegt deren Grenzwert in $K$. Also ist $K$ folgenkompakt und damit kompakt.`]}
]};
