const R=String.raw;
export default {id:'implizite-funktionen',title:'Implizite Funktionen',description:'Gleichungen lokal auflösen und die Lösung ableiten.',priority:'Schwerpunkt',source:'Lecture Notes · §2.3; Blatt 5; Altklausur 3',visual:'implicit',generator:'implicit',goals:['Freie und abhängige Variablen festlegen.','Die Nullstellenbedingung immer zuerst prüfen.','Die richtige quadratische Teilmatrix wählen.','Das lineare Gleichungssystem für die Ableitung lösen.'],theory:[
{id:'implicit-theorem',kind:'Satz',title:'Satz über implizite Funktionen',text:R`Sei $E\subseteq\mathbb R^n\times\mathbb R^m$ offen und $F\in C^1(E,\mathbb R^n)$. Sei $(a,b)\in E$ mit $F(a,b)=0$ und $D_xF(a,b)$ invertierbar. Dann existieren offene Umgebungen $U$ von $a$, $V$ von $b$ mit $U\times V\subseteq E$ und eine eindeutige Funktion $g\in C^1(V,U)$ mit $g(b)=a$, sodass $$F(x,y)=0\ \Longleftrightarrow\ x=g(y)\quad((x,y)\in U\times V).$$ Zudem $$Dg(y)=-[D_xF(g(y),y)]^{-1}D_yF(g(y),y).$$`,source:'Lecture Notes · Satz 2.21, S. 35; T.5.2; Altklausur 3(a)',checks:['F von Klasse C¹ auf offenem Gebiet.','F(a,b)=0.','D_xF quadratisch und invertierbar.','Lokale Eindeutigkeit und g(b)=a.','Minuszeichen und richtige Matrixreihenfolge.']},
{id:'implicit-scalar',kind:'Spezialfall',title:'Eine Gleichung, eine abhängige Variable',text:R`Sei $F\in C^1(E,\mathbb R)$ auf offenem $E\subseteq\mathbb R^2$, $F(a,b)=0$ und $F_y(a,b)\ne0$. Dann ist $F(x,y)=0$ nahe $(a,b)$ eindeutig als $y=g(x)$ mit $g\in C^1$ und $g(a)=b$ lösbar. Es gilt $$g'(x)=-\frac{F_x(x,g(x))}{F_y(x,g(x))}.$$`,source:'Lecture Notes · §2.3; B.5.4',checks:['Hier ist y abhängig, im allgemeinen Satz oben ist x abhängig.','Nicht Variablennamen auswendig anwenden, sondern die gewünschte Auflösung lesen.']},
{id:'implicit-blocks',kind:'Rechenschema',title:'Ableitung als lineares Gleichungssystem',text:R`Bei $F(g(y),y)=0$ liefert die Kettenregel $$D_xF\,Dg+D_yF=0.$$ Alle Ableitungen von $F$ werden in $(g(y),y)$ ausgewertet. Löse daher $A\,Dg=-B$ mit $A=D_xF$, $B=D_yF$. Die Zahl der abhängigen Variablen ist gleich der Zahl der Gleichungen.`,source:'Lecture Notes · §2.3',checks:['A ist n × n, B ist n × m, Dg ist n × m.','Eine rechteckige Gesamt-Jacobi-Matrix wird nicht invertiert.']}
],exercises:[
{id:'implicit-simple',title:'Eine Gleichung lokal auflösen',source:'B.5.4(a)',prompt:R`Sei $F(x,y)=x-3y+e^{xy^2}+2$. Ist $F(x,y)=0$ bei $(0,1)$ nach $y$ auflösbar? Berechne $g'(0)$ für $y=g(x)$.`,hint:'Prüfe F(0,1), dann F_y(0,1).',steps:[R`$F(0,1)=0-3+1+2=0$, und $F\in C^\infty(\mathbb R^2)$.`,R`$F_x=1+y^2e^{xy^2}$ und $F_y=-3+2xye^{xy^2}$. Somit $F_x(0,1)=2$, $F_y(0,1)=-3\ne0$.`,R`Der implizite Funktionensatz liefert lokal eindeutig $y=g(x)$ mit $g(0)=1$ und $g'(0)=-2/(-3)=2/3$.`]},
{id:'implicit-loop',title:'Wenn die Voraussetzung ausfällt',source:'B.5.4(b)',prompt:R`Für $F(x,y)=y^2-x^2(1-x^2)$ bestimme alle Punkte der Nullstellenmenge, bei denen sie lokal der Graph einer $C^1$-Funktion $y=g(x)$ ist.`,hint:'F_y = 2y. Untersuche die übrigen Punkte gesondert.',steps:[R`Für $y\ne0$ ist $F_y=2y\ne0$. Auf der Nullstellenmenge sind dies genau $0<|x|<1$ und $y=\pm x\sqrt{1-x^2}$.`,R`Dort gilt $g'(x)=-( -2x+4x^3)/(2y)=(x-2x^3)/y$.`,R`Für $y=0$ liegen $(0,0),(1,0),(-1,0)$ auf der Kurve. Nahe $(0,0)$ gibt es für kleine $x\ne0$ zwei y-Werte nahe 0. Die ganze Nullstellenmenge ist dort kein eindeutiger Graph, obwohl einzelne glatte Zweige existieren.`,R`Bei $x=\pm1$ kann ein solcher $C^1$-Graph nicht existieren: Differenzieren von $F(x,g(x))=0$ würde $F_x+F_yg'=0$ ergeben, aber dort ist $F_y=0$ und $F_x=\pm2\ne0$.`],pitfall:'Eine verschwindende Teilableitung allein beweist noch nicht, dass Auflösen unmöglich ist.'},
{id:'implicit-system',title:'Zwei Gleichungen, zwei abhängige Variablen',source:'B.5.5',prompt:R`Sei $f\in C^1(\mathbb R^2)$ mit $f(2,-1)=-1$. Setze $G=f(x,y)+u^2$, $H=ux+3y^3+u^3$. Wann kann man nahe $(2,-1,1)$ nach $x=g(y)$ und $u=h(y)$ auflösen? Berechne die Ableitungen für $Df(2,-1)=(1,-3)$.`,hint:'Die Spalten für x und u bilden die zu invertierende Teilmatrix.',steps:[R`$(G,H)(2,-1,1)=(0,0)$. Die Teilmatrix nach $(x,u)$ ist am Punkt $$A=\begin{pmatrix}f_x(2,-1)&2\\1&5\end{pmatrix}.$$ Die Bedingung $5f_x(2,-1)-2\ne0$ sichert lokale $C^1$-Auflösbarkeit.`,R`Für $Df=(1,-3)$ gilt $A=\begin{pmatrix}1&2\\1&5\end{pmatrix}$ und $B=\binom{-3}{9}$.`,R`Löse $A\binom{g'(-1)}{h'(-1)}=-B=\binom3{-9}$. Subtraktion liefert $3h'=-12$, also $h'=-4$ und $g'=11$.`]},
{id:'implicit-exam',title:'Aufgabe 3: Original prüfen und korrigiert lösen',source:'Altklausur 3(b) · 6 Punkte · Druckfehler',points:6,prompt:R`Abgedruckt ist $$F(x_1,x_2,y)=\binom{-e^{x_1}+2x_2+\cos y}{\pi x_1^2+5x_2^3+\sin y+5}.$$ Prüfe die behauptete Nullstelle $(0,-1,\pi)$. Bearbeite danach die ausdrücklich korrigierte Fassung $\widetilde F=F+(4,0)^\top$: Jacobi-Matrix, lokale Lösung $(x_1,x_2)=g(y)$ und $Dg(\pi)$.`,hint:'Im Original ist die erste Komponente −4. Die ergänzte Konstante ändert die Ableitung nicht.',steps:[R`$F(0,-1,\pi)=(-1-2-1,\,-5+5)=(-4,0)$. Die Nullstellenbehauptung ist falsch. Eine Lösung mit den im Original geforderten Eigenschaften existiert nicht. Für die korrigierte Fassung ist $\widetilde F(0,-1,\pi)=0$.`,R`$$D\widetilde F=\begin{pmatrix}-e^{x_1}&2&-\sin y\\2\pi x_1&15x_2^2&\cos y\end{pmatrix},\quad D\widetilde F(0,-1,\pi)=\begin{pmatrix}-1&2&0\\0&15&-1\end{pmatrix}.$$`,R`$A=D_{(x_1,x_2)}\widetilde F=\begin{pmatrix}-1&2\\0&15\end{pmatrix}$ hat Determinante $-15\ne0$. Da $\widetilde F\in C^1$, existiert lokal eindeutig $g$ mit $g(\pi)=(0,-1)$ und $\widetilde F(g(y),y)=0$.`,R`Mit $B=\binom0{-1}$ lösen wir $A\,Dg(\pi)=\binom01$. Daraus $15g_2'=1$ und $-g_1'+2g_2'=0$, also $$Dg(\pi)=\binom{2/15}{1/15}.$$`],pitfall:'Die Reparatur +4 ist eine gekennzeichnete Übungsfassung. Niemals die falsche Nullstellenbehauptung des Originals übernehmen.'}
]};
