const R=String.raw;
const part=(label,prompt,steps,checks)=>({label,prompt,steps,checks});
const task=(id,title,source,parts)=>({id,title,source,parts});

export const trainingSets=[
 {id:'fokus-a',title:'Schwerpunkte · A',description:'Kompaktheit, Winkelverdopplung, skalare Auflösung und Taylor an einem verschobenen Punkt.',source:'Eigene Übungsvarianten nach Blatt 3–5 und 7; keine Originalklausur.',tasks:[
  task('a-compact','Kompaktheit','Varianten zu B.3.3–B.3.5',[
   part('a','Formuliere Heine–Borel mit dem zulässigen umgebenden Raum.',[R`Für $K\subset\mathbb R^n$, allgemeiner in einem endlichdimensionalen normierten Raum, gilt: $K$ ist genau dann kompakt, wenn $K$ abgeschlossen und beschränkt ist.`],['Endlichdimensionalen normierten Raum genannt.','Beide Richtungen und beide Eigenschaften formuliert.']),
   part('b',R`Ist $K=\{(x,y):1\le x^2+y^2\le4,\ x\ge0\}$ kompakt? Begründe.`,[R`$K$ ist der Schnitt der abgeschlossenen Urbilder $\{1\le x^2+y^2\le4\}$ und $\{x\ge0\}$ unter stetigen Funktionen. Außerdem gilt $\|(x,y)\|\le2$. Heine–Borel liefert Kompaktheit.`],['Abgeschlossenheit als Urbild/Schnitt begründet.','Normschranke 2 angegeben.']),
   part('c',R`Untersuche $M=\{(1/n,1/n^2):n\ge1\}$ und $M\cup\{(0,0)\}$ auf Kompaktheit.`,[R`Die Folge $(1/n,1/n^2)$ liegt in $M$ und konvergiert gegen $(0,0)\notin M$. Also ist $M$ nicht abgeschlossen und nicht kompakt.`,R`Für die ergänzte Menge: Jede offene Überdeckung enthält eine Umgebung von $(0,0)$, die alle bis auf endlich viele Folgenglieder enthält. Endlich viele zusätzliche Überdeckungsmengen reichen für den Rest. Also ist $M\cup\{(0,0)\}$ kompakt.`],['Fehlenden Grenzwert konkret angegeben.','Kompaktheit der ergänzten Menge begründet.'])]),
  task('a-inverse','Umkehrfunktionen','Variante zu B.4.5',[
   part('a',R`Sei $f(x,y)=(e^x\cos(2y),e^x\sin(2y))$ auf $A=\mathbb R\times(0,\pi)$. Berechne $Df$ und zeige lokale Umkehrbarkeit.`,[R`$$Df=e^x\begin{pmatrix}\cos(2y)&-2\sin(2y)\\\sin(2y)&2\cos(2y)\end{pmatrix},\qquad\det Df=2e^{2x}>0.$$ Das Gebiet ist offen und $f\in C^1$. Satz 2.17 liefert lokale $C^1$-Umkehrbarkeit in jedem Punkt.`],['Jacobi-Matrix einschließlich Faktor 2 korrekt.','Offenes Gebiet, C¹ und Determinante geprüft.']),
   part('b',R`Zeige Injektivität auf $A$ und bestimme $f(A)$.`,[R`Gleiche Bilder haben gleiche Normen, also $e^x=e^{x'}$ und $x=x'$. Die Winkel $2y,2y'$ liegen beide in $(0,2\pi)$; gleiche Sinus- und Kosinuswerte erzwingen $y=y'$.`,R`Jeder positive Radius und jeder Winkel aus $(0,2\pi)$ wird erreicht. Daher $$f(A)=\mathbb R^2\setminus\{(u,0):u\ge0\}.$$`],['Globale Injektivität eigenständig begründet.','Ausgeschlossene Halbgerade einschließlich Ursprung richtig.']),
   part('c',R`Berechne $D(f^{-1})(0,2)$.`,[R`Das Urbild ist $(\log2,\pi/4)$. Dort gilt $$Df=\begin{pmatrix}0&-4\\2&0\end{pmatrix},\qquad D(f^{-1})(0,2)=\begin{pmatrix}0&1/2\\-1/4&0\end{pmatrix}.$$`],['Zuerst das richtige Urbild bestimmt.','Matrix am Urbild invertiert.'])]),
  task('a-implicit','Implizite Funktionen','Variante zu B.5.4',[
   part('a',R`Für $F(x,y)=x^2+xy+y^2-7$ begründe die lokale Auflösung $y=g(x)$ bei $(1,2)$.`,[R`$F(1,2)=1+2+4-7=0$. $F$ ist glatt, und $F_y(1,2)=x+2y=5\ne0$. Es gibt lokal eindeutig eine $C^1$-Funktion $g$ mit $g(1)=2$ und $F(x,g(x))=0$.`],['Nullstellenbedingung geprüft.','Fᵧ und lokale Eindeutigkeit genannt.']),
   part('b',R`Berechne $g'(1)$. Ist am selben Punkt auch eine Auflösung $x=h(y)$ möglich? Berechne $h'(2)$.`,[R`$F_x(1,2)=2x+y=4$. Also $$g'(1)=-\frac45.$$ Wegen $F_x(1,2)\ne0$ ist auch die andere Auflösung möglich, mit $$h'(2)=-\frac54.$$`],['Je nach abhängiger Variable den richtigen Nenner verwendet.','Beide Ableitungen mit Minuszeichen berechnet.'])]),
  task('a-taylor','Taylor am verschobenen Punkt','Variante zu B.7.1–B.7.2',[
   part('a',R`Entwickle $f(x,y)=\log(1+x+y^2)+e^{(x-1)y}$ bis Grad 2 um $a=(1,0)$. Gib eine Restabschätzung an.`,["Setze $u=x-1$, $v=y$. Dann $$\\ln(2+u+v^2)=\\ln2+\\ln\\!\\left(1+\\frac{u+v^2}{2}\\right).$$ Das Logarithmuspolynom liefert nach Einsetzen $$\\begin{aligned}&\\ \\ln2+\\frac{u+v^2}{2}-\\frac{(u+v^2)^2}{8}\\\\&=\\ln2+\\frac u2+\\frac{v^2}{2}-\\frac{u^2}{8}-\\frac{uv^2}{4}-\\frac{v^4}{8}.\\end{aligned}$$ Die letzten beiden Terme haben Grad 3 bzw. 4. Für $e^{uv}$ genügt das Polynom $1+uv$.","Addieren der Terme bis Grad 2 und Zurücksetzen liefert $$\\boxed{\\begin{aligned}T_2(x,y)&=1+\\ln2+\\frac{x-1}{2}-\\frac{(x-1)^2}{8}\\\\&\\quad+(x-1)y+\\frac{y^2}{2}.\\end{aligned}}$$","Da $f\\in C^{3}$ in einer offenen Umgebung von $(1,0)$ ist, gilt\n$$\\begin{gathered}\nf(x,y)=T_2(x,y)+R_2(x,y),\\\\\n|R_2(x,y)|\\le C\\|(x,y)-(1,0)\\|^{3}.\n\\end{gathered}$$\nDie Abschätzung gilt nahe $(1,0)$ für eine feste Konstante $C>0$."],['Mit x−1 statt mit x entwickelt.','Gesamtgrad korrekt begrenzt.','Rest mit Regularität in einer Umgebung begründet.']),
   part('b',R`Bestimme $\nabla f(a)$ und $H_f(a)$ und schreibe die Entwicklung in Matrixform.`,["Koeffizientenvergleich in $(u,v)$ liefert $$\\nabla f(a)=\\binom{1/2}0,\\qquad H_f(a)=\\begin{pmatrix}-1/4&1\\\\1&1\\end{pmatrix}.$$ Die Diagonaleinträge sind $2(-1/8)=-1/4$ und $2(1/2)=1$, der gemischte Eintrag ist 1. Mit $h=(u,v)^T$ gilt $$\\begin{aligned}f(a+h)&=1+\\ln2+(1/2,0)h\\\\&\\quad+\\frac12h^TH_f(a)h+R_2(a+h).\\end{aligned}$$ Wie in Teil a gilt $|R_2(a+h)|\\le C\\|h\\|^3$ für kleine $h$ und eine feste Konstante $C>0$, weil $f\\in C^3$ nahe $a$ ist."],['Reine quadratische Koeffizienten verdoppelt.','Gemischten Koeffizienten ohne zusätzlichen Faktor 2 eingetragen.'])])]},
 {id:'fokus-b',title:'Schwerpunkte · B',description:'Kompakte Graphen, globale Inverse, zwei freie Variablen und Taylor in drei Variablen.',source:'Eigene Übungsvarianten nach Lecture Notes und Blatt 3–7; keine Originalklausur.',tasks:[
  task('b-compact','Graphen und Kompaktheit','Variante zu Kompaktheit und stetigen Bildern',[
   part('a',R`Ist $K=\{(x,1/x):1\le x\le2\}$ kompakt?`,[R`$[1,2]$ ist kompakt. Die Abbildung $x\mapsto(x,1/x)$ ist darauf stetig und ihr Bild genau $K$. Also ist $K$ nach Satz 1.12 kompakt.`],['Kompakte Ausgangsmenge genannt.','Stetige Abbildung und ihr Bild korrekt angegeben.']),
   part('b',R`Was ändert sich für $M=\{(x,1/x):0<x\le1\}$? Ist $M$ in $\mathbb R^2$ abgeschlossen?`,[R`Die Punkte $(1/n,n)\in M$ haben unbeschränkte Norm. Daher ist $M$ nicht kompakt.`,R`Trotzdem ist $M$ abgeschlossen: $$M=\{(x,y):xy=1\}\cap\{x\ge0\}\cap\{x\le1\}.$$ Alle drei Mengen sind abgeschlossen; $xy=1$ schließt $x=0$ aus.`],['Unbeschränktheit konkret gezeigt.','Fehlende Kompaktheit nicht mit fehlender Abgeschlossenheit verwechselt.'])]),
  task('b-inverse','Lokale und globale Umkehrbarkeit','Variante zum Umkehrsatz',[
   part('a',R`Sei $f(x,y)=(x+y^2,y)$ auf $\mathbb R^2$. Zeige lokale Umkehrbarkeit in jedem Punkt.`,[R`$f$ ist glatt und $$Df(x,y)=\begin{pmatrix}1&2y\\0&1\end{pmatrix},\qquad\det Df=1.$$ Der Umkehrsatz gilt überall.`],['C¹ und Determinante geprüft.','Zunächst nur lokal geschlossen.']),
   part('b',R`Bestimme die globale Umkehrfunktion und $D(f^{-1})(3,1)$.`,[R`Aus $(u,v)=(x+y^2,y)$ folgt eindeutig $(x,y)=(u-v^2,v)$. Jedes $(u,v)\in\mathbb R^2$ besitzt dieses Urbild. Daher ist $$f^{-1}(u,v)=(u-v^2,v).$$`,R`$$D(f^{-1})(3,1)=\begin{pmatrix}1&-2\\0&1\end{pmatrix}.$$ Kontrolle durch Invertieren von $Df(2,1)$.`],['Existenz und Eindeutigkeit aller Urbilder gezeigt.','Ableitung am richtigen Punkt berechnet.'])]),
  task('b-implicit','Zwei abhängige und zwei freie Variablen','Variante zu Lecture Notes · Example 10',[
   part('a',R`Seien $F_1(u,v,s,t)=u^2+v+s-2$ und $F_2(u,v,s,t)=u+2v+t-3$. Begründe die lokale Auflösung $(u,v)=g(s,t)$ bei $(1,1,0,0)$.`,[R`$F(1,1,0,0)=(0,0)$ und $F$ ist glatt. Der Block nach den abhängigen Variablen ist $$A=\begin{pmatrix}2&1\\1&2\end{pmatrix},\qquad\det A=3\ne0.$$ Satz 2.21 liefert die eindeutige lokale $C^1$-Lösung mit $g(0,0)=(1,1)$.`],['Abhängige und freie Variablen korrekt getrennt.','Nullstelle und invertierbaren 2×2-Block geprüft.']),
   part('b',R`Berechne die gesamte Matrix $Dg(0,0)$.`,[R`Der Block nach $(s,t)$ ist $B=I_2$. Daher $$Dg(0,0)=-A^{-1}B=-\frac13\begin{pmatrix}2&-1\\-1&2\end{pmatrix}=\begin{pmatrix}-2/3&1/3\\1/3&-2/3\end{pmatrix}.$$`],['Beide Spalten berechnet.','A · Dg + B = 0 kontrolliert.'])]),
  task('b-taylor','Taylor mit drei Variablen','Variante zu B.7.3',[
   part('a',R`Bestimme $T_2$ bei 0 von $$f(x,y,z)=\frac{e^{x+y}}{1-z}-1+\sin(xz).$$`,["Für die Rechnung bis Grad 2 verwenden wir die Polynome $1+x+y+(x+y)^2/2$ für $e^{x+y}$ und $1+z+z^2$ für $(1-z)^{-1}$. Multipliziere sie, ziehe 1 ab und behalte nur Gesamtgrad höchstens 2. Aus $\\sin(xz)$ kommt noch $xz$ hinzu.","Damit $$T_2=x+y+z+\\frac12x^2+xy+\\frac12y^2+2xz+yz+z^2.$$ Nahe 0 ist der Nenner ungleich null.","Da $f\\in C^{3}$ in einer offenen Umgebung von $0$ ist, gilt\n$$\\begin{gathered}\nf(x,y,z)=T_2(x,y,z)+R_2(x,y,z),\\\\\n|R_2(x,y,z)|\\le C\\|(x,y,z)\\|^{3}.\n\\end{gathered}$$\nDie Abschätzung gilt nahe $0$ für eine feste Konstante $C>0$."],['Linearen z-Term und z² nicht verloren.','Beide Beiträge zum xz-Term erfasst.','Restordnung begründet.']),
   part('b',R`Lies Gradient und Hesse-Matrix ab.`,[R`$$\nabla f(0)=\begin{pmatrix}1\\1\\1\end{pmatrix},\qquad H_f(0)=\begin{pmatrix}1&1&2\\1&1&1\\2&1&2\end{pmatrix}.$$`],['Diagonale Koeffizienten verdoppelt.','Symmetrische gemischte Einträge korrekt.'])])]},
 {id:'werkzeuge',title:'Weiterer Übungsstoff',description:'Banach, Richtungsableitungen, kritische Punkte und Laplace.',source:'Eigene Übungsvarianten nach Blatt 3, 6 und 7.',tasks:[
  task('c-fixed','Banach anwenden','Variante zu B.3.1',[
   part('a',R`Zeige mit Banach, dass $\varphi(x)=(x^2+1)/4$ auf $[0,1]$ genau einen Fixpunkt hat. Bestimme ihn.`,[R`$[0,1]$ ist nichtleer und vollständig. Für $x\in[0,1]$ gilt $\varphi(x)\in[1/4,1/2]\subset[0,1]$.`,R`Für $x,y\in[0,1]$ gilt $|\varphi(x)-\varphi(y)|=|x-y||x+y|/4\le\tfrac12|x-y|$. Banach liefert genau einen Fixpunkt.`,R`Die Gleichung $x^2-4x+1=0$ ergibt $x=2\pm\sqrt3$. Nur $2-\sqrt3$ liegt in $[0,1]$.`],['Vollständigkeit und Selbstabbildung gezeigt.','Einheitlichen Faktor 1/2 nachgewiesen.','Nur die Lösung im richtigen Intervall gewählt.'])]),
  task('c-gradient','Gradient und Richtung','Variante zu B.7.5',[
   part('a',R`Bestimme für $f(x,y,z)=xe^y+z^2$ in $(1,0,1)$ die Richtung des stärksten Anstiegs und die maximale Richtungsableitung. Gibt es kritische Punkte?`,[R`$\nabla f=(e^y,xe^y,2z)^\top$, am gegebenen Punkt also $(1,1,2)^\top$. Die Einheitsrichtung ist $(1,1,2)^\top/\sqrt6$ und die maximale Richtungsableitung $\sqrt6$.`,R`Es gibt keine kritischen Punkte, weil die erste Komponente $e^y$ niemals null ist.`],['Normierte Richtung und maximale Steigung unterschieden.','Kritische Punkte mit dem ganzen Gradienten geprüft.'])]),
  task('c-extrema','Wenn die Hesse-Matrix nicht entscheidet','Variante zu B.7.4',[
   part('a',R`Klassifiziere den Ursprung für $f(x,y)=x^4+y^2$ und $g(x,y)=-x^4+y^2$. Was sagt jeweils die Hesse-Matrix?`,[R`Beide Gradienten verschwinden am Ursprung, und beide Hesse-Matrizen sind $\begin{pmatrix}0&0\\0&2\end{pmatrix}$. Sie sind nur positiv semidefinit, daher entscheidet das Hesse-Kriterium nicht.`,R`Für $(x,y)\ne(0,0)$ gilt $f(x,y)>0=f(0,0)$: striktes Minimum. Bei $g$ gilt $g(x,0)<0$ für $x\ne0$ und $g(0,y)>0$ für $y\ne0$: kein lokales Extremum.`],['Semidefinite Matrix nicht als Beweis eines Minimums verwendet.','Klassifikation durch Funktionswerte begründet.'])]),
  task('c-laplace','Laplace einer Radialfunktion','Variante zu B.6.5',[
   part('a',R`Berechne $\Delta u$ für $u(x)=\log(1+\|x\|^2)$ auf $\mathbb R^n$.`,[R`Setze $s=\|x\|^2$, $q(s)=\log(1+s)$. Dann $q'=1/(1+s)$ und $q''=-1/(1+s)^2$.`,R`$$\Delta u=2nq'(s)+4sq''(s)=\frac{2n+(2n-4)s}{(1+s)^2}.$$`],['Kettenregel und Raumdimension berücksichtigt.','Reine zweite Ableitungen addiert.'])])]} 
];
