import {worksheets} from './worksheet-data.js';
import {trainingSets} from './training.js';
export const R=String.raw;
export const part=(prompt,...steps)=>({prompt,steps});
export const numberField=(label,answer)=>({label,answer:String(answer)});
export const question=(prompt,correct,explanation,wrong,whyWrong,other,whyOther)=>({prompt,options:[
 {text:correct,correct:true,explanation},{text:wrong,correct:false,explanation:whyWrong},{text:other,correct:false,explanation:whyOther}
]});
export function original(number,labels){const w=worksheets[number];return {source:`Originalaufgabe · ${w.source}`,sourceHref:`#/blaetter/${w.sheet}/${number}`,intro:w.intro,parts:w.parts.filter(p=>!labels||labels.includes(p.label)).map(p=>({...p}))};}
export function previous(id,indices){const t=trainingSets.flatMap(s=>s.tasks).find(t=>t.id===id);return {source:`Eigene Variante · ${t.source.replace(/^Variante[n]? zu /,'')}`,intro:'',parts:t.parts.filter((_,i)=>!indices||indices.includes(i)).map(p=>({...p}))};}
export const topics={compact:'Kompaktheit',inverse:'Umkehrfunktionen',implicit:'Implizite Funktionen',taylor:'Taylor'};
export const standardSeries={
 exp:[R`$e^w$`,R`$1+w+\frac{w^2}{2}+\frac{w^3}{6}$`],
 log:[R`$\ln(1+w)$`,R`$w-\frac{w^2}{2}+\frac{w^3}{3}$`],
 sin:[R`$\sin w$`,R`$w-\frac{w^3}{6}$`],
 cos:[R`$\cos w$`,R`$1-\frac{w^2}{2}$`],
 geometric:[R`$\frac1{1-w}$`,R`$1+w+w^2+w^3$`]
};
export const neededSeries={
 't-logexp':['log','exp'],'t-product':['exp','cos','sin'],'t-log-shift':['log'],
 't-shift':['log','exp'],'t-exp-shift':['exp'],'t-fraction':['exp','geometric','sin'],'t-read-shift':['exp']
};
const inverseRecipe=[
 R`Kläre den Punkt: $a$ ist die Eingabe von $f$, $b=f(a)$ ihre Ausgabe. Ist nur $b$ für die Umkehrableitung gegeben, löse zuerst $f(a)=b$ im angegebenen Gebiet. Ist $a$ bereits gegeben, entfällt diese Suche.`,
 R`Prüfe, dass das Gebiet um $a$ offen und $f\in C^1$ ist. Stelle $Df$ auf: Zeilen sind Ausgaben, Spalten sind Eingabevariablen.`,
 R`Setze $a$ ein und berechne $\det Df(a)$. Bei einer Frage nach allen Punkten untersuchst du stattdessen, wo die allgemeine Determinante ungleich 0 ist.`,
 R`Bei $\det Df(a)\ne0$ liefert der Umkehrsatz eine lokale $C^1$-Umkehrfunktion. Ist nur lokale Umkehrbarkeit gefragt, bist du hier fertig. Globale Injektivität braucht zusätzlich einen eigenen Nachweis.`,
 R`Für die Umkehrableitung rechnest du mit derselben Matrix weiter: $$D(f^{-1})(b)=[Df(a)]^{-1},\qquad f(a)=b.$$`,
 R`Bei einer $2\times2$-Matrix: $$M=\begin{pmatrix}p&q\\r&s\end{pmatrix}\quad\Longrightarrow\quad M^{-1}=\frac1{ps-qr}\begin{pmatrix}s&-q\\-r&p\end{pmatrix}.$$ Diagonale vertauschen, die anderen Vorzeichen wechseln, durch die Determinante teilen. Bei $3\times3$ verwende Gauß–Jordan. Die Matrix wird bei $a$ ausgewertet, die gesuchte Umkehrableitung bei $b$.`
];
export const families={
 closed:{topic:'compact',title:'Abgeschlossen und beschränkt',page:'2–3',recipe:[R`Schreibe die Menge durch Bedingungen an die Koordinaten. Bei $(x,1/x)$ heißt die zweite Koordinate $y$; die Beziehung lautet $xy=1$. Behalte auch die Bedingung an $x$.`,R`Abgeschlossenheit: Schreibe die Bedingungen als Urbilder abgeschlossener Mengen unter Funktionen, die auf ganz $\mathbb R^n$ stetig sind. Ihr Schnitt ist abgeschlossen.`,R`Beschränktheit: Finde eine feste Zahl $R$ mit $\|z\|\le R$ für jeden Punkt $z$ der Menge. Zum Beispiel: $x^2+y^2\le4$ ergibt $\|(x,y)\|\le2$. Eine Bedingung genügt dafür, wenn sie bereits alle Punkte beschränkt.`,R`Schluss in $\mathbb R^n$: abgeschlossen und beschränkt, also nach Heine–Borel kompakt.`]},
 noncompact:{topic:'compact',title:'Kompaktheit widerlegen',page:4,recipe:[R`Prüfe, ob ein Grenzpunkt fehlt oder die Menge unbeschränkt ist. Einer der beiden Nachweise reicht.`,R`Fehlender Punkt: Wähle $z_n$ in der Menge und zeige $z_n\to z$ mit $z$ außerhalb.`,R`Unbeschränkt: Wähle $z_n$ in der Menge und zeige $\|z_n\|\to\infty$.`,R`Schreibe dazu, welche Eigenschaft fehlt. Ein erfolgloser Urbildansatz allein widerlegt nichts.`]},
 images:{topic:'compact',title:'Stetige Bilder und Mengenoperationen',page:'2b, 4a–4d',recipe:[R`Summe oder Produkt: Setze $K=A\times B$; bei nur einer gegebenen Menge $K=A\times A$. Begründe: $K$ ist als Produkt kompakter Mengen kompakt. Wähle $f(x,y)=x+y$ bzw. $f(x,y)=xy$.`,R`Stetiges Bild: Nenne die stetige Abbildung und schreibe ausdrücklich „gesuchte Menge $=f(K)$“. Dann ist sie kompakt. Bei einem Graphen $\{(t,h(t)):t\in[a,b]\}$ nutze $\varphi(t)=(t,h(t))$, sofern $h$ auf dem ganzen kompakten Intervall stetig ist.`,R`Quotient: Prüfe vor dem Bildsatz, dass der Nenner auf ganz $K$ nie null ist. Für ein Gegenbeispiel nimm $A=B=[0,1]$: Mit $x=1$, $y=1/n$ erhältst du $x/y=n\to\infty$, also eine unbeschränkte Quotientenmenge.`,R`Konkreter Schnitt oder konkrete Vereinigung: Bestimme zuerst, welche Punkte zur Menge gehören. Prüfe dann in $\mathbb R^n$ mit Heine–Borel. Allgemein gilt: Endliche Vereinigungen kompakter Mengen sind kompakt; ein abgeschlossener Schnitt, der in einer kompakten Menge liegt, ebenfalls. Eine unendliche Vereinigung ist nicht immer kompakt.`]},
 local:{topic:'inverse',title:'Lokale Umkehrbarkeit',page:'8–9a',recipe:inverseRecipe},
 image:{topic:'inverse',title:'Injektivität und Bild',page:'6–7b',recipe:[R`Falls Injektivität gefragt ist: Wähle zwei beliebige Eingaben $P,Q$ im Gebiet, setze $f(P)=f(Q)$ und zeige, dass alle Eingabekoordinaten übereinstimmen. Zum Widerlegen reichen zwei verschiedene zulässige Eingaben mit gleicher Ausgabe.`,R`Für die Bildmenge nenne die Ausgabe $(u,v)=f(P)$. Bei einer Polarform berechnest du ihren Radius $\rho=\sqrt{u^2+v^2}$, also die Norm der Ausgabe. Übertrage die erlaubten Eingaben auf die möglichen Radien. Beispiel: $e^x$ mit $x\in\mathbb R$ erreicht genau $(0,\infty)$.`,R`Bestimme die möglichen Winkel der Ausgabe: Bei $(r\cos\theta,r\sin\theta)$ mit $r>0$ ist das $\theta$, bei $(r^2\cos2\theta,r^2\sin2\theta)$ ist es $2\theta$. Prüfe, welche Ränder und ob der Ursprung dazugehören.`,R`Schreibe dieselbe geometrische Menge in Ausgabekoordinaten: $1\le\rho\le2$ wird zu $1\le u^2+v^2\le4$; die obere Hälfte wird zu $v\ge0$. Radius- und Winkelbedingungen müssen zusammen gelten.`,R`Zeige, dass jeder genannte Punkt erreicht wird: Wähle zu seinem Radius und Winkel eine zulässige Eingabe. Bei anderen Funktionsformen kannst du dafür direkt $(u,v)=f(P)$ nach den Eingaben auflösen. So prüfst du, ob deine Bildbeschreibung vollständig ist.`]},
 inverseDerivative:{topic:'inverse',title:'Ableitung der Umkehrfunktion',page:'8–10',recipe:inverseRecipe},
 scalar:{topic:'implicit',title:'Eine Gleichung auflösen',page:14,recipe:[R`Prüfe $F(a,b)=0$ und $F\in C^1$ nahe dem Punkt.`,R`Gesucht ist $y=g(x)$: Prüfe $F_y(a,b)\ne0$. Gesucht ist $x=h(y)$: Prüfe $F_x(a,b)\ne0$.`,R`Setze die Werte ein: $g'(a)=-\frac{F_x}{F_y}$ bzw. $h'(b)=-\frac{F_y}{F_x}$.`,R`Nenne lokale Existenz, Eindeutigkeit und den vorgegebenen Funktionswert. Ist der Nenner null, entscheidet diese Anwendung des Satzes nicht.`]},
 system:{topic:'implicit',title:'Gleichungssystem, eine freie Variable',page:'13, 15–17d',recipe:[R`Schreibe auf, welche Variablen gesucht sind und welche frei bleibt. Setze den angegebenen Punkt in jede Gleichung ein: Alle Werte müssen 0 sein. Prüfe $C^1$ auf einer offenen Umgebung.`,R`Stelle die Jacobi-Matrix auf und setze den Punkt ein. Die Spalten der gesuchten Variablen bilden $A$ in dieser Reihenfolge; die Spalte der freien Variablen ist $B$.`,R`Berechne $\det A$. Bei $\det A\ne0$ liefert der implizite Satz die eindeutige lokale $C^1$-Lösung durch den angegebenen Punkt. Ist nur die Auflösbarkeit gefragt, bist du hier fertig.`,R`Für die Ableitung invertierst du den Zahlenblock: $$A=\begin{pmatrix}a&b\\c&d\end{pmatrix},\qquad A^{-1}=\frac1{ad-bc}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}.$$ Diagonale vertauschen, die beiden anderen Vorzeichen wechseln, durch die Determinante teilen.`,R`Berechne $Dg=-A^{-1}B=A^{-1}(-B)$. Drehe zuerst alle Vorzeichen von $B$ um. Multipliziere dann jede Zeile der inversen Matrix mit diesem Vektor und rechne zuletzt den gemeinsamen Vorfaktor hinein. Die Ergebniszeilen gehören zu den gesuchten Variablen in der Reihenfolge von $A$.`]},
 multifree:{topic:'implicit',title:'Gleichungssystem, mehrere freie Variablen',page:'13 (Matrixrezept)',recipe:[R`Prüfe $F(a,b)=0$ und $C^1$ auf einer offenen Umgebung. $a$ enthält die gesuchten Variablen, $b$ die freien Variablen.`,R`Setze den Punkt in die Jacobi-Matrix ein. Die Spalten der gesuchten Variablen bilden $A$; die übrigen Spalten in ihrer Reihenfolge bilden $B$.`,R`Prüfe $\det A\ne0$. Dann gibt es lokal eindeutig eine $C^1$-Lösung mit $g(b)=a$.`,R`Invertiere $A$ einmal: Bei $A=\begin{pmatrix}a&b\\c&d\end{pmatrix}$ ist $A^{-1}=\frac1{ad-bc}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}$.`,R`Multipliziere $Dg=A^{-1}(-B)$. Jede Zeile mal jede Spalte ergibt einen Eintrag. Ergebniszeilen gehören zu den gesuchten Variablen, Ergebnisspalten zu den freien Variablen. Zur Kontrolle gilt $A\,Dg+B=0$.`]},
 series:{topic:'taylor',title:'Standardreihen einsetzen',page:'18–20',recipe:[R`Prüfe das Definitionsgebiet nahe dem Entwicklungspunkt. Verschiebe ihn auf $0$, falls nötig.`,R`Verwende die passende Tabellenreihe für $e^w,\ln(1+w),\sin w,\cos w$ oder $(1-w)^{-1}$. Setze den gesamten inneren Ausdruck für $w$ ein; dieser muss am verschobenen Entwicklungspunkt 0 sein. Beispiel: $\ln(2+u)=\ln2+\ln(1+u/2)$.`,R`Multipliziere und behalte nur den gefragten Gesamtgrad in den Verschiebungsvariablen: $xy$ hat Grad 2, $xy^2$ Grad 3. Hat der innere Ausdruck schon Grad 2, beginnt sein Quadrat erst bei Grad 4.`,R`Sammle die Terme zu $T_n$ und schreibe $f(x)=T_n(x)+R_n(x)$. Ist $f\in C^{n+1}$ nahe dem Entwicklungspunkt $a$, gilt $|R_n(x)|\le C\|x-a\|^{n+1}$ nahe $a$ für eine feste Konstante $C>0$. Hier ist $x$ der ganze Eingabevektor. Aus $T_2$ kannst du anschließend Gradient und Hesse-Matrix ablesen.`,R`Falls die Aufgabe zusätzlich eine direkte Ableitungskontrolle verlangt, berechne diese am ursprünglichen Funktionsterm. Das ist bei B.7.2(d) und B.7.3(d) ausdrücklich gefragt.`]},
 shift:{topic:'taylor',title:'Verschobener Entwicklungspunkt',page:23,recipe:[R`Setze bei $a=(a_1,a_2)$ die neuen Variablen $u=x-a_1$, $v=y-a_2$.`,R`Schreibe die ganze Funktion in $u,v$. Bei einem Logarithmus trenne die Konstante ab, z. B. $\ln(2+w)=\ln2+\ln(1+\frac w2)$.`,R`Setze Standardreihen ein und behalte nur den verlangten Gesamtgrad in $u,v$.`,R`Setze $u,v$ zurück und schreibe $f(x,y)=T_n(x,y)+R_n(x,y)$. Da $f\in C^{n+1}$ nahe $a$ ist, gilt dort $|R_n(x,y)|\le C\|(x,y)-a\|^{n+1}$ für eine feste Konstante $C>0$. Verwende den Abstand zum tatsächlichen Entwicklungspunkt.`]},
 hessian:{topic:'taylor',title:'Gradient, Hesse-Matrix und Rest',page:'21–22, 25–26',recipe:[R`Bestimme zuerst $T_2$ mit den passenden Standardreihen. Am Entwicklungspunkt $a$ verwende die Verschiebungen $h=x-a$ und schreibe $f(a+h)=c+\ell^Th+\frac12h^THh+R_2(a+h)$.`,R`Die linearen Koeffizienten ergeben den Gradienten bei $a$. Fehlt eine Variable im linearen Teil, ist ihr Eintrag 0.`,R`Verdopple die Koeffizienten von $h_i^2$ für die Diagonale. Der Koeffizient von $h_i h_j$ steht unverändert an beiden gemischten Stellen. Fehlende quadratische Terme ergeben Einträge 0.`,R`Kontrolliere durch zweite Ableitungen der ursprünglichen Funktion, wenn verlangt; B.7.2(d) und B.7.3(d) verlangen das ausdrücklich. Da $f\in C^3$ nahe $a$ ist, gilt $|R_2(a+h)|\le C\|h\|^3$ für kleine $h$ und eine feste Konstante $C>0$.`]}
};
