const R=String.raw;
export default {id:'ergaenzungen',title:'Ergänzungen',description:'Vollständigkeit, Fixpunkte und Funktionenfolgen.',priority:'Danach',source:'Lecture Notes · §1.1; Blatt 1–3',visual:'fixed',generator:'fixed',goals:['Cauchy-Folgen und Vollständigkeit definieren.','Banachs Fixpunktsatz mit allen Voraussetzungen formulieren.','Punktweise und gleichmäßige Konvergenz unterscheiden.','Grenzübergänge nur unter passenden Voraussetzungen vertauschen.'],theory:[
{id:'complete',kind:'Definition',title:'Cauchy-Folge, vollständiger Raum',text:R`Eine Folge $(x_n)$ in $(X,d)$ heißt Cauchy-Folge, wenn $\forall\varepsilon>0\ \exists N\ \forall m,n\ge N:d(x_m,x_n)<\varepsilon$. Der Raum heißt vollständig, wenn jede Cauchy-Folge in $X$ gegen einen Punkt von $X$ konvergiert. Ein vollständiger normierter Raum heißt Banachraum, ein vollständiger Skalarproduktraum Hilbertraum.`,source:'Lecture Notes · Definition 1.1; T.2.1, T.3.1(a)',checks:['Grenzwert im Raum.','Hilbertraum: Vollständigkeit bezüglich der induzierten Norm.']},
{id:'banach',kind:'Satz',title:'Banachscher Fixpunktsatz',text:R`Sei $(X,d)$ nichtleer und vollständig. Sei $\varphi:X\to X$ eine Kontraktion: Es existiert $q\in[0,1)$ mit $d(\varphi(x),\varphi(y))\le qd(x,y)$ für alle $x,y\in X$. Dann besitzt $\varphi$ genau einen Fixpunkt $x_*$. Für jeden Startwert $x_0\in X$ konvergiert $x_{n+1}=\varphi(x_n)$ gegen $x_*$. Zudem $$d(x_n,x_*)\le\frac{q^n}{1-q}d(x_1,x_0).$$`,source:'Lecture Notes · Satz 1.3; T.3.1(b)',checks:['Nichtleer und vollständig.','Selbstabbildung X → X.','Ein gemeinsames q < 1.']},
{id:'uniform-continuity',kind:'Definition',title:'Gleichmäßige Stetigkeit',text:R`$f:(X,d_X)\to(Y,d_Y)$ heißt gleichmäßig stetig, wenn $\forall\varepsilon>0\ \exists\delta>0\ \forall x,y\in X$: $d_X(x,y)<\delta\Rightarrow d_Y(f(x),f(y))<\varepsilon$. Das $\delta$ darf von $\varepsilon$, aber nicht vom Ort abhängen. Jede stetige Abbildung auf einem kompakten metrischen Raum ist gleichmäßig stetig.`,source:'Blatt 1 · B.1.2–B.1.5',checks:['Ein gemeinsames δ für alle Punkte.']},
{id:'convergence',kind:'Definition',title:'Punktweise und gleichmäßige Konvergenz',text:R`Für $f_n,f:D\to\mathbb R$ bedeutet punktweise Konvergenz: $\forall x\in D\ \forall\varepsilon>0\ \exists N\ \forall n\ge N:|f_n(x)-f(x)|<\varepsilon$. Gleichmäßige Konvergenz bedeutet: $\forall\varepsilon>0\ \exists N\ \forall n\ge N\ \forall x\in D:|f_n(x)-f(x)|<\varepsilon$. Äquivalent zur gleichmäßigen Konvergenz ist $\sup_{x\in D}|f_n(x)-f(x)|\to0$.`,source:'T.1.1; B.2.2(a)',checks:['Bei gleichmäßiger Konvergenz darf N nicht von x abhängen.']},
{id:'uniform-criteria',kind:'Satz',title:'Kriterien für gleichmäßige Konvergenz',text:R`Für $f_n,f:D\to\mathbb R$ sind äquivalent: (i) $f_n\to f$ gleichmäßig; (ii) Für jede Folge $(x_n)\subseteq D$ gilt $f_n(x_n)-f(x_n)\to0$; (iii) Es existiert eine Nullfolge $a_n\ge0$, sodass für alle hinreichend großen $n$ und alle $x\in D$ gilt $|f_n(x)-f(x)|\le a_n$. Das gleichmäßige Cauchy-Kriterium lautet: $\forall\varepsilon>0\ \exists N\ \forall m,n\ge N\ \forall x\in D:|f_n(x)-f_m(x)|<\varepsilon$. In $\mathbb R$ ist es äquivalent zur Existenz eines gleichmäßigen Grenzwerts.`,source:'T.1.2',checks:['Supremum über das gesamte Gebiet.','Cauchy-Kriterium benötigt vollständigen Zielraum.']},
{id:'integral-limit',kind:'Satz',title:'Integration und Grenzübergang',text:R`Sind $f_n:[a,b]\to\mathbb R$ Riemann-integrierbar und konvergieren gleichmäßig gegen $f$, so ist $f$ Riemann-integrierbar und $$\lim_{n\to\infty}\int_a^b f_n(x)\,dx=\int_a^b f(x)\,dx.$$`,source:'T.2.2(a)',checks:['Kompaktes Intervall.','Gleichmäßige Konvergenz.']},
{id:'derivative-limit',kind:'Satz',title:'Gliedweise Differentiation',text:R`Seien $f_n\in C^1([a,b])$, $a<b$. Konvergiere $(f_n(x_0))$ für ein $x_0\in[a,b]$ und konvergiere $f_n'$ gleichmäßig auf $[a,b]$ gegen $g$. Dann konvergiert $f_n$ gleichmäßig gegen ein $f\in C^1([a,b])$, und $f'=g$. An den Endpunkten werden einseitige Ableitungen verwendet.`,source:'T.2.2(b) · C¹-Fassung',checks:['Konvergenz an einem Ausgangspunkt.','Gleichmäßige Konvergenz der Ableitungen.']},
{id:'ascoli',kind:'Satz',title:'Arzelà–Ascoli',text:R`Sei $K\ne\varnothing$ ein kompakter metrischer Raum und $Y$ ein endlichdimensionaler normierter Raum. Ist $(f_n:K\to Y)$ gleichmäßig beschränkt und gleichgradig stetig, so besitzt sie eine gleichmäßig konvergente Teilfolge. Gleichgradig stetig heißt: Zu jedem $a\in K$, $\varepsilon>0$ gibt es $\delta>0$, sodass $d(x,a)<\delta\Rightarrow\|f_n(x)-f_n(a)\|<\varepsilon$ für alle $n$.`,source:'Blatt 3 · Satz unter B.3.2',checks:['Kompakter Definitionsraum.','Gemeinsame Schranke und gemeinsame Stetigkeitskontrolle.','Endlichdimensionaler Zielraum.']}
],exercises:[
{id:'fixed-ball',title:'Eine Kugel auf sich abbilden',source:'B.3.1',prompt:R`Sei $\varphi:X\to X$, $X\subseteq\mathbb R^n$, eine Kontraktion mit Faktor $q<1$. Sei $\overline B_r(a)\subseteq X$ und $\|\varphi(a)-a\|\le(1-q)r$. Zeige, dass $\varphi$ in dieser Kugel einen Fixpunkt hat.`,hint:'Die abgeschlossene Kugel ist vollständig. Prüfe die Selbstabbildung.',steps:[R`Für $x\in\overline B_r(a)$ gilt $\|\varphi(x)-a\|\le\|\varphi(x)-\varphi(a)\|+\|\varphi(a)-a\|\le qr+(1-q)r=r$.`,R`Die Einschränkung auf die nichtleere vollständige Kugel ist eine Kontraktion in sich. Banach liefert genau einen Fixpunkt in der Kugel.`]},
{id:'fixed-limit',title:'Fixpunkte im Grenzübergang',source:'B.3.2(a–d)',prompt:R`Sei $A\ne\varnothing$ kompakt in $\mathbb R^n$, $f_n:A\to A$ mit Lipschitz-Konstanten $L_n<1$ und $f_n\to f$ punktweise. Zeige die Existenz eines Fixpunkts von f.`,hint:'Gemeinsame Lipschitz-Schranke 1, Arzelà–Ascoli und kompakte Folge von Fixpunkten.',steps:[R`$A$ ist abgeschlossen in $\mathbb R^n$, also vollständig. Banach liefert je einen eindeutigen Fixpunkt $a_n$ von $f_n$.`,R`Die Abbildungen sind durch die Beschränktheit von $A$ gemeinsam beschränkt und wegen $L_n\le1$ gleichgradig stetig. Arzelà–Ascoli liefert eine gleichmäßig konvergente Teilfolge $f_{n_k}$. Ihr Grenzwert ist wegen punktweiser Eindeutigkeit $f$.`,R`Nach weiterer Teilfolgenwahl gilt $a_{n_k}\to a\in A$. Außerdem ist $f$ 1-Lipschitz, denn die Lipschitz-Ungleichung geht punktweise in den Grenzwert über.`,R`$$\|f(a)-a\|\le\|f(a)-f(a_{n_k})\|+\|f(a_{n_k})-f_{n_k}(a_{n_k})\|+\|a_{n_k}-a\|\to0.$$ Somit $f(a)=a$.`]},
{id:'uniform-example',title:'Gleichmäßige Konvergenz abschätzen',source:'B.1.3(a)',prompt:R`Untersuche $f_n(x)=\sin(nx)/n^2$ auf $\mathbb R$ auf punktweise und gleichmäßige Konvergenz.`,hint:'Eine von x unabhängige Schranke genügt.',steps:[R`$|f_n(x)|\le1/n^2$ für alle $x$. Also $f_n(x)\to0$ für jedes $x$.`,R`$\sup_{x\in\mathbb R}|f_n(x)|=1/n^2\to0$. Damit ist die Konvergenz gleichmäßig.`]},
{id:'limit-derivatives',title:'Ableitungen nicht blind vertauschen',source:'B.2.4(b)',prompt:R`Sei $f_n(x)=x/(1+n^2x^2)$. Bestimme die Grenzfunktion und vergleiche $\lim_n f_n'(0)$ mit $f'(0)$.`,hint:'Für jedes feste x den Grenzwert nehmen. Danach gesondert ableiten.',steps:[R`Für $x=0$ gilt $f_n(0)=0$, für $x\ne0$ gilt ebenfalls $f_n(x)\to0$. Also $f\equiv0$. Sogar $\sup_x|f_n(x)|=1/(2n)\to0$.`,R`$f_n'(x)=(1-n^2x^2)/(1+n^2x^2)^2$, also $f_n'(0)=1$. Aber $f'(0)=0$. Gleichmäßige Konvergenz der Funktionen allein rechtfertigt keine Vertauschung der Ableitung.`]},
{id:'uniform-integral',title:'Integration und Grenzübergang',source:'B.2.3(a)',prompt:R`Zeige für $f_n(x)=\sin(nx)/n$ auf $[-\pi,\pi]$, dass Grenzübergang und Integral vertauscht werden dürfen.`,hint:'Begründe die Voraussetzungen des Satzes, nicht nur die Integralwerte.',steps:[R`Alle $f_n$ sind stetig und damit Riemann-integrierbar. $\sup|f_n|\le1/n\to0$, also gleichmäßige Konvergenz gegen 0.`,R`Der Satz liefert $\lim_n\int_{-\pi}^{\pi}f_n=\int_{-\pi}^{\pi}0=0$. Direkt sind auch alle Integrale wegen Ungeradheit gleich 0.`]}
]};
