const R=String.raw;
export function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
export function parseNumber(value){const s=String(value).trim().replace(',','.');if(!s)return NaN;if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s))return Number(s);const m=s.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s*\/\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+))$/);return m&&Number(m[2])!==0?Number(m[1])/Number(m[2]):NaN}
export function generate(type,seed){const random=rng(seed),int=(a,b)=>Math.floor(random()*(b-a+1))+a,sign=()=>random()<.5?-1:1;let a=int(1,4),b=int(1,4),c=int(1,4);const base={type,seed,title:'Neue Variante',hint:'Rechne zunächst auf Papier. Trage dann deine Ergebnisse ein.'};
if(type==='compact'){const index=int(0,5);const sets=[{s:R`\{(x,y)\in\mathbb R^2:x^2+y^2\le ${a*a}\}`,v:1,why:R`Die Menge ist beschränkt durch Radius ${a}. Sie ist das Urbild des abgeschlossenen Intervalls $(-\infty,${a*a}]$ unter der stetigen Funktion $x^2+y^2$. Heine–Borel liefert Kompaktheit.`},{s:R`\{(x,y)\in\mathbb R^2:x^2+y^2<${a*a}\}`,v:0,why:R`Beschränkt, aber nicht abgeschlossen: $(${a}(1-1/n),0)$ konvergiert gegen $(${a},0)$ außerhalb der Menge.`},{s:R`[${-a},\infty)\subseteq\mathbb R`,v:0,why:'Die Menge ist abgeschlossen, aber unbeschränkt.'},{s:R`\{0\}\cup\{${a}/n:n\ge1\}\subseteq\mathbb R`,v:1,why:'Eine konvergente Folge zusammen mit ihrem Grenzwert bildet eine kompakte Menge. Jede offene Menge um 0 enthält alle bis auf endlich viele Punkte.'},{s:R`\{${a}/n:n\ge1\}\subseteq\mathbb R`,v:0,why:'Der Grenzwert 0 fehlt. Daher ist die Menge nicht abgeschlossen.'},{s:R`\{(x,y):xy=${a}\}\subseteq\mathbb R^2`,v:0,why:R`Als Nullstellenmenge einer stetigen Funktion abgeschlossen, aber unbeschränkt: $(n,${a}/n)$ liegt für jedes $n\ge1$ in der Menge.`}];const z=sets[index];return {...base,prompt:R`Ist $K=${z.s}$ kompakt? Begründe deine Entscheidung.`,fields:[{label:'Kompakt?',options:[{value:1,label:'Ja'},{value:0,label:'Nein'}],answer:z.v}],solution:z.why};}
if(type==='chain'){const A=[a,sign()*b,int(-3,3),c],u=int(-2,3),v=int(-2,3),k=int(1,4),l=int(1,4);const B=[1,k,l*v,l*u],answer=[B[0]*A[0]+B[1]*A[2],B[0]*A[1]+B[1]*A[3],B[2]*A[0]+B[3]*A[2],B[2]*A[1]+B[3]*A[3]];return{...base,prompt:R`$f:\mathbb R^2\to\mathbb R^2$ sei in $0$ differenzierbar, $f(0)=(${u},${v})$, $Df(0)=\begin{pmatrix}${A[0]}&${A[1]}\\${A[2]}&${A[3]}\end{pmatrix}$. Für $g(x,y)=(x+${k}y,${l}xy)$ bestimme $D(g\circ f)(0)$.`,fields:answer.map((x,i)=>({label:`Eintrag (${Math.floor(i/2)+1},${i%2+1})`,answer:x})),solution:R`$Dg(f(0))=\begin{pmatrix}1&${k}\\${l*v}&${l*u}\end{pmatrix}$. Rechts mit $Df(0)$ multiplizieren: $$D(g\circ f)(0)=\begin{pmatrix}${answer[0]}&${answer[1]}\\${answer[2]}&${answer[3]}\end{pmatrix}.$$`};}
if(type==='inverse'){b=sign()*b;c=sign()*c;let d=int(1,5);while(a*d-b*c===0)d++;const det=a*d-b*c,ans=[d/det,-b/det,-c/det,a/det];return{...base,prompt:R`$f:\mathbb R^2\to\mathbb R^2$ sei $C^1$ mit $f(p)=q$ und $Df(p)=\begin{pmatrix}${a}&${b}\\${c}&${d}\end{pmatrix}$. Begründe lokale Umkehrbarkeit und berechne $D(f^{-1})(q)$.`,fields:ans.map((x,i)=>({label:`Eintrag (${Math.floor(i/2)+1},${i%2+1})`,answer:x})),solution:R`$\det Df(p)=${det}\ne0$. Der Umkehrsatz ist anwendbar. $$D(f^{-1})(q)=\frac1{${det}}\begin{pmatrix}${d}&${-b}\\${-c}&${a}\end{pmatrix}.$$`};}
if(type==='implicit'){const x0=int(-2,2),y0=int(1,3);return{...base,prompt:R`$F(x,y)=${a}x^2+${b}y^2-${a*x0*x0+b*y0*y0}$. Zeige lokale Auflösbarkeit als $y=g(x)$ bei $(${x0},${y0})$ und berechne $g'(${x0})$.`,fields:[{label:R`g′(${x0})`,answer:-a*x0/(b*y0)}],solution:R`$F(${x0},${y0})=0$, $F_y(${x0},${y0})=${2*b*y0}\ne0$, $F\in C^1$. Also existiert die lokale Lösung und $$g'(${x0})=-\frac{F_x}{F_y}=-\frac{${2*a*x0}}{${2*b*y0}}.$$`};}
if(type==='taylor'){const ans=[1,a,b,a*a/2,a*b+c,b*b/2];return{...base,prompt:R`Bestimme das Taylorpolynom zweiter Ordnung bei 0 von $f(x,y)=e^{${a}x+${b}y}+${c}xy$. Trage die Koeffizienten in $T_2=c_0+c_xx+c_yy+c_{xx}x^2+c_{xy}xy+c_{yy}y^2$ ein.`,fields:ans.map((x,i)=>({label:['Konstante','x','y','x²','xy','y²'][i],answer:x})),solution:R`$e^t=1+t+t^2/2+O(t^3)$ mit $t=${a}x+${b}y$. Daher $$T_2=1+${a}x+${b}y+\frac{${a*a}}2x^2+${a*b+c}xy+\frac{${b*b}}2y^2.$$ Der Rest ist $O(\|(x,y)\|^3)$.`};}
if(type==='laplace'){const n=int(2,5);return{...base,prompt:R`Sei $u(x)=${a}s^2+${b}s$ auf $\mathbb R^{${n}}$, $s=\|x\|^2$. Schreibe $\Delta u=As+B$ und bestimme A und B.`,fields:[{label:'A',answer:4*a*(n+2)},{label:'B',answer:2*n*b}],solution:R`Für $\varphi(s)=${a}s^2+${b}s$ gilt $\varphi'=${2*a}s+${b}$, $\varphi''=${2*a}$. Mit $\Delta u=2n\varphi'+4s\varphi''$ folgt $A=${4*a*(n+2)}$, $B=${2*n*b}$.`};}
const q=int(1,4)/5,d=int(1,5);return{...base,prompt:R`Für $\varphi(x)=${q}x+${d}$ auf $\mathbb R$: Begründe die Voraussetzungen von Banach und berechne den Fixpunkt.`,fields:[{label:'Fixpunkt',answer:d/(1-q)}],solution:R`$\mathbb R$ ist nichtleer und vollständig; $\varphi$ ist eine Selbstabbildung mit Kontraktionsfaktor $${q}<1$. Aus $x=${q}x+${d}$ folgt $x_*=${d}/(1-${q})$.`};
}
