// Expanded numerical steps for the examples reused from the earlier training.
import {R} from './practice-shared.js';
export const workedSteps={
 'k-annulus':[[R`Setze $q(x,y)=x^2+y^2$ und $p(x,y)=x$. Beide Funktionen sind auf ganz $\mathbb R^2$ stetig.`,R`Die Bedingungen lauten $q(x,y)\in[1,4]$ und $p(x,y)\in[0,\infty)$. Also $$K=q^{-1}([1,4])\cap p^{-1}([0,\infty)).$$ Beide Wertebereiche sind abgeschlossen. Ihre Urbilder unter stetigen Funktionen und deren Schnitt sind abgeschlossen.`,R`Für jeden Punkt in $K$ gilt $$\|(x,y)\|=\sqrt{x^2+y^2}\le\sqrt4=2.$$ Somit ist $K$ beschränkt. Nach Heine–Borel ist $K$ kompakt.`]],
 'k-graph':[[R`Das Intervall $[1,2]$ ist abgeschlossen und beschränkt in $\mathbb R$, also kompakt.`,R`Definiere $\varphi:[1,2]\to\mathbb R^2$ durch $\varphi(t)=(t,1/t)$. Auf diesem Intervall wird der Nenner nie 0; beide Komponenten sind stetig.`,R`Jeder Punkt von $K$ und nur ein solcher entsteht durch diese Parametrisierung. Also $K=\varphi([1,2])$. Nach Satz 1.12 ist das stetige Bild der kompakten Ausgangsmenge kompakt.`]],
 'k-hyperbola':[[R`Wähle $z_n=(1/n,n)$, $n\ge1$. Die erste Koordinate liegt in $(0,1]$, und die zweite ist ihr Kehrwert. Somit $z_n\in M$.`,R`Es gilt $\|z_n\|=\sqrt{1/n^2+n^2}\ge n\to\infty$. Daher ist $M$ unbeschränkt und nicht kompakt.`,R`Für die Abgeschlossenheit schreibe $$M=\{(x,y):xy=1\}\cap\{x\ge0\}\cap\{x\le1\}.$$ Diese Beschreibung ist gleichwertig: Aus $xy=1$ folgt $x\ne0$, zusammen mit $x\ge0$ also $x>0$. Alle drei Bedingungen sind abgeschlossene Urbilder stetiger Funktionen. Ihr Schnitt ist abgeschlossen. Fehlende Kompaktheit bedeutet hier also nicht fehlende Abgeschlossenheit.`]],
 'k-sequence':[[R`Auf $M$ gilt $\|(1/n,1/n^2)\|\le\sqrt2$. Die Menge ist beschränkt. Aber $z_n=(1/n,1/n^2)\to(0,0)$, und dieser Punkt gehört wegen $1/n>0$ für jedes $n$ nicht zu $M$. Also ist $M$ nicht abgeschlossen und nicht kompakt.`,R`Betrachte jetzt $K=M\cup\{(0,0)\}$ und eine beliebige offene Überdeckung von $K$. Eine ihrer Mengen $U$ enthält $(0,0)$. Da $U$ offen ist und $z_n\to(0,0)$, liegen alle $z_n$ ab einem Index $N$ in $U$.`,R`Es fehlen höchstens die endlich vielen Punkte $z_1,\ldots,z_{N-1}$. Wähle für jeden davon eine Überdeckungsmenge. Zusammen mit $U$ ergeben diese endlich vielen Mengen eine endliche Teilüberdeckung. Damit ist $K$ kompakt.`]],
 'i-triangle':[
 [R`Das Gebiet $\mathbb R^2$ ist offen; beide Komponenten sind Polynome, also ist $f\in C^1$. Die Ableitungen nach $x$ stehen in Spalte 1, die nach $y$ in Spalte 2: $$Df(x,y)=\begin{pmatrix}1&2y\\0&1\end{pmatrix}.$$`,R`Die Determinante ist $1\cdot1-(2y)\cdot0=1\ne0$. Der Umkehrsatz liefert in jedem Punkt eine lokale $C^1$-Umkehrfunktion.`],
 [R`Schreibe $(u,v)=(x+y^2,y)$. Aus der zweiten Gleichung folgt $y=v$. In die erste eingesetzt: $u=x+v^2$, also $x=u-v^2$. Somit $$f^{-1}(u,v)=(u-v^2,v).$$ Für jeden Bildkandidaten $(u,v)\in\mathbb R^2$ existiert genau dieses Urbild. Das zeigt globale Bijektivität.`,R`Für $(u,v)=(3,1)$ erhältst du $y=1$ und $x=3-1=2$. Also ist das Urbild $(2,1)$.`,R`$$Df(2,1)=\begin{pmatrix}1&2\\0&1\end{pmatrix},\qquad D(f^{-1})(3,1)=\begin{pmatrix}1&-2\\0&1\end{pmatrix}.$$ Kontrolle: Das Produkt dieser beiden Matrizen ist $I_2$. Dasselbe Ergebnis folgt direkt durch Ableiten der expliziten Inversen.`]],
 'i-double':[
 [R`Das Gebiet $A$ ist offen; Exponentialfunktion, Sinus und Kosinus sind glatt. Beim Ableiten nach $y$ kommt jeweils der innere Faktor 2 dazu: $$Df(x,y)=\begin{pmatrix}e^x\cos(2y)&-2e^x\sin(2y)\\e^x\sin(2y)&2e^x\cos(2y)\end{pmatrix}.$$`,R`Die Determinante vereinfacht sich zu $$2e^{2x}\cos^2(2y)+2e^{2x}\sin^2(2y)=2e^{2x}>0.$$ Daher ist $f$ in jedem Punkt von $A$ lokal $C^1$-umkehrbar.`],
 [R`Setze $f(x,y)=f(x',y')$. Die Normen sind $e^x$ und $e^{x'}$. Aus ihrer Gleichheit folgt $x=x'$. Nach Kürzen dieses gemeinsamen positiven Faktors stimmen Sinus und Kosinus der Winkel $2y$ und $2y'$ überein.`,R`Beide Winkel liegen in $(0,2\pi)$. Ihre Differenz kann daher nur dann ein Vielfaches von $2\pi$ sein, wenn sie 0 ist. Also $2y=2y'$ und $y=y'$. Damit ist $f$ injektiv.`,R`Der Radius $e^x$ erreicht alle positiven Zahlen. Der Winkel $2y$ erreicht $(0,2\pi)$, aber nicht die positive horizontale Richtung. Folglich $$f(A)=\mathbb R^2\setminus\{(u,0):u\ge0\}.$$ Umgekehrt hat jeder Punkt dieser Menge einen Radius $r>0$ und Winkel $\theta\in(0,2\pi)$; $(\ln r,\theta/2)$ ist ein zulässiges Urbild.`],
 [R`Der Bildpunkt $(0,2)$ hat Norm 2 und Winkel $\pi/2$. Also $e^x=2$ und $2y=\pi/2$. Das gesuchte Urbild ist $(\ln2,\pi/4)$.`,R`Setze $e^x=2$, $\cos(2y)=0$, $\sin(2y)=1$ in $Df$ ein: $$Df(\ln2,\pi/4)=\begin{pmatrix}0&-4\\2&0\end{pmatrix},\qquad\det=8.$$`,R`Diagonale vertauschen, andere Vorzeichen wechseln, durch 8 teilen: $$D(f^{-1})(0,2)=\frac18\begin{pmatrix}0&4\\-2&0\end{pmatrix}=\begin{pmatrix}0&1/2\\-1/4&0\end{pmatrix}.$$ Der Auswertungspunkt von $Df$ ist das Urbild, nicht $(0,2)$.`]],
 'p-ellipse':[
 [R`Zuerst die Nullstelle: $F(1,2)=1+2+4-7=0$. Alle Terme sind Polynome, also ist $F$ auf einer offenen Umgebung $C^1$.`,R`Gesucht ist $y=g(x)$. Dafür prüfst du $F_y=x+2y$, also $F_y(1,2)=1+4=5\ne0$. Der implizite Funktionensatz liefert lokal eindeutig eine $C^1$-Lösung mit $g(1)=2$.`],
 [R`Es gilt $F_x=2x+y$ und $F_x(1,2)=2+2=4$. Differenzieren von $F(x,g(x))=0$ liefert $F_x+F_y g'=0$. Daher $$g'(1)=-\frac45.$$`,R`Für die andere Richtung ist die gesuchte Variable $x$. Der Nenner ist deshalb $F_x(1,2)=4\ne0$. Es existiert lokal eindeutig $x=h(y)$ mit $h(2)=1$. Aus $F_x h'+F_y=0$ folgt $$h'(2)=-\frac54.$$`]],
 'p-multifree':[
 [R`Einsetzen liefert $F_1(1,1,0,0)=1+1+0-2=0$ und $F_2(1,1,0,0)=1+2+0-3=0$. Die Funktionen sind Polynome, also glatt.`,R`Die gesuchten Variablen sind $(u,v)$. Ihre Ableitungen ergeben am Punkt $$A=\begin{pmatrix}2u&1\\1&2\end{pmatrix}_{u=1}=\begin{pmatrix}2&1\\1&2\end{pmatrix}.$$ Die Determinante ist $4-1=3\ne0$. Daher existiert lokal eindeutig $g(s,t)$ mit $g(0,0)=(1,1)$.`],
 [R`Nach den freien Variablen $(s,t)$ abgeleitet ist $B=I_2$. Damit lautet die Regel $A\,Dg=-I_2$.`,R`Für Spalte 1 löse $2a+b=-1$, $a+2b=0$. Verdopple die zweite Gleichung und ziehe die erste ab: $3b=1$, also $b=1/3$. Einsetzen in $a+2b=0$ ergibt $a=-2/3$.`,R`Für Spalte 2 löse $2c+d=0$, $c+2d=-1$. Verdopple wieder die zweite Gleichung und ziehe die erste ab: $3d=-2$, also $d=-2/3$. Aus $2c+d=0$ folgt $c=1/3$.`,R`Setze die Lösungen als Spalten ein: $$Dg(0,0)=\begin{pmatrix}-2/3&1/3\\1/3&-2/3\end{pmatrix}.$$ Zeilen gehören zu $(u,v)$, Spalten zu $(s,t)$. Zur Kontrolle liefert $A\,Dg$ die Matrix $-I_2$.`]],
 't-shift':[
 [R`Setze $u=x-1$, $v=y$ und $\rho=\sqrt{u^2+v^2}$. Die Funktion lautet jetzt $\ln(2+u+v^2)+e^{uv}$. Ihr Definitionsgebiet enthält eine offene Umgebung von $(u,v)=(0,0)$.`,R`Trenne die Konstante ab: $\ln(2+w)=\ln2+\ln(1+\frac w2)$. Mit $w=u+v^2$ entsteht $$\ln2+\frac{u+v^2}{2}-\frac{(u+v^2)^2}{8}+\ldots$$ Im Quadrat sind $2uv^2$ und $v^4$ schon von Grad 3 bzw. 4. Bis Grad 2 bleibt somit $\ln2+\frac u2+\frac{v^2}2-\frac{u^2}8$.`,R`Aus $e^{uv}$ bleiben $1+uv$, denn $(uv)^2$ hat Grad 4. Zusammen ergibt das $$T_2=1+\ln2+\frac u2-\frac{u^2}8+uv+\frac{v^2}2.$$ Für $f=T_2+R_2(x,y)$ gilt $R_2=O(\rho^3)$, weil $f$ nahe $(1,0)$ glatt ist.`],
 [R`Die linearen Koeffizienten sind $1/2$ und 0. Für die Hesse-Matrix verdopple die Koeffizienten von $u^2$ und $v^2$: $2(-1/8)=-1/4$ und $2(1/2)=1$. Der gemischte Koeffizient 1 kommt an beide anderen Stellen.`,R`$$\nabla f(1,0)=\binom{1/2}{0},\qquad H_f(1,0)=\begin{pmatrix}-1/4&1\\1&1\end{pmatrix}.$$ Mit $h=(x-1,y)^T$ lautet die Matrixform $$f(1+h_1,h_2)=1+\ln2+(1/2,0)h+\frac12h^TH_f(1,0)h+R_2(1+h_1,h_2),$$ wobei $R_2(1+h_1,h_2)=O(\|h\|^3)$.`]]
};
