// Englische Skripttitel sind von beschreibenden Lernüberschriften getrennt.
const script=(title,refs,recognize,originalName='',nameType='description',contrast='',aliases='')=>({title,scriptRefs:refs.split(' ').filter(Boolean),origin:'script',recognize,originalName,nameType,contrast,aliases});
const support=(title,origin,recognize,contrast='',aliases='')=>({title,origin,recognize,contrast,aliases,scriptRefs:[],originalName:'',nameType:'description'});
export const theoryNames={
 'compact-def':script('Offene Überdeckung und Überdeckungskompaktheit','1.4 1.5','Jede offene Überdeckung besitzt eine endliche Teilüberdeckung.','covering; open covering; (covering) compact','term','Das ist die Definition der Kompaktheit. Abgeschlossene Mengen mit endlicher Schnittbedingung gehören zu Cantor.','finite subcover finite subcovering Überdeckungsdefinition'),
 sequential:script('Folgenkompaktheit und ihre Äquivalenz zur Kompaktheit','1.5 1.9','Jede Folge besitzt eine konvergente Teilfolge mit Grenzwert in der Menge; in metrischen Räumen ist das äquivalent zur Kompaktheit.','sequentially compact','term','Der Grenzwert muss in A liegen. Satz 1.9 hat im Skript keinen eigenen Titel.','sequential compactness convergent subsequence Folgenkriterium'),
 'heine-borel':script('Satz von Heine–Borel','1.11','In endlichdimensionalen normierten Räumen: kompakt genau dann, wenn abgeschlossen und beschränkt.','Heine–Borel Theorem','title','Die Äquivalenz gilt nicht in jedem metrischen Raum.','Heine Borel closed bounded'),
 'compact-closed':script('Kompakte Mengen sind abgeschlossen und beschränkt','1.10','Jede kompakte Teilmenge eines metrischen Raumes ist abgeschlossen und beschränkt.','','description','Hier nur diese Richtung. Für die Umkehrung in endlichdimensionalen normierten Räumen: Heine–Borel.'),
 stability:script('Stabilitätseigenschaften der Kompaktheit','1.12','Abgeschlossene Teilmengen, endliche Vereinigungen, endliche Produkte und stetige Bilder erhalten Kompaktheit.','Stability Properties of Compactness','title','','continuous image finite union product'),
 cantor:script('Cantorscher Durchschnittssatz','1.6','Jede Familie abgeschlossener Mengen mit der endlichen Schnittbedingung relativ zu A hat auch insgesamt einen gemeinsamen Punkt in A; dies charakterisiert Kompaktheit.','Cantor intersection theorem','title','Die Skriptfassung behandelt beliebige Familien abgeschlossener Mengen. Sie ist nicht auf geschachtelte Folgen beschränkt.','finite intersection property endliche Durchschnittseigenschaft Schnittmengen'),
 'closed-bounded':support('Abgeschlossenheit und Beschränktheit','foundation','Grenzwerte bleiben in der Menge; alle Punkte liegen in einer ausreichend großen Kugel.'),
 metric:support('Metrik und metrischer Raum','foundation','Abstandsfunktion mit Definitheit, Symmetrie und Dreiecksungleichung.'),
 accumulation:script('Häufungspunkt einer Folge','1.7 1.8','Eine Teilfolge konvergiert gegen den Punkt; äquivalent liegen für jedes ε > 0 unendlich viele Folgenglieder in seiner ε-Kugel.','Accumulation point of a sequence; Equivalent characterization','title','Unendlich viele Indizes, nicht notwendig unendlich viele verschiedene Werte.','Häufungswert subsequence'),
 total:script('Differenzierbarkeit und totale Ableitung','2.1','Eine lineare Abbildung approximiert den Zuwachs mit einem Rest, der geteilt durch die Schrittlänge gegen null geht.','differentiable','term','Die Existenz einzelner partieller oder aller Richtungsableitungen genügt dafür nicht.','Fréchet Frechet derivative total differentiability linear approximation'),
 jacobi:script('Partielle Ableitungen und Jacobi-Matrix','2.8 2.9','Bei einer differenzierbaren Abbildung existieren die partiellen Ableitungen und bilden die Matrix der Ableitung.','partial derivative','term','Satz 2.9 hat keinen eigenen Titel. Partielle Ableitungen allein sichern keine totale Differenzierbarkeit.','Jacobian matrix'),
 c1:script('Stetige Differenzierbarkeit und Kriterium durch partielle Ableitungen','2.13 2.14','C¹ ist äquivalent zur Existenz und Stetigkeit aller partiellen Ableitungen.','continuously differentiable','term','Definition 2.13 definiert C¹ über die stetige Ableitung; Satz 2.14 liefert das Kriterium und hat keinen eigenen Titel.','continuous partial derivatives'),
 chain:script('Kettenregel','2.3','Die Ableitung einer Verkettung ist das Produkt der Ableitungen: äußere Ableitung am inneren Funktionswert, dann innere Ableitung.','Chain Rule','title','','composition'),
 mean:script('Mittelwertungleichung: beschränkte Ableitung ⇒ Lipschitz-Stetigkeit','2.11','Eine einheitliche Schranke der Ableitung auf einem offenen konvexen Gebiet liefert dieselbe Lipschitz-Konstante.','','description','Abschätzung für vektorwertige Funktionen; keine Gleichheit an einem gemeinsamen Zwischenpunkt.','mean value inequality Lipschitz bound'),
 'mean-scalar':script('Mittelwertsatz für reellwertige Funktionen','2.4','Der Funktionszuwachs ist die Ableitung an einem Zwischenpunkt der Strecke, angewendet auf den Zuwachsvektor.','Mean-Value Theorem','title','Reellwertige Funktion. Die „Mean value property“ aus Proposition 2.25 betrifft ein Rechteck und eine gemischte Ableitung.','scalar Mittelwerttheorem'),
 'mean-vector':script('Mittelwertabschätzung für vektorwertige Kurven','2.5','Der Abstand der Endwerte ist höchstens Intervalllänge mal Ableitungsnorm an einem inneren Punkt.','','description','Eine Ungleichung von Normen, keine vektorielle Mittelwertgleichheit.','vector mean value curve'),
 'zero-derivative':script('Verschwindende Ableitung ⇒ konstante Funktion','2.12','Ist die Ableitung auf dem offenen konvexen Gebiet überall null, so ist die Funktion konstant.','','description','','zero derivative constant'),
 'derivative-unique':script('Eindeutigkeit der Ableitung','2.2','Zwei lineare Abbildungen, die dieselbe Differenzierbarkeitsbedingung erfüllen, stimmen überein.','','description','','uniqueness derivative'),
 components:script('Komponenten und komponentenweise Differenzierbarkeit','2.6 2.7','Eine vektorwertige Abbildung ist genau dann differenzierbar, wenn alle Komponenten differenzierbar sind; ihre Ableitungen sind die Matrixzeilen.','components','term','Satz 2.7 hat keinen eigenen Titel.','component functions rows'),
 convex:script('Konvexe Menge','2.10','Mit je zwei Punkten enthält die Menge auch deren ganze Verbindungsstrecke.','convex','term','','line segment'),
 bijective:support('Injektivität, Surjektivität und Bijektivität','foundation','Höchstens ein Urbild, mindestens ein Urbild bzw. genau ein Urbild pro Zielpunkt.'),
 homeomorphism:support('Homöomorphismus','worksheet','Bijektive stetige Abbildung mit stetiger Umkehrabbildung.','Begriff aus der Anmerkung zu Blatt 4; keine nummerierte Definition der Lecture Notes.','homeomorphism'),
 diffeo:script('Lokaler und globaler Diffeomorphismus','2.18','C¹-Bijektion mit C¹-Umkehrabbildung; lokal gilt dies auf einer offenen Umgebung jedes betrachteten Punkts.','diffeomorphism; local diffeomorphism','term','Lokale Umkehrbarkeit liefert keine globale Injektivität.'),
 'inverse-theorem':script('Umkehrsatz / Satz über die inverse Funktion','2.17','Eine C¹-Abbildung mit invertierbarer Ableitung am Punkt hat zwischen geeigneten offenen Umgebungen eine C¹-Umkehrfunktion.','Inverse Function Theorem','title','Es wird die ganze Abbildung lokal umgekehrt. Beim impliziten Satz wird eine Gleichung nach einem Variablenblock aufgelöst.','inverser Funktionensatz inverse mapping theorem IFT'),
 'matrix-inverse':support('Inverse einer Matrix berechnen','foundation','Determinante, inverse Matrix und Auswertung am richtigen Urbild.'),
 'open-map':script('Offenheit einer überall lokal umkehrbaren Abbildung','2.19','Eine C¹-Abbildung mit überall invertierbarer Ableitung bildet offene Mengen auf offene Mengen ab.','','description','Die Ableitung muss an jedem Punkt invertierbar sein; globale Injektivität ist keine Folgerung.','open mapping offene Abbildung'),
 'invertible-operators':script('Offenheit der invertierbaren Operatoren und Stetigkeit der Inversion','2.15','Kleine Störungen eines invertierbaren linearen Operators bleiben invertierbar; die Menge dieser Operatoren ist offen und die Inversion stetig.','','description','Das ist ein Satz über lineare Operatoren. Die lokale Umkehrfunktion einer nichtlinearen Abbildung liefert Satz 2.17.','invertible linear operators continuity inversion'),
 'c1-invertible':script('C¹-Umkehrbarkeit','2.16','Offene Bildmenge und eine C¹-Umkehrabbildung mit beiden Kompositionsidentitäten.','C¹-invertible','term','','C1 invertible'),
 'implicit-theorem':script('Satz über implizite Funktionen','2.21','Eine C¹-Gleichung f(x,y) = 0 lässt sich nahe einer Nullstelle eindeutig nach x auflösen, wenn der x-Ableitungsblock invertierbar ist.','Implicit Function Theorem','title','Im Skript sind x die abhängigen und y die freien Variablen; der invertierbare Block gehört zu x.','impliziter Funktionensatz impliziter Satz'),
 'implicit-scalar':support('Implizites Ableiten im skalaren Fall','consequence','Ableitung einer lokal aufgelösten skalaren Gleichung als negativer Quotient partieller Ableitungen.','Spezialfall des Satzes über implizite Funktionen.'),
 'implicit-blocks':support('Implizites Ableiten mit Variablenblöcken','consequence','Abhängige Variablen wählen und das lineare System A · Dg = −B lösen.','Rechenschema zum impliziten Satz; kein eigener Skriptsatz.'),
 'implicit-linear':script('Auflösbarkeit einer linearen Gleichung nach einem Variablenblock','2.20','Ein invertierbarer x-Block macht die lineare Gleichung A(h,k) = 0 für jedes k eindeutig nach h lösbar.','','description','Linearer Vorläufer des impliziten Satzes, keine C¹-Umgebungsaussage.','linear implicit block'),
 ck:script('Höhere partielle Ableitungen und Cᵏ-Funktionen','','Iterierte partielle Ableitungen und die Klassen C², Cᵏ und C∞ werden über Existenz und Stetigkeit definiert.','Derivatives of higher order','title','Bei Dᵢⱼ wird zuerst nach j, dann nach i abgeleitet. Die Definition auf S. 44 ist unnummeriert.'),
 schwarz:script('Satz von Schwarz','2.26','Existieren D₁f, D₂₁f und D₂f im offenen Gebiet und ist D₂₁f am Punkt stetig, so existiert dort D₁₂f und beide stimmen überein.','Schwarz’s theorem','title','Die genaue Skriptfassung setzt nicht C² voraus. Das C²-Ergebnis ist das nachfolgende Korollar.','mixed partial derivatives Vertauschbarkeit gemischte Ableitungen'),
 'schwarz-corollary':script('Vertauschbarkeit gemischter Ableitungen für C²-Funktionen','2.27','Für eine C²-Funktion stimmen alle gemischten zweiten Ableitungen unabhängig von der Reihenfolge überein.','','description','Korollar zu Schwarz. Bei „Formuliere Schwarz“ die Voraussetzungen von Satz 2.26 lernen, nicht nur diese Kurzfassung.','Schwarz C2 corollary'),
 hessian:script('Hesse-Matrix','','Matrix aller zweiten partiellen Ableitungen; bei C² symmetrisch.','Hessian matrix','title','Die Matrix ist eine Definition. Ihre Verwendung zur Klassifikation kritischer Punkte ist eine zusätzliche Rechenhilfe.','Hessian Hesse'),
 divergence:script('Divergenz','','Skalarfeld: Summe der Ableitungen der j-ten Komponente nach der j-ten Variablen.','Divergence','title','','div'),
 laplace:script('Laplace-Operator','','Divergenz des Gradienten, also Summe der reinen zweiten partiellen Ableitungen.','Laplacian','title','Keine gemischten Ableitungen in der Summe.','Laplace operator delta'),
 orthogonal:support('Laplace-Operator unter orthogonalen Transformationen','consequence','Orthogonale Koordinatentransformationen erhalten den Laplace-Operator in der entsprechenden Verkettungsform.','Rechenregel zur Aufgabe 4(c) der Altklausur 2025; kein eigener Skriptsatz.','rotation invariant'),
 'field-products':script('Produktregeln für Gradient und Divergenz','2.23 2.24','Gradient eines Produkts zweier Skalarfelder und Divergenz eines mit einem Skalarfeld multiplizierten Vektorfelds.','','description','Lemma 2.23 liefert einen Vektor; Proposition 2.24 liefert einen Skalar.','product rules gradient divergence'),
 'vector-field':script('Skalarfeld und Vektorfeld','2.22','Ein Skalarfeld ordnet jedem Punkt eine Zahl zu, ein Vektorfeld einen Vektor des gleichen Raums.','scalar field; vector field','term'),
 'rectangle-mean':script('Mittelwerteigenschaft auf einem Rechteck','2.25','Die Differenz über vier Rechtecksecken geteilt durch h · k ist eine gemischte Ableitung an einem inneren Punkt.','Mean value property','title','Hilfssatz vor Schwarz. Nicht mit dem „Mean-Value Theorem“ für den Zuwachs entlang einer Strecke verwechseln.','rectangle Rechteck Mittelwerteigenschaft'),
 multiindex:script('Multiindex-Notation','','Gesamtordnung, Fakultät, Monom und partielle Ableitung eines Multiindex.','multi-index','term','','multiindex total degree'),
 'taylor-theorem':script('Satz von Taylor mit Restglied','2.29','Eine Cᵏ⁺¹-Funktion wird entlang einer im Gebiet liegenden Strecke durch ihr Taylorpolynom vom Grad k und einen Rest vom Grad k + 1 am gemeinsamen Zwischenpunkt dargestellt.','Taylor’s Theorem','title','Die vollständige Aussage enthält Regularität, Streckenbedingung und Restglied.','Taylor approximation expansion Entwicklung Taylor-Approximation'),
 'taylor-second':support('Taylorentwicklung zweiter Ordnung mit Hesse-Matrix','consequence','Linearer Gradiententerm, quadratischer Hesse-Term und Rest o(|ξ|²) bei C².','Spezialfall bzw. Folgerung aus Taylor; nicht die vollständige Formulierung von Satz 2.29.','Peano Restglied'),
 'known-series':support('Elementare Taylorentwicklungen zum Rechnen','foundation','Entwicklungen bekannter Funktionen passend zur verlangten Restordnung einsetzen.'),
 'segment-derivatives':script('Höhere Ableitungen entlang einer Strecke','2.28','Die k-te Ableitung von g(t) = f(x + tξ) ist die Multiindexsumme mit Faktoren k!/α!.','','description','Hilfslemma für Taylor; noch keine Entwicklung mit Restglied.','line segment higher derivative'),
 gradient:script('Gradient und Richtungsableitung','','Der Gradient sammelt die ersten partiellen Ableitungen; bei Differenzierbarkeit ist die Richtungsableitung sein Skalarprodukt mit der Richtung.','gradient; directional derivative','term','Eine Richtungsableitung kann ohne totale Differenzierbarkeit existieren.'),
 'gradient-theorem':script('Gradient: stärkster Anstieg und Orthogonalität zu Niveaumengen','2.30','Der Gradient liefert die Richtung des stärksten Anstiegs; er steht orthogonal auf Tangenten differenzierbarer Kurven in einer Niveaumenge.','','description','Der Satz enthält zusätzlich die Vorzeichenregel für kleine positive Schritte. Alle drei Teile gehören zur Aussage.','steepest ascent level set Niveaulinie Tangentialraum'),
 'local-extremum':script('Lokale Minimumstelle und Maximumstelle','2.31','In einer Umgebung sind alle zulässigen Funktionswerte mindestens bzw. höchstens so groß wie am betrachteten Punkt.','local minimum point; local maximum point','term'),
 'critical-definition':script('Notwendige Bedingung für innere Extremstellen; kritische Punkte und Werte','2.32 2.33','An einer differenzierbaren inneren Extremstelle verschwindet die Ableitung; ihre Nullstellen heißen kritische Punkte.','Necessary condition for interior extremal points','title','Nur notwendig: Ein kritischer Punkt muss kein Extremum sein. Definition 2.33 benennt kritische Punkte und ihre Werte.','critical points critical values Fermat'),
 extrema:support('Hesse-Kriterium zur Klassifikation kritischer Punkte','consequence','Eine definite Hesse-Matrix liefert ein striktes Extremum, eine indefinite keines; semidefinit entscheidet nicht.','Rechenhilfe aus Taylor. Im Skript steht kein eigener Satz mit diesem Namen.','Hessian criterion second derivative test'),
 'boundary-extrema':script('Notwendiges Kriterium für Extremstellen am implizit beschriebenen Rand','2.34','Sind Rand, Inneres und Äußeres durch g = 0, g < 0 und g > 0 beschrieben, sind die Gradienten von f und g an einem Randextremum linear abhängig.','Criterion for boundary extrema with implicitly defined boundary','title','Die Skriptfassung verlangt keine von null verschiedene Randgradienten-Norm. Erst bei ∇g ≠ 0 folgt die Darstellung ∇f = λ∇g.','Lagrange boundary extrema Randextrema'),
 complete:script('Cauchy-Folge, Vollständigkeit, Banachraum und Hilbertraum','1.1','Jede Cauchy-Folge konvergiert im Raum; vollständig und normiert heißt Banachraum, vollständig mit Skalarprodukt Hilbertraum.','Cauchy sequence; complete; Banach space; Hilbert space','term','Banachraum ist eine Definition. Der Banachsche Fixpunktsatz ist eine andere Aussage.'),
 contraction:script('Kontraktion','1.2','Eine Selbstabbildung verkürzt alle Abstände mit einem gemeinsamen Faktor kleiner als eins.','contraction','term','Ein gemeinsamer Faktor für alle Punktepaare; bloß punktweise kleinere Abstände genügen nicht.'),
 banach:script('Banachscher Fixpunktsatz','1.3','Eine Kontraktion auf einem nichtleeren vollständigen metrischen Raum besitzt genau einen Fixpunkt.','The Banach fixed point theorem','title','Nicht mit der Definition eines Banachraums verwechseln. Vollständigkeit und Selbstabbildung gehören zu den Voraussetzungen.','Banach Fixed Point Theorem contraction mapping'),
 'banach-iteration':support('Banach-Iteration und Fehlerabschätzung','consequence','Iteration der Kontraktion konvergiert zum eindeutigen Fixpunkt; der Fehler ist geometrisch beschränkt.','Folgerung aus dem Beweis von Banach, keine eigene nummerierte Satzformulierung.','Picard iteration error bound'),
 'uniform-continuity':support('Gleichmäßige Stetigkeit und Kompaktheit','worksheet','Ein δ gilt für alle Punkte; Stetigkeit auf einer kompakten Menge liefert gleichmäßige Stetigkeit.','Grundlage für Blatt 1. Das Kompaktheitsresultat heißt Heine–Cantor; es ist nicht der Cantorsche Durchschnittssatz der Lecture Notes.','uniform continuity Heine Cantor'),
 convergence:support('Punktweise und gleichmäßige Konvergenz','worksheet','Punktweise darf der Startindex vom Ort abhängen; bei gleichmäßiger Konvergenz gilt ein gemeinsamer Index.','','pointwise uniform convergence'),
 'uniform-criteria':support('Supremums- und Cauchy-Kriterium für gleichmäßige Konvergenz','worksheet','Der Supremumsfehler geht gegen null bzw. die Cauchy-Abschätzung gilt gleichzeitig an allen Punkten.','','uniform Cauchy criterion'),
 'uniform-limit':support('Stetigkeit des gleichmäßigen Grenzwerts','worksheet','Gleichmäßige Grenzwerte stetiger bzw. gleichmäßig stetiger Funktionen besitzen wieder diese Eigenschaft.','','uniform limit continuity'),
 ascoli:support('Satz von Arzelà–Ascoli in der Fassung von Blatt 3','worksheet','Auf kompaktem K liefern die Voraussetzungen aus Blatt 3 eine gleichmäßig konvergente Teilfolge.','Auf Blatt 3 als Hilfssatz angegeben; keine nummerierte Aussage der Lecture Notes.','Arzela Ascoli compact subsequence'),
 'integral-limit':support('Vertauschung von Integral und gleichmäßigem Grenzwert','worksheet','Bei gleichmäßiger Konvergenz auf einem kompakten Intervall darf unter den angegebenen Voraussetzungen Integration mit dem Grenzwert vertauscht werden.','','integration uniform limit'),
 'derivative-limit':support('Differentiation eines Funktionenlimes','worksheet','Gleichmäßige Konvergenz der Ableitungen und Konvergenz der Funktionswerte an einem Punkt erlauben die Ableitung des Grenzwerts.','Hier die C¹-Fassung für das Rechnen mit Blatt 2.','derivative limit differentiation'),
 weierstrass:support('Weierstraßscher Majorantentest','foundation','Eine summierbare, vom Ort unabhängige Majorante liefert gleichmäßige und absolute Konvergenz einer Funktionenreihe.','Benötigte Grundlage für B.2.4(a); kein eigener Satz der Lecture Notes.','Weierstrass M test')
};

export const originLabels={script:'Lecture Notes',worksheet:'Übungsblatt / Grundlage dazu',consequence:'Folgerung / Rechenhilfe',foundation:'Vorausgesetzte Rechengrundlage'};
export function namingLabel(t){
 if(t.originalName)return `${t.nameType==='title'?'Skripttitel':'Begriff im Skript'}: ${t.originalName}`;
 return t.origin==='script'?'Beschreibende Überschrift; im Skript ohne eigenen Titel.':`${originLabels[t.origin]}; keine eigene Satzformulierung der Lecture Notes.`;
}
const normalize=s=>String(s).toLowerCase().replaceAll('ß','ss').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
export function findTheorems(entries,{query='',module='all',scope='script'}={}){
 const words=normalize(query).split(' ').filter(Boolean);
 return entries.filter(t=>(scope==='all'||t.origin==='script')&&(module==='all'||t.module===module)).map((t,index)=>{
  const name=normalize(`${t.title} ${t.originalName}`),cue=normalize(t.recognize),rest=normalize(`${t.kind} ${t.aliases}`);
  const score=words.reduce((s,w)=>s+(name.includes(w)?5:cue.includes(w)?3:rest.includes(w)?1:0),0);
  return {t,index,score,matches:words.every(w=>`${name} ${cue} ${rest}`.includes(w))};
 }).filter(r=>r.matches).sort((a,b)=>b.score-a.score||a.index-b.index).map(r=>r.t);
}
