import {chart,fmt as baseFmt} from './plot-geometry.js';
const fmt=n=>n===0?'0':Math.abs(n)<.01?Number(n).toExponential(3):baseFmt(n);
const R=String.raw,orange='#b9602e',blue='var(--accent)';
const clean=x=>Math.abs(x)<1e-12?0:x;
const figure=(title,svg,caption='')=>({title,svg,caption});
const metric=(label,value)=>({label,value});
const graph=(fn,min,max,options={})=>chart([t=>{const x=min+(max-min)*t;return[x,fn(x)];}],{xMin:min,xMax:max,...options});

export function coverModel(p){
 const eps=+p.epsilon,n=+p.n,withZero=p.mode==='with-zero',needed=Math.floor((1+1e-12)/eps);
 const covered=withZero&&n>=needed,witness=withZero?1/(n+1):1/(n+2);
 const points=Array.from({length:40},(_,i)=>{const j=i+1,ok=withZero?(j<=n||1/j<eps-1e-12):1/j>1/(n+1)+1e-12;return[1/j,0,ok?blue:orange];});
 points.push([0,0,blue,!withZero]);if(!covered)points.push([witness,0,orange,false,6]);
 return {needed,covered,witness,figures:[figure('Welche Punkte sind bereits überdeckt?',chart([],{xMin:-.08,xMax:1.08,yMin:-.2,yMax:.2,points,segments:withZero?[[-eps,.09,eps,.09,blue]]:[[1/(n+1),.09,1.08,.09,blue]],labels:['x',''],title:'Folgenmenge und die gewählte endliche Überdeckung'}),'Blau: überdeckte Punkte bzw. Intervall. Orange: noch nicht überdeckt. Gezeigt sind nur ausgewählte Punkte der unendlichen Menge.')],metrics:[metric('Gewählte Mengen',withZero?`${n+1} (U₀ und ${n} weitere)`:`${n}`),metric('Gesamte Menge überdeckt?',covered?'Ja':'Nein')],text:withZero?R`$K=\{0\}\cup\{1/j:j\ge1\}$, $U_0=(-\varepsilon,\varepsilon)$ mit $\varepsilon=${fmt(eps)}$. Für jedes $j\ge1$ sei $V_j=(1/j-r_j,1/j+r_j)$ mit $r_j=1/(4j(j+1))$. Gewählt sind $U_0,V_1,\ldots,V_N$ mit $N=${n}$.`:R`$K=\{1/j:j\ge1\}$, $U_j=(1/(j+1),2)$. Die unendliche Familie überdeckt K. Für die gewählten $U_1,\ldots,U_N$ gilt jedoch $\bigcup_{j=1}^NU_j=U_N$ und $1/(N+2)=${fmt(witness)}\notin U_N$.`,explanation:withZero?R`$U_0$ enthält den ganzen unendlichen Rest mit $j>1/\varepsilon$. Es bleiben genau $\lfloor1/\varepsilon\rfloor=${needed}$ Punkte außerhalb von $U_0$; für jeden genügt ein $V_j$. ${covered?'Die endliche Auswahl deckt deshalb wirklich alle Punkte ab.':R`Noch fehlt zum Beispiel $1/(N+1)=${fmt(witness)}$. Erhöhe N auf ${needed}.`} Im allgemeinen Kompaktheitsbeweis kann eine beliebige offene Überdeckung verwendet werden: Eine ihrer Mengen enthält 0 und damit eine solche ε-Umgebung.`:'Auch jede anders gewählte endliche Teilfamilie hat einen größten Index N und lässt noch Punkte übrig. Das ist eine konkrete offene Überdeckung ohne endliche Teilüberdeckung. Bloß N immer größer zu wählen macht die Auswahl nicht zu einer endlichen Überdeckung.'};
}
export function differentialModel(p){
 const a=+p.angle*Math.PI/180,r=+p.radius,c=clean(Math.cos(a)),s=clean(Math.sin(a)),smooth=p.mode==='smooth';
 const value=smooth?r*r:c*s,ratio=Math.abs(value)/r;
 const fn=t=>smooth?t*t:c*s;
 return {value,ratio,figures:[figure('Zuwachs entlang deiner Richtung',graph(fn,.002,1,{yMin:-.6,yMax:1.1,points:[[r,value,orange]],labels:['r','f(rv)'],title:'Funktionswert auf dem Weg zum Ursprung'}))],metrics:[metric('f(h)',fmt(value)),metric('|f(h) − f(0) − Ah| / |h|',fmt(ratio))],text:smooth?R`$f(x,y)=x^2+y^2$, $A=0$, $h=r(\cos\varphi,\sin\varphi)$. Damit $$\frac{|f(h)-f(0)-Ah|}{|h|}=r.$$`:R`$f(x,y)=xy/(x^2+y^2)$ für $(x,y)\ne0$, $f(0,0)=0$. Beide partiellen Ableitungen in 0 sind null, also wäre die einzige mögliche Ableitung $A=0$. Für $h=rv$ gilt $$f(rv)=\cos\varphi\sin\varphi.$$`,explanation:smooth?'Der normierte Fehler geht für jede Richtung gleichzeitig gegen null, weil er nur r ist. Das ist genau die Approximationsbedingung der totalen Differenzierbarkeit.':R`Auf den Achsen ist der Fehler null. In der Richtung 45° bleibt $f(rv)=1/2$, selbst wenn $r\to0$. Die Funktion ist dort nicht einmal stetig. Zwei existierende partielle Ableitungen ersetzen deshalb nicht den Grenzwert über alle Zuwächse.`};
}
export function inverseModel(p){
 const a=+p.a,r=+p.radius,det=2*a,fold=r>Math.abs(a)+1e-12,lo=a-r,hi=a+r;
 const grid=[];for(let j=0;j<=6;j++){const x=lo+(hi-lo)*j/6,y=-.6+1.2*j/6;grid.push(t=>[x,-.6+1.2*t],t=>[lo+(hi-lo)*t,y]);}
 const mapped=grid.map(line=>t=>{const [x,y]=line(t);return[x*x,y];});
 return {det,fold,figures:[figure('Ausgangsmenge bei a',chart(grid,{xMin:-2,xMax:2,yMin:-1,yMax:1,points:[[a,0]],title:'Gitter vor der Abbildung'}),'a ist hier die erste Koordinate des Entwicklungspunkts (a,0).'),figure('Bild unter f(x,y) = (x²,y)',chart(mapped,{xMin:-.1,xMax:4,yMin:-1,yMax:1,points:[[a*a,0]],labels:['u','v'],title:'Gitter nach der quadratischen Abbildung'}),'Gitterlinien können aufeinanderfallen: x und −x haben dasselbe Bild.')],metrics:[metric('det Df(a,0)',fmt(det)),metric('Fenster enthält beide Vorzeichen',fold?'Ja':'Nein')],text:R`$$Df(a,0)=\begin{pmatrix}2a&0\\0&1\end{pmatrix},\qquad \det Df(a,0)=2a=${fmt(det)}.$$ Das gezeigte Fenster hat $a-r\le x\le a+r$ mit $r=${fmt(r)}$.`,explanation:det===0?'Bei a = 0 kollabiert die x-Richtung in der linearen Näherung. Hier ist f tatsächlich auf keiner Umgebung injektiv: (t,y) und (−t,y) haben dasselbe Bild. Allgemein bedeutet det = 0 zunächst nur, dass der Umkehrsatz nicht anwendbar ist.':fold?'Der Umkehrsatz gilt am Mittelpunkt, aber dein Fenster ist zu groß: Es enthält positive und negative x-Werte mit identischem Bild. Verkleinere r unter |a|. „Es existiert eine geeignete Umgebung“ bedeutet nicht „jede Umgebung funktioniert“.':R`Der Umkehrsatz gilt am Mittelpunkt. Auf der Seite $x>0$ ist die lokale Inverse $(\sqrt u,v)$, auf $x<0$ ist sie $(-\sqrt u,v)$. Die Ableitung der inversen x-Komponente am Bildpunkt ist $1/(2a)=${fmt(1/(2*a))}$. Nahe a = 0 wird sie groß.`};
}
export function implicitModel(p){
 const angle=+p.angle*Math.PI/180,at=t=>{const c=Math.cos(t),s=Math.sin(t);return[1/3+c/Math.sqrt(3)+s/3,1/3-c/Math.sqrt(3)+s/3,1/3-2*s/3].map(clean);};
 const point=at(angle),free=Number(p.free),dep=[0,1,2].filter(i=>i!==free),[i,j]=dep,names=['x','y','z'],det=clean(2*(point[i]-point[j]));
 const derivatives=det===0?null:[2*(point[j]-point[free])/det,2*(point[free]-point[i])/det];
 const proj=v=>[v[0]-.5*v[1],v[2]-.35*v[1]];
 return {point,free,dep,det,derivatives,figures:[figure('Gemeinsame Nullstellen: eine Raumkurve',chart([t=>proj(at(t*2*Math.PI))],{xMin:-1,xMax:1.4,yMin:-.8,yMax:1.3,points:[[...proj(point),orange]],labels:['',''],title:'Schrägbild der Schnittkurve von Kugel und Ebene'}),'Schrägbild, keine x-y-Ebene. Orange: der ausgewählte Punkt der Kurve.')],metrics:[metric('Punkt (x,y,z)',`(${point.map(fmt).join(', ')})`),metric(`Block nach (${names[i]},${names[j]})`,det===0?'Nicht invertierbar':`det = ${fmt(det)}`)],text:R`$$F(x,y,z)=\binom{x^2+y^2+z^2-1}{x+y+z-1}.$$ Am ausgewählten Punkt ist $F=0$. Die Variable $${names[free]}$ ist frei; $(${names[i]},${names[j]})=g(${names[free]})$ sind abhängig.
$$A=\begin{pmatrix}${fmt(2*point[i])}&${fmt(2*point[j])}\\1&1\end{pmatrix},\quad B=\binom{${fmt(2*point[free])}}1.$$`,explanation:derivatives?R`Der Block ist invertierbar. Der implizite Satz liefert eine eindeutige lokale C¹-Auflösung und $$g'=-A^{-1}B=\binom{${fmt(derivatives[0])}}{${fmt(derivatives[1])}}.$$ Kontrolliere $Ag'+B=0$. Es wird nur der Block nach den abhängigen Variablen invertiert, nicht die gesamte rechteckige Jacobi-Matrix.`:'Dieser Block ist singulär. Wähle eine andere freie Variable und kontrolliere den neuen Block. Am Punkt (1,0,0) eignet sich x nicht als freie Variable für diesen Satz; mit y oder z als freier Variable funktioniert die Auflösung.'};
}
export function schwarzModel(p){
 const h=10**(-Number(p.h)),k=10**(-Number(p.k)),smooth=p.mode==='smooth';
 const q=(u,v)=>smooth?1+u+v:(u*u-v*v)/(u*u+v*v),value=q(h,k);
 return {h,k,value,figures:[figure('Ein Schritt wird kleiner, der andere bleibt fest',graph(t=>q(10**(-t),k),0,5,{yMin:smooth?.9:-1.15,yMax:smooth?3.1:1.15,points:[[+p.h,value,orange]],labels:['s','Q'],title:'Gemischter Differenzenquotient für h gleich 10 hoch minus s'}),'Nach rechts wird h kleiner. k bleibt auf deinem eingestellten Wert.')],metrics:[metric('h',fmt(h)),metric('k',fmt(k)),metric('Q(h,k)',fmt(value))],text:R`$$Q(h,k)=\frac{f(h,k)-f(h,0)-f(0,k)+f(0,0)}{hk}.$$ ${smooth?R`Für $f(x,y)=xy+x^2y+xy^2$ ist $Q(h,k)=1+h+k$.`:R`Für $f(x,y)=xy(x^2-y^2)/(x^2+y^2)$ außerhalb von 0 und $f(0,0)=0$ ist $Q(h,k)=(h^2-k^2)/(h^2+k^2)$.`}`,explanation:smooth?R`Die Funktion ist glatt. Unabhängig von der Reihenfolge gilt $Q(h,k)\to1$. Somit $D_{21}f(0)=D_{12}f(0)=1$. Das passt zum C²-Korollar von Schwarz.`:R`Zuerst $h\to0$, dann $k\to0$ ergibt $D_{21}f(0)=-1$. In umgekehrter Reihenfolge ergibt sich $D_{12}f(0)=1$. Bei $h=k$ ist Q dagegen 0. Das ist kein Widerspruch zu Schwarz: Die nötige Stetigkeit einer gemischten Ableitung fehlt. Gleiche Schrittweiten allein entdecken diesen Fehler nicht.`};
}
export function taylorModel(p){
 const angle=+p.angle*Math.PI/180,r=+p.radius,k=+p.degree,c=clean(Math.cos(angle)),s=clean(Math.sin(angle));
 const exact=(x,y)=>Math.log1p(x+y*y)+Math.exp(x*y);
 const poly=(x,y)=>1+x+(k>=2?y*y-x*x/2+x*y:0)+(k>=3?-x*y*y+x*x*x/3:0);
 const error=t=>Math.abs(exact(t*c,t*s)-poly(t*c,t*s)),e=error(r),half=error(r/2),ratio=half>1e-13?e/half:null;
 const terms=[['1',0],['x',1],['y^2',2],['-x^2/2',2],['xy',2],['-xy^2',3],['x^3/3',3]];
 return {error:e,halfError:half,ratio,degree:k,terms,figures:[figure('Funktion und Taylorpolynom auf deiner Geraden',chart([t=>{const z=.9*t-.45;return[z,exact(z*c,z*s)];},t=>{const z=.9*t-.45;return[z,poly(z*c,z*s)];}],{xMin:-.45,xMax:.45,yMin:.25,yMax:1.7,points:[[r,exact(r*c,r*s),blue],[r,poly(r*c,r*s),orange]],labels:['r','Wert'],title:'Vergleich der Funktion aus Blatt 7 mit ihren Taylorpolynomen'}),'Blau: f(rv). Orange: Tₖ(rv). Das Gebiet 1 + x + y² > 0 ist im gezeigten Ausschnitt erfüllt.')],metrics:[metric('Fehler bei r',fmt(e)),metric('Fehler bei r/2',fmt(half)),metric('Fehlerverhältnis',ratio===null?'Numerisch zu klein':fmt(ratio))],text:R`$f(x,y)=\log(1+x+y^2)+e^{xy}$ am Entwicklungspunkt $(0,0)$. $v=(\cos\varphi,\sin\varphi)$, $(x,y)=rv$.
$$T_${k}=${k===1?'1+x':k===2?'1+x+y^2-x^2/2+xy':'1+x+y^2-x^2/2+xy-xy^2+x^3/3'}.$$`,explanation:R`Der Gesamtgrad von $x^ay^b$ ist $a+b$: $xy$ hat Grad 2, $xy^2$ bereits Grad 3. Bis Grad ${k} bleiben nur die entsprechend markierten Terme. Für kleine r nähert sich bei einem führenden Fehler der Ordnung $r^{${k+1}}$ das Fehlerverhältnis bei Halbierung von r dem Faktor $2^{${k+1}}=${2**(k+1)}$. Bei größeren Abständen muss das Verhältnis noch nicht nahe an diesem Wert liegen. In besonderen Richtungen kann der führende Term verschwinden; dann wird der Fehler noch schneller klein. Die Zeichnung einer Richtung ersetzt nicht den mehrdimensionalen Restnachweis.`};
}
export function gradientStepModel(p){
 const a=+p.angle*Math.PI/180,h=+p.h,c=clean(Math.cos(a)),s=clean(Math.sin(a)),derivative=2*c+4*s,q=c*c+2*s*s,change=h*derivative+h*h*q,end=[1+h*c,1+h*s];
 const contours=[1,3,7].map(level=>t=>[Math.sqrt(level)*Math.cos(t*2*Math.PI),Math.sqrt(level/2)*Math.sin(t*2*Math.PI)]);
 return {derivative,change,figures:[figure('Von a zum Punkt a + hv',chart(contours,{xMin:-3,xMax:3,yMin:-3,yMax:3,points:[[1,1,blue],[...end,orange]],segments:[[1,1,...end,orange]],title:'Schritt auf einer quadratischen Funktion zwischen Niveaulinien'}),'Blau: Startpunkt a = (1,1). Orange: Endpunkt. Die Ellipsen gehören zu f = 1, 3 und 7.')],metrics:[metric('Richtungsableitung Dᵥf(a)',fmt(derivative)),metric('Tatsächlicher Zuwachs',fmt(change))],text:R`$f(x,y)=x^2+2y^2$, $a=(1,1)$, $|v|=1$. Hier gilt exakt $$f(a+hv)-f(a)=hD_vf(a)+h^2(v_1^2+2v_2^2).$$`,explanation:derivative<0?R`Die Richtungsableitung ist negativ: Kleine positive Schritte senken f. Hier muss dafür $0<h<${fmt(-derivative/q)}$ gelten. ${change>0?'Dein Schritt ist so groß, dass der positive quadratische Term überwiegt.':'Dein gewählter Schritt senkt den Funktionswert oder ist null.'} Satz 2.30 garantiert das Vorzeichen nur für hinreichend kleine positive Schritte.`:derivative>0?'Die Richtungsableitung ist positiv. Für diese quadratische Funktion ist auch der quadratische Term positiv: Jeder positive Schritt erhöht den Wert. Die allgemeine Satzaussage ist trotzdem nur lokal.':'In dieser Tangentenrichtung ist die Richtungsableitung null. Der quadratische Term kann den Funktionswert dennoch erhöhen. Ableitung null bedeutet keine konstante Funktion auf der Geraden.'};
}
export function degenerateModel(p){
 const sign=p.mode==='minimum'?1:p.mode==='saddle'?-1:0,r=+p.radius,t=+p.t*r;
 return {sign,figures:[figure('Zwei Wege durch denselben kritischen Punkt',chart([u=>{const x=r*(2*u-1);return[x,sign*x**4];},u=>{const x=r*(2*u-1);return[x,x*x];}],{xMin:-r,xMax:r,yMin:-r*r*1.1,yMax:r*r*1.1,points:[[t,sign*t**4,blue],[t,t*t,orange]],labels:['t','f'],title:'Vergleich der Werte auf der x-Achse und der y-Achse'}),'Blau: (t,0). Orange: (0,t). Die vertikale Skala ändert sich mit dem Ausschnitt.')],metrics:[metric('Hesse-Matrix in 0','diag(0,2) – in allen drei Fällen'),metric('Wert auf der x-Achse',fmt(sign*t**4))],text:R`$$f(x,y)=y^2${sign===1?'+x^4':sign===-1?'-x^4':''},\qquad \nabla f(0)=0,\qquad H_f(0)=\begin{pmatrix}0&0\\0&2\end{pmatrix}.$$`,explanation:sign===1?'Hier ist f(x,y) > 0 für jeden Punkt ungleich 0: striktes Minimum. Der Term vierter Ordnung entscheidet in der Richtung, in der die Hesse-Matrix nichts erkennt.':sign===-1?'Auf der x-Achse sind die Werte negativ, auf der y-Achse positiv: kein Extremum. Dieselbe semidefinite Hesse-Matrix wie beim strikten Minimum führt also zu einem anderen Ergebnis.':'Hier ist f ≥ 0, aber f(x,0) = 0 auf der gesamten x-Achse: ein nichtstriktes Minimum. Eine semidefinite Hesse-Matrix erlaubt keine eindeutige Klassifikation.'};
}
export function iterationModel(p){
 const q=+p.q,n=+p.n,x0=+p.x0,xs=[x0];for(let j=0;j<n;j++)xs.push(q*xs.at(-1)+1);
 const target=Math.abs(q-1)<1e-12?null:1/(1-q),contract=Math.abs(q)<1-1e-12,error=target===null?null:Math.abs(xs.at(-1)-target),bound=contract?Math.abs(q)**n/(1-Math.abs(q))*Math.abs(xs[1]-xs[0]):null;
 const vals=target===null?xs:[...xs,target],lo=Math.min(0,...vals),hi=Math.max(1,...vals),pad=(hi-lo)*.15;
 return {xs,target,contract,error,bound,figures:[figure('Iteration mit deinem Startwert',chart(target===null?[]:[t=>[t*n,target]],{xMin:0,xMax:n,yMin:lo-pad,yMax:hi+pad,points:xs.map((x,i)=>[i,x,i===n?orange:blue]),labels:['n','xₙ'],title:'Konvergenz oder Divergenz einer affinen Fixpunktiteration'}),'Punkte: Iterationswerte. Horizontale Linie, falls vorhanden: Fixpunkt. Die Skala passt sich an.')],metrics:[metric('Kontraktionsfaktor |q|',fmt(Math.abs(q))),metric(`x${n}`,fmt(xs.at(-1))),metric('Abstand zum Fixpunkt',error===null?'Kein Fixpunkt':fmt(error))],text:R`$\varphi(x)=qx+1$ auf dem vollständigen Raum $\mathbb R$. $x_0=${fmt(x0)}$, $q=${fmt(q)}$. ${contract?R`Banach gilt. Die Fehlerschranke ist $$|x_n-x_*|\le\frac{|q|^n}{1-|q|}|x_1-x_0|=${fmt(bound)}.$$`:'Banachs Voraussetzung |q| < 1 ist nicht erfüllt.'}`,explanation:contract?(q<0?'Die Vorzeichen wechseln um den Fixpunkt, aber die Abstände schrumpfen. Eine Kontraktion muss nicht monoton iterieren.':'Die Abstände schrumpfen geometrisch. Je näher |q| an 1 liegt, desto mehr Schritte brauchst du. Vollständigkeit allein sagt nichts über die Geschwindigkeit.'):target===null?'Bei q = 1 ist φ(x) = x + 1. Es gibt keinen Fixpunkt, und die Iteration läuft weiter.':Math.abs(error)<1e-10?'Du hast zufällig den Fixpunkt als Startwert gewählt. Die konstante Folge beweist keine Kontraktion und keine Konvergenz für beliebige Startwerte.':Math.abs(q+1)<1e-12?'Bei q = −1 pendelt die Folge zwischen zwei Werten. Es existiert zwar ein Fixpunkt, aber die Iteration konvergiert im Allgemeinen nicht.':'Obwohl ein Fixpunkt existiert, wachsen die Abstände bei |q| > 1. Existenz eines Fixpunkts und Konvergenz der Iteration sind verschiedene Aussagen.'};
}
export function uniformModel(p){
 const eps=+p.epsilon,x=+p.x,factor=+p.factor,delta=eps*eps,y=x+factor*delta,gap=Math.sqrt(y)-Math.sqrt(x),inside=factor<1;
 return {delta,x,y,gap,inside,figures:[figure('Dasselbe δ an verschiedenen Stellen',graph(Math.sqrt,0,1.6,{xMin:0,xMax:1.6,yMin:0,yMax:1.4,points:[[x,Math.sqrt(x),blue],[y,Math.sqrt(y),orange]],segments:[[x,Math.sqrt(x),y,Math.sqrt(x),orange],[y,Math.sqrt(x),y,Math.sqrt(y),orange]],title:'Wurzelfunktion mit horizontalem und vertikalem Abstand'}),'Verschiebe x: δ bleibt gleich. Orange zeigt den Abstand der Eingaben und der Funktionswerte.')],metrics:[metric('Gemeinsames δ = ε²',fmt(delta)),metric('|x − y|',fmt(y-x)),metric('|√x − √y|',fmt(gap))],text:R`Für $x,y\ge0$ gilt $|\sqrt x-\sqrt y|\le\sqrt{|x-y|}$. Wähle zu $\varepsilon=${fmt(eps)}$ das vom Ort unabhängige $\delta=\varepsilon^2$.`,explanation:inside?R`Dein Punktepaar erfüllt $|x-y|<\delta$. Deshalb gilt $$|\sqrt x-\sqrt y|\le\sqrt{|x-y|}<\sqrt\delta=\varepsilon.$$ Genau das „ein δ für alle x,y“ macht die Stetigkeit gleichmäßig.`:'Dein Abstand ist mindestens δ. Die gewählte Abschätzung garantiert dann keine strenge ε-Schranke mehr. Trotzdem kann der tatsächliche Funktionsabstand kleiner als ε sein: Die δ-Bedingung ist hinreichend, nicht notwendig.'};
}
export function intervalModel(p){
 const a=+p.a,n=+p.n,eps=+p.epsilon,compactSubinterval=a<1,err=compactSubinterval?a**n:1,witness=2**(-1/n),N=compactSubinterval?Math.floor(Math.log(eps)/Math.log(a)+1e-12)+1:null;
 return {error:err,witness,N,figures:[figure('Wie groß bleibt der schlimmste Fehler?',chart([t=>[a*t,(a*t)**n]],{xMin:0,xMax:1.03,yMin:-.04,yMax:1.1,segments:[[0,0,a,0,orange]],points:compactSubinterval?[[a,a**n,blue]]:[[1,0,orange,true],[1,1,orange],[witness,.5,blue]],labels:['x','fₙ(x)'],title:'Potenzfolge auf einem veränderlichen Intervall'}),'Blau: fₙ. Orange: punktweiser Grenzwert. Bei a = 1 liegt der markierte Zeuge xₙ knapp links von 1.')],metrics:[metric('Intervall',`[0, ${fmt(a)}]`),metric('Supremumsfehler',fmt(err)),metric('Startindex für Fehler < ε',N===null?'Existiert hier nicht':`${N}`)],text:R`$f_n(x)=x^n$, $\varepsilon=${fmt(eps)}$. ${compactSubinterval?R`Auf $[0,a]$ mit $a<1$ gilt $f=0$ und $\|f_n-f\|_\infty=a^n$.`:R`Auf $[0,1]$ gilt $f(x)=0$ für $x<1$, aber $f(1)=1$. Der Supremumsfehler ist trotzdem 1; dieses Supremum wird nicht angenommen.`}`,explanation:compactSubinterval?R`Da $a=${fmt(a)}<1$ fest ist, wird $a^n$ kleiner als jedes positive ε. Ab $n=${N}$ gilt die Fehlerschranke gleichzeitig für jeden Punkt im Intervall. Je näher a an 1 liegt, desto später beginnt diese gemeinsame Schranke.`:R`Ein fester Punkt x < 1 kann täuschen. Wähle den mit n wandernden Punkt $x_n=2^{-1/n}=${fmt(witness)}$: Dort ist $f_n(x_n)=1/2$, aber $f(x_n)=0$. Deshalb ist die Konvergenz nicht gleichmäßig.`};
}
export function limitModel(p){
 const n=+p.n,power=+p.power,fn=x=>Math.sin(n*x)/n**power,dn=x=>Math.cos(n*x)/n**(power-1),error=1/n**power,derivativeError=1/n**(power-1);
 return {error,derivativeError,figures:[figure('Funktionen fₙ',graph(fn,-Math.PI,Math.PI,{yMin:-1.1,yMax:1.1,segments:[[-Math.PI,0,Math.PI,0,orange]],labels:['x','fₙ'],title:'Oszillierende Funktionen mit Grenzwert null'})),figure('Ableitungen fₙ′',graph(dn,-Math.PI,Math.PI,{yMin:-1.1,yMax:1.1,points:[[0,dn(0),blue]],segments:[[-Math.PI,0,Math.PI,0,orange]],labels:['x','fₙ′'],title:'Ableitungen einer gleichmäßig konvergierenden Funktionenfolge'}),'Beide vertikalen Skalen bleiben fest. Orange: Ableitung der Grenzfunktion, also 0.')],metrics:[metric('Supremumsnorm von fₙ',fmt(error)),metric('Supremumsnorm von fₙ′',fmt(derivativeError))],text:R`$$f_n(x)=\frac{\sin(nx)}{n^{${power}}},\qquad f_n'(x)=\frac{\cos(nx)}{n^{${power-1}}},\qquad x\in[-\pi,\pi].$$ Für beide Beispiele gilt $f_n\to0$ gleichmäßig und $f_n(0)=0$.`,explanation:power===2?R`Auch die Ableitungen konvergieren gleichmäßig gegen 0: $\|f_n'\|_\infty=1/n\to0$. Zusammen mit der Konvergenz an x = 0 erlaubt der Differentiationssatz den Grenzübergang. Die Integralvertauschung ist wegen gleichmäßiger Konvergenz der Funktionen ebenfalls zulässig.`:R`Die Funktionen konvergieren gleichmäßig, die Ableitungen aber nicht gegen $f'=0$: Schon $f_n'(0)=1$ bleibt bestehen. Für den Differentiationssatz fehlen die Voraussetzungen. Das Integral darfst du auf dem kompakten Intervall trotzdem mit dem Grenzwert vertauschen.`};
}
export const labModels={cover:coverModel,differential:differentialModel,fold:inverseModel,blocks:implicitModel,schwarz:schwarzModel,'taylor-error':taylorModel,'gradient-step':gradientStepModel,degenerate:degenerateModel,iteration:iterationModel,'uniform-delta':uniformModel,interval:intervalModel,'limit-conditions':limitModel};
