const range=(label,key,min,max,step,value)=>({label,key,min,max,step,value,type:'range'});
const choose=(label,key,options,value=options[0][0])=>({label,key,options,value,type:'select'});
const preset=(label,values,explain)=>({label,values,explain});
const quiz=(question,answers,correct,explain)=>({question,answers,correct,explain});

// Lernaufträge zu den bestehenden zwölf Veranschaulichungen.
export const originalLabs={
 compact:{title:'Menge, Folge und fehlender Grenzwert',benefit:'Du lernst, Nichtkompaktheit mit einer konkreten Folge zu begründen und „beschränkt“ von „kompakt“ zu unterscheiden.',presets:[preset('Mit Rand',{mode:'closed',n:6},'Der Randpunkt gehört zur Menge. Vergrößere n und beobachte den Grenzwert.'),preset('Ohne Rand',{mode:'open',n:50},'Dieselbe Folge läuft zu einem ausgeschlossenen Punkt. Genau das liefert das Gegenargument.'),preset('Grenzwert ergänzen',{mode:'sequence0',n:50},'Vergleiche die Folgenmenge mit und ohne 0 im Auswahlfeld.')],quiz:quiz('Eine beschränkte Menge enthält den Grenzwert einer Folge aus ihr nicht. Was folgt?',['Sie ist nicht kompakt.','Sie ist trotzdem kompakt.','Nur die Folge ist falsch gewählt.'],0,'Kompakte Mengen sind abgeschlossen. Eine Folge mit fehlendem Grenzwert im umgebenden Raum widerlegt daher Kompaktheit.'),theory:'heine-borel',exercise:'compact-disk'},
 derivative:{title:'Lineare Näherung und normierter Fehler',benefit:'Du siehst, warum nicht der Rest allein, sondern der durch die Schrittlänge geteilte Rest gegen null gehen muss.',presets:[preset('Großer Schritt',{a:.7,h:.8},'Vergleiche Funktionswert und Tangentenwert.'),preset('Kleiner Schritt',{a:.7,h:.1},'Der Fehler ist h²; relativ zur Schrittlänge bleibt |h|.'),preset('Anderer Punkt',{a:-1,h:.1},'Die Steigung ändert sich, die Restrechnung für x² bleibt gleich.')],quiz:quiz('Welche Bedingung ist entscheidend für die Ableitung A?',['Der Rest ist beschränkt.','Der Rest geteilt durch |h| geht gegen 0.','Eine partielle Ableitung existiert.'],1,'Definition 2.1 verlangt eine lineare Approximation mit Rest o(|h|), gleichzeitig für alle Zuwächse.'),theory:'total',exercise:'jacobi-warmup'},
 inverse:{title:'Lokal umkehrbar, global mehrdeutig',benefit:'Du trennst die lokale Aussage des Umkehrsatzes von der zusätzlichen globalen Injektivität.',presets:[preset('Erstes Urbild',{x:0,angle:.5},'Merke dir den Bildpunkt bei y = π/2.'),preset('Zweites Urbild',{x:0,angle:2.5},'y wurde um 2π erhöht. Das Bild bleibt gleich, die Determinante bleibt positiv.'),preset('Bild vergrößern',{x:.5,angle:.5},'x bestimmt den Radius eˣ; y bestimmt den Winkel.')],quiz:quiz('det Df ist überall ungleich null. Muss f global injektiv sein?',['Ja, das ist der Umkehrsatz.','Nein, der Umkehrsatz ist lokal.'],1,'Hier haben y und y + 2π dasselbe Bild. Lokale C¹-Umkehrfunktionen existieren trotzdem.'),theory:'inverse-theorem',exercise:'polar'},
 implicit:{title:'Kreis: ein lokaler Graph',benefit:'Du erkennst, welcher Ableitungsblock zur gewählten abhängigen Variablen gehört und wann du die Variable wechseln musst.',presets:[preset('Oben',{angle:.5},'Fᵧ ≠ 0: y lässt sich lokal als Funktion von x beschreiben.'),preset('Am rechten Rand',{angle:0},'Fᵧ = 0, aber Fₓ ≠ 0. Hier nach x statt nach y auflösen.'),preset('Fast am Rand',{angle:.025},'Der Graph ist noch lokal möglich, seine Steigung wird jedoch groß.')],quiz:quiz('Für y = g(x) muss welcher Block invertierbar sein?',['Die Ableitung nach x.','Die Ableitung nach y.','Die gesamte rechteckige Jacobi-Matrix.'],1,'Invertiert wird nach der abhängigen Variablen. In der allgemeinen Skriptnotation heißen die abhängigen Variablen x; die Rollen müssen zur konkreten Aufgabe passen.'),theory:'implicit-theorem',exercise:'implicit-simple'},
 higher:{title:'Hesse-Matrix, Richtungskrümmung und Laplace',benefit:'Du unterscheidest die Krümmung in einer einzelnen Richtung, die gesamte Hesse-Matrix und deren Spur.',presets:[preset('Minimum',{lambda:1,angle:.8},'Alle Richtungen sind nach oben gekrümmt.'),preset('Sattel, erste Richtung',{lambda:-1,angle:0},'Auf der x-Achse sieht der Sattel wie ein Minimum aus.'),preset('Sattel, andere Richtung',{lambda:-1,angle:1.55},'Nahe der y-Achse ist das Vorzeichen umgekehrt. Δf ist trotzdem 0.')],quiz:quiz('Kann Δf = 0 zusammen mit einer indefiniten Hesse-Matrix auftreten?',['Ja, etwa bei x² − y².','Nein, Δf = 0 bedeutet Hf = 0.'],0,'Die Spur 2 + (−2) ist null. Die Hesse-Matrix selbst ist nicht null; der Laplace-Operator erfasst nur ihre Spur.'),theory:'laplace',exercise:'laplace-proof'},
 taylor:{title:'Taylorpolynom entlang einer Richtung',benefit:'Du siehst den Einfluss von Grad, Abstand und Richtung, ohne die mehrdimensionale Formel aus dem Blick zu verlieren.',presets:[preset('Linear',{angle:0,degree:'1',t:.8},'Eine Tangentenapproximation ist nahe dem Entwicklungspunkt gut.'),preset('Quadratisch',{angle:0,degree:'2',t:.8},'Vergleiche den Fehler bei demselben Punkt mit Grad 1.'),preset('Näher am Punkt',{angle:0,degree:'2',t:.1},'Verkleinere den Abstand, während der Grad unverändert bleibt.')],quiz:quiz('Was gehört zur vollständigen Aussage des Taylor-Satzes?',['Nur das Polynom.','Polynom, Restglied und Voraussetzungen.'],1,'Zur Skriptfassung gehören Cᵏ⁺¹, die im Gebiet enthaltene Strecke und das gemeinsame θ im Restglied.'),theory:'taylor-theorem',exercise:'taylor-three'},
 gradient:{title:'Richtung des stärksten Anstiegs',benefit:'Du erkennst den Zusammenhang zwischen Einheitsrichtung, Skalarprodukt und Niveaulinie.',presets:[preset('In x-Richtung',{angle:0},'Hier wird nur die erste Komponente des Gradienten sichtbar.'),preset('Nahe am Maximum',{angle:.35},'Die Einheitsrichtung zeigt fast parallel zum Gradienten.'),preset('Fast tangential',{angle:.85},'Das Skalarprodukt liegt nahe null: fast keine Änderung erster Ordnung.')],quiz:quiz('Über welche Richtungen wird der stärkste Anstieg verglichen?',['Alle Vektoren beliebiger Länge.','Nur Einheitsvektoren.'],1,'Ohne feste Länge könnte man eine positive Richtungsableitung durch Skalieren beliebig vergrößern.'),theory:'gradient-theorem',exercise:'gradient-exercise'},
 extrema:{title:'Warum Geraden nicht immer genügen',benefit:'Du lernst, in einem semidefiniten Fall gekrümmte Wege zu prüfen, statt nach mehreren Geraden aufzuhören.',presets:[preset('Eine Gerade',{mode:'line',angle:.15,radius:.2},'Verkleinere den Ausschnitt: Auf dieser Geraden liegt ein lokales Minimum.'),preset('Andere Gerade',{mode:'line',angle:.6,radius:.2},'Auch andere feste Geraden liefern lokal kein Gegenbeispiel.'),preset('Gekrümmter Weg',{mode:'curve',angle:.15,radius:.2},'Jetzt werden die Werte für jedes t ≠ 0 negativ.')],quiz:quiz('Ein Minimum auf jeder Geraden durch 0 beweist ein lokales Minimum in R².',['Richtig.','Falsch.'],1,'Die nötige Umgebung kann von der Geraden abhängen. Der Weg y = 3x²/2 liefert in diesem Beispiel beliebig nahe negative Werte.'),theory:'extrema',exercise:'extrema-curves'},
 fixed:{title:'Banach: Konvergenzgeschwindigkeit',benefit:'Du verstehst, weshalb derselbe Fixpunktsatz bei verschiedenen Kontraktionsfaktoren unterschiedlich schnelle Iterationen liefert.',presets:[preset('Starke Kontraktion',{q:.2,n:5},'Wenige Schritte bringen dich sehr nahe an den Fixpunkt.'),preset('Schwache Kontraktion',{q:.85,n:5},'Fünf Schritte reichen hier deutlich weniger weit.'),preset('Mehr Schritte',{q:.85,n:20},'Der Fehler schrumpft weiter geometrisch.')],quiz:quiz('Welcher Faktor liefert bei vergleichbarem Anfangsfehler schnelleres Schrumpfen?',['q = 0,2.','q = 0,85.'],0,'Die geometrische Potenz qⁿ nimmt bei kleinerem q schneller ab.'),theory:'banach-iteration',exercise:'fixed-ball'},
 uniform:{title:'Gegenbeispiel zur gleichmäßigen Stetigkeit',benefit:'Du übst die Gegenbeweisstrategie: Eingaben rücken zusammen, ihre Funktionswerte nicht.',presets:[preset('Anfang',{n:3},'Vergleiche die beiden Abstände unter der Grafik.'),preset('Näher an 0',{n:15},'Die Eingaben werden näher, während die Werte weiter auseinanderliegen.'),preset('Noch näher',{n:30},'Ein gemeinsames δ für das ganze Gebiet kann so nicht funktionieren.')],quiz:quiz('Was muss ein Gegenbeispiel zur gleichmäßigen Stetigkeit zeigen?',['Nahe Eingaben mit nicht klein werdendem Werteabstand.','Nur einen großen Funktionswert.'],0,'Ein großer Wert allein widerlegt keine Stetigkeit. Entscheidend ist die fehlende gemeinsame Kontrolle der Funktionsabstände.'),theory:'uniform-continuity',exercise:'uniform-root'},
 convergence:{title:'Ein fester Punkt kann täuschen',benefit:'Du unterscheidest „für jedes feste x irgendwann klein“ von einer gemeinsamen Schranke für alle x.',presets:[preset('Fester Punkt',{n:5,x:.8},'Merke dir den Funktionswert bei x = 0,8.'),preset('n vergrößern',{n:50,x:.8},'An diesem Punkt ist der Wert nun sehr klein.'),preset('Nahe an 1',{n:50,x:.99},'An einem anderen Punkt ist der Fehler bei demselben n noch groß.')],quiz:quiz('Wenn fₙ(x) an jedem festen Punkt konvergiert, folgt gleichmäßige Konvergenz?',['Ja.','Nein.'],1,'Der benötigte Startindex darf bei punktweiser Konvergenz vom Punkt abhängen. Gleichmäßigkeit verlangt einen Index für das ganze Gebiet.'),theory:'convergence',exercise:'uniform-example'},
 limits:{title:'Grenzwert und Integral oder Ableitung',benefit:'Du erkennst an konkreten Gegenbeispielen, warum Grenzübergänge eigene Voraussetzungen brauchen.',presets:[preset('Dreiecksspitze',{mode:'integral',n:3},'Berechne Basis mal Höhe durch zwei.'),preset('Schmale Spitze',{mode:'integral',n:30},'Punktweise verschwindet die Spitze, ihre Fläche bleibt 1.'),preset('Ableitung vergleichen',{mode:'derivative',n:20},'Die Funktionen liegen nahe null, ihre Steigung im Ursprung bleibt 1.')],quiz:quiz('Gleichmäßige Konvergenz der Funktionen allein erlaubt immer den Grenzübergang bei Ableitungen.',['Richtig.','Falsch.'],1,'Der Differentiationssatz verlangt zusätzliche Kontrolle der Ableitungen. Das Beispiel hat fₙ′(0) = 1, aber f′(0) = 0.'),theory:'derivative-limit',exercise:'limit-derivatives'}
};

export const additionalLabs={
 compact:{id:'cover',title:'Eine endliche Teilüberdeckung bauen',source:'Experiment zu Definition 1.5 und dem Folgenmengen-Beispiel der Lecture Notes',benefit:'Du verstehst den entscheidenden Schritt der Überdeckungsdefinition: Eine Umgebung des Grenzwerts kann unendlich viele Punkte auf einmal abdecken.',controls:[choose('Grenzwert 0','mode',[['with-zero','0 gehört zur Menge'],['without-zero','0 fehlt in der Menge']]),range('Radius ε um 0','epsilon',.05,.5,.01,.2),range('Anzahl N weiterer Mengen','n',1,30,1,3)],presets:[preset('Es fehlt noch etwas',{mode:'with-zero',epsilon:.2,n:3},'Außerhalb der ε-Umgebung bleiben fünf Punkte. Drei Zusatzmengen reichen noch nicht.'),preset('Endlich reicht',{mode:'with-zero',epsilon:.2,n:5},'Fünf Zusatzmengen plus U₀ überdecken jetzt die ganze unendliche Menge.'),preset('Ohne Grenzwert',{mode:'without-zero',epsilon:.2,n:30},'Hier ändert sich die Überdeckungsfamilie: Auch die größte endliche Auswahl lässt einen Punkt frei.')],quiz:quiz('Warum genügt bei K = {0} ∪ {1/j} eine endliche Auswahl?',['Weil K endlich ist.','Weil eine offene Menge um 0 den ganzen Folgenschwanz enthält.','Weil jede Menge in der Überdeckung endlich ist.'],1,'K ist unendlich. Offenheit am enthaltenen Grenzwert deckt aber alle bis auf endlich viele Punkte auf einmal ab.'),theory:'compact-def',exercise:'compact-sequence'},
 derivative:{id:'differential',title:'Partielle Ableitungen reichen nicht',source:'Experiment zu Definition 2.1 und Theorem 2.9',benefit:'Du findest den Unterschied zwischen zwei Achsentests und dem Grenzwert über alle Zuwächse.',controls:[choose('Funktion','mode',[['smooth','x² + y²'],['counter','xy / (x² + y²), in 0 gleich 0']]),range('Richtung in Grad','angle',0,180,1,45),range('Abstand r vom Ursprung','radius',.01,1,.01,.5)],presets:[preset('Glatter Fall',{mode:'smooth',angle:45,radius:.05},'Der normierte Fehler ist klein und unabhängig von der Richtung.'),preset('Achse täuscht',{mode:'counter',angle:0,radius:.05},'Beide Achsen liefern den Wert 0. Das allein beweist nichts.'),preset('Diagonale entlarvt',{mode:'counter',angle:45,radius:.05},'Derselbe Abstand, aber ein Funktionswert von 1/2. Verkleinere jetzt r.')],quiz:quiz('Wenn alle partiellen Ableitungen null sind, ist die Funktion automatisch differenzierbar.',['Ja.','Nein.'],1,'Die partiellen Ableitungen bestimmen nur den möglichen Kandidaten A. Die Approximationsbedingung für alle Zuwächse muss zusätzlich gelten.'),theory:'total',exercise:'partial-counter'},
 inverse:{id:'fold',title:'Wie klein muss die Umgebung sein?',source:'Eigenes Beispiel zum Inverse Function Theorem, Theorem 2.17',benefit:'Du siehst, wie eine Abbildung ein Gitter faltet und warum eine lokale Umkehrfunktion eine passende Umgebung braucht.',controls:[range('Punktkoordinate a','a',-1,1,.05,.7),range('Halbe Fensterbreite r','radius',.05,1,.05,.3)],presets:[preset('Passende Umgebung',{a:.7,radius:.3},'Das Fenster bleibt auf einer Seite von x = 0.'),preset('Zu große Umgebung',{a:.3,radius:.8},'Die Determinante am Mittelpunkt ist noch ungleich null. Trotzdem faltet sich das große Fenster.'),preset('Singulärer Punkt',{a:0,radius:.3},'Jetzt scheitert schon die Voraussetzung am Mittelpunkt.')],quiz:quiz('Der Umkehrsatz gilt in a. Ist f auf jeder großen Umgebung von a injektiv?',['Ja.','Nein, nur auf geeigneten kleinen Umgebungen.'],1,'Der Satz behauptet die Existenz geeigneter offener U und V. Über beliebig große Umgebungen sagt er nichts aus.'),theory:'inverse-theorem',exercise:'local-criterion'},
 implicit:{id:'blocks',title:'Abhängige Variablen richtig wählen',source:'Eigenes Gleichungssystem zu Theorem 2.21',benefit:'Du übst das Kernproblem bei mehreren Gleichungen: zwei passende Jacobi-Spalten wählen und nur diesen Block invertieren.',controls:[range('Punkt auf der Kurve · Winkel in Grad','angle',0,360,1,30),choose('Freie Variable','free',[['0','x frei → (y,z) abhängig'],['1','y frei → (x,z) abhängig'],['2','z frei → (x,y) abhängig']])],presets:[preset('Ungeeigneter Block',{angle:30,free:'0'},'Bei (1,0,0) sind die y- und z-Spalten gleich.'),preset('Variable wechseln',{angle:30,free:'1'},'Derselbe Punkt, aber ein invertierbarer Block nach x und z.'),preset('Anderer Punkt',{angle:90,free:'0'},'Ein zuvor ungeeigneter Variablenblock kann an einem anderen Punkt funktionieren.')],quiz:quiz('Bei zwei Gleichungen und drei Variablen invertierst du …',['die gesamte 2×3-Jacobi-Matrix.','den 2×2-Block nach den abhängigen Variablen.'],1,'Die restliche Spalte gehört zur freien Variablen. Die Ableitung der Auflösung folgt aus A · g′ = −B.'),theory:'implicit-theorem',exercise:'implicit-system'},
 higher:{id:'schwarz',title:'Schwarz: die Reihenfolge der Grenzwerte',source:'Lecture Notes · Example 15 und Theorem 2.26; glattes Vergleichsbeispiel',benefit:'Du erkennst, warum die Stetigkeitsvoraussetzung wesentlich ist und warum zwei gleichzeitig kleine Schrittweiten keinen Beweis liefern.',controls:[choose('Funktion','mode',[['smooth','Glatter Vergleich'],['counter','Gegenbeispiel aus Example 15']]),range('h = 10⁻ˢ · Exponent s','h',0,5,.1,2),range('k = 10⁻ᵗ · Exponent t','k',0,5,.1,2)],presets:[preset('Gleiche Schritte',{mode:'counter',h:2,k:2},'Der Quotient ist 0. Das ist noch keine gemischte Ableitung.'),preset('Zuerst h klein',{mode:'counter',h:5,k:1},'Der Quotient liegt nahe −1.'),preset('Zuerst k klein',{mode:'counter',h:1,k:5},'Nun liegt er nahe +1. Vergleiche danach mit der glatten Funktion.')],quiz:quiz('Widerlegen D₂₁f(0) ≠ D₁₂f(0) automatisch den Satz von Schwarz?',['Ja.','Nein, zuerst seine Voraussetzungen prüfen.'],1,'Im Skriptgegenbeispiel fehlt die geforderte Stetigkeit. Bloße Existenz beider Ableitungen reicht nicht.'),theory:'schwarz',exercise:'schwarz-counter'},
 taylor:{id:'taylor-error',title:'Gesamtgrad und tatsächlicher Fehler',source:'B.7.2 · Entwicklung bei 0; zusätzlicher Vergleich bis Grad 3',benefit:'Du verbindest das Weglassen zu hoher Gesamtgrade mit dem Fehler, den du dabei tatsächlich machst.',controls:[choose('Taylorgrad','degree',[['1','Grad 1'],['2','Grad 2'],['3','Grad 3']],'2'),range('Richtung in Grad','angle',0,360,1,35),range('Abstand r','radius',.01,.45,.01,.3)],presets:[preset('Linearer Vergleich',{degree:'1',angle:35,radius:.3},'Betrachte den Fehler bei r und r/2.'),preset('Quadratischer Vergleich',{degree:'2',angle:35,radius:.3},'Jetzt kommen x², xy und y² hinzu; xy² bleibt noch draußen.'),preset('Abstand verkürzen',{degree:'2',angle:35,radius:.03},'Das Fehlerverhältnis nähert sich bei kleineren Abständen dem erwarteten Faktor 8.'),preset('Besondere Richtung',{degree:'2',angle:90,radius:.3},'Auf der y-Achse verschwindet der kubische Fehler. Die Konvergenz kann schneller sein als die allgemeine Restordnung.')],quiz:quiz('Gehört xy² zum Taylorpolynom zweiten Grades?',['Ja, denn keine einzelne Potenz übersteigt 2.','Nein, der Gesamtgrad ist 3.'],1,'Beim mehrdimensionalen Taylorpolynom zählt die Summe der Exponenten, nicht der größte einzelne Exponent.'),theory:'taylor-theorem',exercise:'taylor-log-exp'},
 gradient:{id:'gradient-step',title:'Kleine Schritte und zu große Schritte',source:'Eigenes Beispiel zu den drei Aussagen von Theorem 2.30',benefit:'Du verstehst, warum eine negative Richtungsableitung nur für kleine positive Schritte ein Absinken garantiert.',controls:[range('Einheitsrichtung in Grad','angle',0,360,1,243),range('Schrittlänge h','h',0,3,.05,.25)],presets:[preset('Kleiner Abstiegsschritt',{angle:243,h:.25},'Der Funktionswert nimmt ab.'),preset('Zu großer Schritt',{angle:243,h:3},'Die Richtung ist gleich geblieben, aber du bist über das günstige Gebiet hinausgegangen.'),preset('Anstiegsrichtung',{angle:63,h:.25},'Kehre die Richtung um und vergleiche das Vorzeichen.')],quiz:quiz('Dᵥf(a) < 0 garantiert f(a + hv) < f(a) …',['für jedes h > 0.','für alle hinreichend kleinen h > 0.'],1,'Das ist die lokale Vorzeichenregel von Theorem 2.30. Höhere Terme können bei großen Schritten überwiegen.'),theory:'gradient-theorem',exercise:'gradient-level'},
 extrema:{id:'degenerate',title:'Gleiche Hesse-Matrix, anderes Ergebnis',source:'Vergleichsbeispiele zur Taylorentwicklung und zur Rechenhilfe Hesse-Kriterium',benefit:'Du merkst dir nicht nur „semidefinit entscheidet nicht“, sondern siehst drei verschiedene Gründe dafür.',controls:[choose('Funktion','mode',[['minimum','y² + x⁴'],['saddle','y² − x⁴'],['flat','y²']]),range('Ausschnitt |t| ≤ r','radius',.1,1,.05,.7),range('Markierter Punkt t / r','t',-1,1,.05,.7)],presets:[preset('Striktes Minimum',{mode:'minimum',radius:.7,t:.7},'Alle Punkte außer 0 haben einen positiven Wert.'),preset('Kein Extremum',{mode:'saddle',radius:.7,t:.7},'Nun hat die x-Achse negative Werte, obwohl die Hesse-Matrix gleich bleibt.'),preset('Nichtstriktes Minimum',{mode:'flat',radius:.7,t:.7},'Eine ganze Gerade hat denselben Wert wie der Ursprung.')],quiz:quiz('Eine positiv semidefinite Hesse-Matrix an einem kritischen Punkt …',['beweist ein Minimum.','lässt die Klassifikation offen.'],1,'Alle drei gezeigten Funktionen haben Hf(0) = diag(0,2), aber unterschiedliche Extremstellen-Eigenschaften.'),theory:'extrema',exercise:'extrema-curves'},
 fixed:{id:'iteration',title:'Kontraktion, Pendeln und Abstoßen',source:'Eigenes Beispiel und Fehlerabschätzung zu Banachs Fixpunktsatz',benefit:'Du unterscheidest Existenz des Fixpunkts, Kontraktion und tatsächliche Konvergenz einer Iteration.',controls:[range('Steigung q','q',-1.2,1.2,.05,-.8),range('Startwert x₀','x0',-2,2,.1,0),range('Schritte n','n',1,20,1,10)],presets:[preset('Wechselnd, aber konvergent',{q:-.8,x0:0,n:10},'Das Vorzeichen des Fehlers wechselt; sein Betrag schrumpft.'),preset('Grenzfall |q| = 1',{q:-1,x0:0,n:10},'Zwei Werte wiederholen sich. „Nicht größer als 1“ reicht nicht.'),preset('Fixpunkt stößt ab',{q:1.1,x0:0,n:10},'Ein Fixpunkt existiert, doch dieser Startwert entfernt sich davon.')],quiz:quiz('Eine Kontraktion darf einen negativen linearen Faktor q haben.',['Ja, entscheidend ist |q| < 1.','Nein, q muss positiv sein.'],0,'Der Kontraktionsfaktor für φ(x) = qx + 1 ist |q|. Ein negatives q führt zu wechselnden Fehlerzeichen.'),theory:'banach',exercise:'fixed-ball'},
 uniform:{id:'uniform-delta',title:'Ein δ für alle Punkte',source:'Wurzelabschätzung aus dem Grundlagenstoff zu Blatt 1',benefit:'Du siehst die Quantoren der gleichmäßigen Stetigkeit: erst ε wählen, dann ein δ festlegen, das beim Verschieben der Punkte gleich bleibt.',controls:[range('Gewünschter Werteabstand ε','epsilon',.05,.5,.01,.3),range('Erster Punkt x','x',0,1,.01,0),range('Eingabeabstand als Vielfaches von δ','factor',.1,2,.1,.5)],presets:[preset('Nahe am Ursprung',{epsilon:.3,x:0,factor:.5},'Die δ-Bedingung garantiert den gewünschten Werteabstand.'),preset('Anderer Ort, gleiches δ',{epsilon:.3,x:.8,factor:.5},'δ bleibt unverändert. Der tatsächliche Werteabstand wird sogar kleiner.'),preset('Außerhalb der Garantie',{epsilon:.3,x:0,factor:1.5},'Die Voraussetzung |x − y| < δ ist nicht mehr erfüllt.')],quiz:quiz('Darf δ bei gleichmäßiger Stetigkeit vom gewählten Punkt x abhängen?',['Ja.','Nein, nur von ε.'],1,'Das gleiche δ muss die Aussage für alle zulässigen Punktepaare sichern.'),theory:'uniform-continuity',exercise:'uniform-root'},
 convergence:{id:'interval',title:'Das Intervall entscheidet',source:'Experiment zu Funktionenfolgen und dem Supremumskriterium',benefit:'Du kontrollierst den größten Fehler auf dem ganzen Gebiet und erkennst, warum ein kleinerer Definitionsbereich die Antwort ändern kann.',controls:[range('Rechter Intervallrand a','a',.5,1,.01,.9),range('Folgenindex n','n',1,500,1,10),range('Fehlertoleranz ε','epsilon',.05,.5,.01,.1)],presets:[preset('Abstand vom Rand',{a:.9,n:10,epsilon:.1},'Hier ist der Supremumsfehler aⁿ und geht gegen 0.'),preset('Knapp vor dem Rand',{a:.99,n:10,epsilon:.1},'Gleichmäßige Konvergenz gilt weiter, aber der Startindex wird viel größer.'),preset('Rand eingeschlossen',{a:1,n:100,epsilon:.1},'Nun tritt der Sonderpunkt x = 1 hinzu. Der Fehler bleibt irgendwo groß.')],quiz:quiz('Auf jedem festen [0,a] mit a < 1 konvergiert xⁿ gleichmäßig gegen 0.',['Richtig.','Falsch.'],0,'Der Supremumsfehler ist aⁿ. Dass der erforderliche Index von a abhängt, ist kein Problem: a gehört hier zum festgelegten Gebiet.'),theory:'uniform-criteria',exercise:'uniform-example'},
 limits:{id:'limit-conditions',title:'Funktionen und Ableitungen getrennt vergleichen',source:'Vergleichsbeispiele zu T.2.2: Integral- und Differentiationssatz',benefit:'Du siehst, welche zusätzliche Bedingung der Differentiationssatz verlangt und warum Integration und Ableitung unterschiedlich reagieren.',controls:[choose('Amplitude','power',[['1','sin(nx) / n'],['2','sin(nx) / n²']]),range('Folgenindex n','n',1,40,1,8)],presets:[preset('Funktionen klein, Steigungen nicht',{power:'1',n:20},'Oben schrumpft die Kurve, unten bleibt die Amplitude 1.'),preset('Beides schrumpft',{power:'2',n:20},'Jetzt konvergieren auch die Ableitungen gleichmäßig gegen 0.'),preset('Früher Folgenterm',{power:'2',n:2},'Vergleiche die beiden festen vertikalen Skalen und erhöhe dann n.')],quiz:quiz('Welche zusätzliche Information trägt das positive Beispiel?',['Die Ableitungen konvergieren gleichmäßig und fₙ(0) konvergiert.','Nur fₙ konvergiert gleichmäßig.'],0,'Im positiven Beispiel sind beide Voraussetzungen des Differentiationssatzes sichtbar: gemeinsame Ableitungsschranke und ein konvergenter Funktionswert.'),theory:'derivative-limit',exercise:'limit-derivatives'}
};
export function experimentsFor(type){
 const original=originalLabs[type],extra=additionalLabs[type];
 if(!original||!extra)throw Error('Experiment fehlt: '+type);
 return [{id:'overview',legacy:true,source:'Veranschaulichung zum zugeordneten Theorie- und Übungsstoff',...original,explanation:originalExplanations[type]},extra];
}
const R=String.raw;
export const originalExplanations={
 compact:'In R² bzw. R darfst du Heine–Borel verwenden. Beschränktheit ist bei diesen Beispielen sofort gegeben. Die entscheidende Frage ist, ob alle Grenzwerte enthalten bleiben. Eine einzige Folge mit fehlendem Grenzwert genügt gegen Abgeschlossenheit; ein einzelnes positives Beispiel beweist dagegen noch keine Abgeschlossenheit.',
 derivative:R`Die Tangente erfasst den linearen Anteil $2ah$. Der übrige Term ist exakt $h^2$. Beim Teilen durch $|h|$ bleibt $|h|$, also ein Ausdruck, der gegen null geht. Dass allein der Rest gegen null geht, wäre zu schwach: Auch ein Fehler proportional zu |h| verschwindet, ist aber nicht klein genug für die Ableitung.`,
 inverse:R`Die Determinante $e^{2x}$ ist an jedem Punkt positiv. Der Umkehrsatz liefert daher überall eine lokale C¹-Inverse. Der Winkel ist aber 2π-periodisch. Beschränkst du ihn auf $0<y<2\pi$, verschwindet diese Mehrdeutigkeit; die positive reelle Halbgerade bleibt dann aus dem Bild ausgeschlossen.`,
 implicit:R`Beim Ableiten von $x^2+g(x)^2=1$ erhältst du $2x+2g(x)g'(x)=0$. Durch $2g(x)$ darfst du genau dort teilen, wo $F_y=2y\ne0$. Am rechten und linken Kreispunkt musst du die Rollen tauschen: $x=h(y)$ hat dort eine lokale C¹-Darstellung.`,
 higher:R`Die Richtungskrümmung ist $v^\top H_fv=2(\cos^2\varphi+\lambda\sin^2\varphi)$. Bei λ < 0 kommen beide Vorzeichen vor, auch wenn ein einzelner Schnitt positiv gekrümmt aussieht. Der Laplace-Operator ist nur die Summe der Diagonaleinträge, hier $2+2\lambda$; er klassifiziert kritische Punkte nicht allein.`,
 taylor:R`Auf der gewählten Geraden wird $x+y=t(\cos\varphi+\sin\varphi)=ct$. Die mehrdimensionale Entwicklung wird damit zu $e^{ct}=\sum_{j=0}^k (ct)^j/j!+R_k$. Ein höherer Grad berücksichtigt weitere Ableitungsinformationen; ein kleinerer Abstand verkleinert den Rest. In Richtungen mit c = 0 ist die Funktion auf dieser Geraden konstant.`,
 gradient:R`Für einen Einheitsvektor v gilt $D_vf=\nabla f\cdot v=|\nabla f|\cos\theta$, wobei θ der Winkel zwischen Gradient und v ist. Parallel ergibt das Maximum, entgegengesetzt das Minimum, senkrecht den Wert 0. Tangenten an die Niveaulinie sind zum Gradienten orthogonal.`,
 extrema:R`Auf einer festen Geraden $t(a,b)$ dominiert für b ≠ 0 nahe 0 der positive Term $b^2t^2$. Bei b = 0 bleibt $2a^4t^4>0$. Auf dem gekrümmten Weg $y=3x^2/2$ heben sich dagegen die niedrigeren Beiträge so auf, dass $-x^4/4$ übrig bleibt. Deshalb reicht die Prüfung aller festen Geraden hier nicht.`,
 fixed:R`Für $x_0=0$ erhältst du eine geometrische Summe: $x_n=(1-q^n)/(1-q)$. Der Fixpunkt ist $x_*=1/(1-q)$, also $|x_n-x_*|=q^n/(1-q)$. Bei dieser speziellen affinen Abbildung ist die Banach-Schranke exakt; im Allgemeinen ist sie nur eine obere Schranke.`,
 uniform:R`Gleichmäßige Stetigkeit würde für ein festes ε einen einzigen Eingabeabstand δ liefern, der überall funktioniert. Hier wird $|x_n-y_n|=1/(n(n+1))$ kleiner als jedes δ, während $|f(x_n)-f(y_n)|=2n+1$ sogar wächst. Die problematischen Paare wandern zum ausgeschlossenen Ursprung.`,
 convergence:R`Bei jedem festen x < 1 fällt $x^n$ gegen 0. Nahe 1 kannst du aber für jedes n Punkte finden, deren Funktionswert beliebig nahe an 1 liegt. Der punktweise Grenzwert hat am Rand einen Sprung. Ein gleichmäßiger Grenzwert stetiger Funktionen wäre stetig; auch das widerlegt die Gleichmäßigkeit.`,
 limits:'Die Integralspitze wandert zum Rand und wird höher, während ihre Basis schrumpft. Für jeden festen Punkt verschwindet sie irgendwann, doch die Fläche bleibt 1. Im Ableitungsbeispiel werden dagegen die Funktionswerte sogar gleichmäßig klein; die gemeinsame Tangente zeigt trotzdem eine unveränderte Steigung in 0. Prüfe daher immer den Satz für genau den Grenzübergang, den du verwenden willst.'
};
