import {esc,prose,solutionContent} from './study-ui.js';
import {practiceBank,taskById,topics,families} from './practice-bank.js';
import {ensureAttempt,startAttempt,advance,rateAttempt,optionsFor,checkNumber,familyProgress,usedHelp} from './practice-engine.js';
import {standardSeries,neededSeries} from './practice-shared.js';
import {remainderGuide} from './taylor-remainder.js';
const ratingNames={independent:'Selbstständig geschafft',helped:'Mit Hilfe geschafft',again:'Noch nicht geschafft'};
function seriesTable(task){
 const keys=neededSeries[task.id];if(!keys)return '';
 return `<div class="practice-series"><h3>Passende Standardreihen</h3><p class="small">Um $w=0$. Setze für $w$ den gesamten inneren Ausdruck ein.</p><div class="table-wrap"><table><thead><tr><th>Funktion</th><th>Polynom bis Grad 3 in $w$</th></tr></thead><tbody>${keys.map(key=>`<tr>${standardSeries[key].map(v=>`<td>${prose(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small">Jeweils gilt: Funktion = Polynom $+R_3(w)$, mit $|R_3(w)|\\le C|w|^4$ nahe 0. Jede Funktion hat ihren eigenen Rest und ihre eigene Konstante $C>0$. Für Grad 2 fällt der kubische Term weg; der gesamte Rest heißt dann $R_2(w)$ und erfüllt $|R_2(w)|\\le C|w|^3$ nahe 0. Nach dem Einsetzen zählt der Gesamtgrad in deinen Variablen; etwa hat $(xy)^2$ schon Grad 4.</p><details class="rule"><summary>Restabschätzung: Vorlage und Bedeutung von C</summary>${prose(remainderGuide)}</details></div>`;
}
function legacyContent(state){
 const notes=Object.entries(state.notes).filter(([k])=>k.startsWith('exam-'));
 const sessions=Object.entries(state.examSessions||{});
 if(!notes.length&&!sessions.length)return '';
 return `<details class="practice-legacy"><summary>Bisherige Trainingsnotizen</summary><p class="small muted">Aus dem früheren Training erhalten. Diese Angaben werden nicht als Bewertungen der neuen Aufgaben übernommen.</p>${sessions.map(([id,s])=>`<p class="small">${esc({'fokus-a':'Schwerpunkte A','fokus-b':'Schwerpunkte B',werkzeuge:'Weiterer Übungsstoff','2025':'Altklausur 2025'}[id])}: ${Object.values(s.assessments).filter(Boolean).length} bisherige Selbsteinschätzungen gespeichert.</p>`).join('')}${notes.map(([key,value],i)=>`<details><summary>Gespeicherte Notiz ${i+1}</summary><textarea aria-label="Gespeicherte Notiz ${i+1}" data-note="${esc(key)}">${esc(value)}</textarea></details>`).join('')}</details>`;
}
function approach(task,a){return task.questions.map((q,i)=>{
 const selected=a.choices[i],done=selected!==null;
 const feedback=!done?'':selected===-1?`<p>Der passende Ansatz:</p>${prose(q.options.find(o=>o.correct).text)}${prose(q.options.find(o=>o.correct).explanation)}`:`<p><strong>${q.options[selected].correct?'Das passt.':'Hier passt ein anderer Ansatz.'}</strong></p>${prose(q.options[selected].explanation)}${q.options[selected].correct?'':`<p>Der passende Ansatz:</p>${prose(q.options.find(o=>o.correct).text)}${prose(q.options.find(o=>o.correct).explanation)}`}`;
 return `<fieldset class="practice-question"><legend>${esc(q.prompt)}</legend><div class="practice-options">${optionsFor(task,a.id,i).map(o=>`<button data-choice="${i}:${o.index}" ${done?'disabled':''} class="${selected===o.index?'chosen':''}" ${selected===o.index?'aria-pressed="true"':'aria-pressed="false"'}>${prose(o.text)}${done&&o.correct?'<span class="small">Passender Ansatz</span>':''}</button>`).join('')}<button data-choice="${i}:-1" ${done?'disabled':''} class="quiet ${selected===-1?'chosen':''}">Ich weiß es noch nicht</button></div>${done?`<div id="choice-feedback-${i}" class="practice-feedback" role="status" tabindex="-1">${feedback}</div>`:''}</fieldset>`;
 }).join('');}
function inputs(task,a){
 return `<p class="small muted">Optional. Zahlen oder Brüche, z. B. −0,5 oder −1/2. Exakte Werte; längere Rechnungen kannst du auf Papier lösen.</p><div class="practice-inputs">${task.fields.map((f,i)=>`<label for="practice-input-${i}">${prose(f.label)}<input id="practice-input-${i}" data-practice-input="${i}" type="text" inputmode="text" autocomplete="off" value="${esc(a.inputs[i])}" ${a.checks[i]!==null?`class="input-${a.checks[i]?'good':'bad'}" aria-invalid="${!a.checks[i]}"`:''} aria-describedby="field-status-${i}"><span id="field-status-${i}" class="small">${a.checks[i]===true?'Dieser Wert stimmt.':a.checks[i]===false?'Diesen Wert noch einmal nachrechnen.':''}</span></label>`).join('')}</div><button id="check-practice-inputs">Ergebnisse prüfen</button><p id="numeric-status" class="small muted" role="status">${a.checks.some(v=>v!==null)?'Die Prüfung betrifft nur diese Werte. Voraussetzungen und Rechenweg vergleichst du mit der Lösung.':''}</p>`;
}
export function renderPractice(ctx){
 ctx.clearTimer?.();const {state,save,shell}=ctx,p=state.practice,a=ensureAttempt(p),task=taskById[a.taskId];save();
 const progress=familyProgress(p),completed=progress.filter(s=>s.last).length;
 const activePool=practiceBank.filter(t=>p.filter==='all'||t.topic===p.filter||t.family===p.filter);
 const optionLabel=id=>topics[id]||families[id]?.title||'Alle vier Schwerpunkte';
 const body=`<div class="practice-view"><div class="eyebrow">Anwenden und festigen</div><h1>Klausurtraining</h1><p class="lead">Rechne direkt los. Wenn du hängenbleibst, öffne den passenden Hinweis. Du kannst jederzeit unterbrechen.</p>
 <details class="practice-settings"><summary>Auswahl und Lernstand${p.filter!=='all'?' · '+esc(optionLabel(p.filter)):''}</summary><div class="two-col"><label class="small" for="practice-filter">Was möchtest du üben?<select id="practice-filter"><option value="all">Alle vier Schwerpunkte</option>${Object.entries(topics).map(([id,name])=>`<option value="${id}" ${p.filter===id?'selected':''}>${esc(name)}</option>`).join('')}${Object.entries(topics).map(([topic,name])=>`<optgroup label="${esc(name)}">${Object.entries(families).filter(([,f])=>f.topic===topic).map(([id,f])=>`<option value="${id}" ${p.filter===id?'selected':''}>${esc(f.title)}</option>`).join('')}</optgroup>`).join('')}</select></label><label class="small" for="practice-task-select">Eine bestimmte Aufgabe<select id="practice-task-select"><option value="">Aufgabe auswählen …</option>${activePool.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></label></div>
 <p class="small muted">${completed} von ${progress.length} Verfahren von dir eingeschätzt. Angaben beruhen auf deinen Bewertungen; geöffnete Hilfen werden zusätzlich vermerkt.</p><ul class="practice-progress">${progress.map(s=>`<li><span>${esc(families[s.id].title)}</span><span>${s.last?esc(ratingNames[s.last.rating])+(s.last.rating==='independent'&&usedHelp(s.last)?' · Hilfen oder Fehlerrückmeldung':''):'Noch nicht eingeschätzt'}</span></li>`).join('')}</ul>
 ${p.attempts.length>1?`<label class="small" for="practice-history">Bisherige Bearbeitung wieder öffnen<select id="practice-history"><option value="">Bearbeitung auswählen …</option>${[...p.attempts].reverse().map(at=>`<option value="${at.id}">${esc(taskById[at.taskId].title)} · ${at.rating?esc(ratingNames[at.rating]):'ohne Bewertung'} · ${new Date(at.startedAt).toLocaleDateString('de-DE')}</option>`).join('')}</select></label>`:''}
 ${legacyContent(state)}</details>
 <article class="panel practice-task" aria-labelledby="practice-task-heading"><div class="practice-task-head"><h2 id="practice-task-heading" tabindex="-1">Aufgabe</h2><span class="meta">${task.parts.length>1?task.parts.length+' Teilaufgaben':'Auf Papier oder direkt hier'}</span></div>
 ${prose(task.intro)}<div class="practice-statement">${task.parts.map((part,i)=>`<section>${task.parts.length>1?`<h3>${String.fromCharCode(97+i)})</h3>`:''}${prose(part.prompt)}</section>`).join('')}</div>
 ${task.fields.length?`<details data-practice-open="inputs" ${a.open.inputs?'open':''}><summary>Kurze Ergebnisse eingeben</summary>${inputs(task,a)}</details>`:''}
 <details data-practice-open="notes" ${a.open.notes?'open':''}><summary>Eigene Notiz</summary><textarea id="practice-note" aria-label="Eigene Notiz zur Aufgabe" placeholder="Dein Ansatz oder die Stelle, an der du hängst …">${esc(a.note)}</textarea></details>
 <div class="practice-help">
 <details data-practice-open="approach" ${a.open.approach?'open':''}><summary>Ansatz auswählen</summary>${approach(task,a)}</details>
 <div class="practice-hints">${a.hintCount?`<ol class="steps">${task.hints.slice(0,a.hintCount).map(h=>`<li>${prose(h)}</li>`).join('')}</ol>`:''}<button id="practice-hint" class="quiet" ${a.hintCount>=task.hints.length?'disabled':''}>${a.hintCount>=task.hints.length?'Alle Hinweise geöffnet':a.hintCount?'Nächsten Hinweis zeigen':'Einen Hinweis zeigen'}</button></div>
 <details data-practice-open="recipe" ${a.open.recipe?'open':''}><summary>Rezept ansehen</summary><div class="practice-recipe"><h3>${esc(task.recipeTitle||families[task.family].title)}</h3><ol class="steps">${task.recipe.map(s=>`<li>${prose(s)}</li>`).join('')}</ol>${seriesTable(task)}<p class="meta">${task.recipeSource?esc(task.recipeSource):`Gedruckte Seiten im Rechenguide: ${families[task.family].page}. Die Hinweise darüber wenden die Schritte auf diese Aufgabe an.`}</p></div></details>
 </div><div class="practice-main-actions"><button id="practice-solution" class="primary" aria-expanded="${a.open.solution}" aria-controls="practice-solution-body">${a.open.solution?'Lösung ausblenden':'Lösung vergleichen'}</button><button id="practice-next">Nächste Aufgabe →</button></div>
 <details data-practice-open="source" class="practice-source" ${a.open.source?'open':''}><summary>Quelle und Lernzweck</summary><p class="small">${esc(task.source)}</p><p class="small">${esc(task.purpose)}</p>${task.sourceHref?`<a class="small" href="${task.sourceHref}">Passende Originalaufgabe →</a>`:''}</details></article>
 ${a.open.solution?`<section id="practice-solution-body" class="panel practice-solution" aria-labelledby="solution-heading"><div class="practice-task-head"><h2 id="solution-heading" tabindex="-1">Musterlösung</h2><button id="back-to-task" class="quiet">Zur Angabe ↑</button></div><p class="meta">${esc(task.title)}</p>${task.parts.map((part,i)=>`<section class="practice-solution-part">${task.parts.length>1?`<h3>Teil ${String.fromCharCode(97+i)}</h3>`:''}${solutionContent(part)}</section>`).join('')}
 <div class="practice-assessment"><h3>Wie hat es geklappt?</h3><p class="small muted">Deine Einschätzung des gesamten Rechenwegs vor dem Lösungsvergleich. Die automatisch geprüften Werte bleiben davon getrennt.</p>${usedHelp(a)?'<p class="small">Bei dieser Bearbeitung hast du Hinweise, ein Rezept oder Rückmeldung zu einem unsicheren bzw. falschen Ergebnis genutzt. Das bleibt zusätzlich zu deiner Einschätzung gespeichert.</p>':''}<div class="practice-ratings">${Object.entries(ratingNames).map(([key,name])=>`<button data-practice-rating="${key}" class="${a.rating===key?'selected':''}" aria-pressed="${a.rating===key}">${name}</button>`).join('')}</div><p id="practice-rating-status" class="small muted" role="status" tabindex="-1">${a.rating?'Gespeichert: '+esc(ratingNames[a.rating])+'.':''}</p><button id="practice-next-bottom" class="primary">Nächste Aufgabe →</button></div></section>`:''}
 </div>`;
 shell(body,'klausur','Üben / Klausurtraining');
 const redraw=(focusId)=>{const y=window.scrollY;renderPractice(ctx);window.scrollTo(0,y);if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});};
 const next=()=>{advance(p);save();renderPractice(ctx);document.getElementById('practice-task-heading').focus();document.getElementById('practice-task-heading').scrollIntoView({block:'start'});};
 document.getElementById('practice-next').onclick=next;
 document.getElementById('practice-next-bottom')?.addEventListener('click',next);
 document.getElementById('practice-filter').onchange=e=>{p.filter=e.target.value;advance(p);save();renderPractice(ctx);};
 document.getElementById('practice-task-select').onchange=e=>{if(taskById[e.target.value]){startAttempt(p,taskById[e.target.value]);save();renderPractice(ctx);}};
 document.getElementById('practice-history')?.addEventListener('change',e=>{const id=Number(e.target.value);if(p.attempts.some(at=>at.id===id)){p.current=id;save();renderPractice(ctx);}});
 document.querySelectorAll('[data-practice-open]').forEach(el=>el.ontoggle=()=>{const key=el.dataset.practiceOpen;a.open[key]=el.open;if(key==='recipe'&&el.open)a.recipeSeen=true;save();});
 document.getElementById('practice-note').oninput=e=>{a.note=e.target.value;save();};
 document.getElementById('practice-hint').onclick=()=>{a.hintCount=Math.min(a.hintCount+1,task.hints.length);save();redraw('practice-hint');};
 document.getElementById('practice-solution').onclick=()=>{a.open.solution=!a.open.solution;save();redraw('practice-solution');if(a.open.solution)document.getElementById('solution-heading').scrollIntoView({block:'start'});};
 document.getElementById('back-to-task')?.addEventListener('click',()=>{const el=document.getElementById('practice-task-heading');el.focus();el.scrollIntoView({block:'start'});});
 document.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>{const [i,value]=el.dataset.choice.split(':').map(Number);if(a.choices[i]!==null)return;a.choices[i]=value;save();redraw('choice-feedback-'+i);});
 document.querySelectorAll('[data-practice-input]').forEach(el=>el.oninput=()=>{const i=Number(el.dataset.practiceInput);a.inputs[i]=el.value;a.checks[i]=null;el.classList.remove('input-good','input-bad');el.removeAttribute('aria-invalid');document.getElementById('field-status-'+i).textContent='';document.getElementById('numeric-status').textContent='';save();});
 document.getElementById('check-practice-inputs')?.addEventListener('click',()=>{
  let invalid=false,checked=0;task.fields.forEach((f,i)=>{const result=checkNumber(a.inputs[i],f);a.checks[i]=result.valid?result.correct:null;if(result.valid){checked++;if(!result.correct)a.numericWrong=true;}else if(a.inputs[i].trim())invalid=true;});
  save();redraw('check-practice-inputs');document.getElementById('numeric-status').textContent=invalid?'Mindestens eine Eingabe ist keine gültige Zahl oder kein gültiger Bruch. Verwende z. B. −0,5 oder −1/2.':checked?`${checked} ${checked===1?'Wert geprüft':'Werte geprüft'}. Leere Felder bleiben unbewertet. Prüfe auch Voraussetzungen und Rechenweg.`:'Trage einen Wert ein. Leere Felder bleiben unbewertet.';
 });
 document.querySelectorAll('[data-practice-rating]').forEach(el=>el.onclick=()=>{rateAttempt(a,el.dataset.practiceRating);save();redraw('practice-rating-status');});
}
