// Worked steps for reused tasks; original statements and direct derivative checks stay intact.
import {R} from './practice-shared.js';
export const workedSteps={
 'k-annulus':[[R`Setze $q(x,y)=x^2+y^2$ und $p(x,y)=x$. Beide Funktionen sind auf ganz $\mathbb R^2$ stetig.`,R`Die Bedingungen lauten $q(x,y)\in[1,4]$ und $p(x,y)\in[0,\infty)$. Also $$K=q^{-1}([1,4])\cap p^{-1}([0,\infty)).$$ Beide Wertebereiche sind abgeschlossen. Ihre Urbilder unter stetigen Funktionen und deren Schnitt sind abgeschlossen.`,R`Für jeden Punkt in $K$ gilt $$\|(x,y)\|=\sqrt{x^2+y^2}\le\sqrt4=2.$$ Somit ist $K$ beschränkt. Nach Heine–Borel ist $K$ kompakt.`]],
 'k-graph':[[R`Das Intervall $[1,2]$ ist abgeschlossen und beschränkt in $\mathbb R$, also kompakt.`,R`Definiere $\varphi:[1,2]\to\mathbb R^2$ durch $\varphi(t)=(t,1/t)$. Auf diesem Intervall wird der Nenner nie 0; beide Komponenten sind stetig.`,R`Jeder Punkt von $K$ und nur ein solcher entsteht durch diese Parametrisierung. Also $K=\varphi([1,2])$. Nach Satz 1.12 ist das stetige Bild der kompakten Ausgangsmenge kompakt.`]],
 'k-hyperbola':[[R`Wähle $z_n=(1/n,n)$, $n\ge1$. Die erste Koordinate liegt in $(0,1]$, und die zweite ist ihr Kehrwert. Somit $z_n\in M$.`,R`Es gilt $\|z_n\|=\sqrt{1/n^2+n^2}\ge n\to\infty$. Daher ist $M$ unbeschränkt und nicht kompakt.`,R`Für die Abgeschlossenheit schreibe $$M=\{(x,y):xy=1\}\cap\{x\ge0\}\cap\{x\le1\}.$$ Diese Beschreibung ist gleichwertig: Aus $xy=1$ folgt $x\ne0$, zusammen mit $x\ge0$ also $x>0$. Alle drei Bedingungen sind abgeschlossene Urbilder stetiger Funktionen. Ihr Schnitt ist abgeschlossen. Fehlende Kompaktheit bedeutet hier also nicht fehlende Abgeschlossenheit.`]],
 'k-sequence':[[R`Auf $M$ gilt $\|(1/n,1/n^2)\|\le\sqrt2$. Die Menge ist beschränkt. Aber $z_n=(1/n,1/n^2)\to(0,0)$, und dieser Punkt gehört wegen $1/n>0$ für jedes $n$ nicht zu $M$. Also ist $M$ nicht abgeschlossen und nicht kompakt.`,R`Betrachte jetzt $K=M\cup\{(0,0)\}$ und eine beliebige offene Überdeckung von $K$. Eine ihrer Mengen $U$ enthält $(0,0)$. Da $U$ offen ist und $z_n\to(0,0)$, liegen alle $z_n$ ab einem Index $N$ in $U$.`,R`Es fehlen höchstens die endlich vielen Punkte $z_1,\ldots,z_{N-1}$. Wähle für jeden davon eine Überdeckungsmenge. Zusammen mit $U$ ergeben diese endlich vielen Mengen eine endliche Teilüberdeckung. Damit ist $K$ kompakt.`]],
 'i-triangle':[
 [R`Das Gebiet $\mathbb R^2$ ist offen; beide Komponenten sind Polynome, also ist $f\in C^1$. Die Ableitungen nach $x$ stehen in Spalte 1, die nach $y$ in Spalte 2: $$Df(x,y)=\begin{pmatrix}1&2y\\0&1\end{pmatrix}.$$`,R`Die Determinante ist $1\cdot1-(2y)\cdot0=1\ne0$. Der Umkehrsatz liefert in jedem Punkt eine lokale $C^1$-Umkehrfunktion.`],
 [R`Schreibe $(u,v)=(x+y^2,y)$. Aus der zweiten Gleichung folgt $y=v$. In die erste eingesetzt: $u=x+v^2$, also $x=u-v^2$. Somit $$f^{-1}(u,v)=(u-v^2,v).$$ Für jeden Bildkandidaten $(u,v)\in\mathbb R^2$ existiert genau dieses Urbild. Das zeigt globale Bijektivität.`,R`Für den Bildpunkt $b=(3,1)$ erhältst du $y=1$ und $x=3-1=2$. Also ist das Urbild $a=(2,1)$.`,R`Mit der Jacobi-Matrix aus (a) rechnest du jetzt weiter: $$M=Df(2,1)=\begin{pmatrix}1&2\\0&1\end{pmatrix},\qquad\det M=1.$$ Diagonale vertauschen, aus $2$ wird $-2$, aus $0$ wieder $0$, durch 1 teilen: $$D(f^{-1})(3,1)=M^{-1}=\frac11\begin{pmatrix}1&-2\\0&1\end{pmatrix}.$$ Kontrolle: Das Produkt dieser beiden Matrizen ist $I_2$. Dasselbe Ergebnis folgt direkt durch Ableiten der expliziten Inversen.`]],
 'i-double':[
 [R`Das Gebiet $A$ ist offen; Exponentialfunktion, Sinus und Kosinus sind glatt. Beim Ableiten nach $y$ kommt jeweils der innere Faktor 2 dazu: $$Df(x,y)=\begin{pmatrix}e^x\cos(2y)&-2e^x\sin(2y)\\e^x\sin(2y)&2e^x\cos(2y)\end{pmatrix}.$$`,R`Die Determinante vereinfacht sich zu $$2e^{2x}\cos^2(2y)+2e^{2x}\sin^2(2y)=2e^{2x}>0.$$ Daher ist $f$ in jedem Punkt von $A$ lokal $C^1$-umkehrbar.`],
 [R`Wähle zwei beliebige Eingaben $(x,y),(s,t)\in A$ mit $f(x,y)=f(s,t)$. Gleiche Ausgaben haben gleiche Normen. Hier ist $$\|f(x,y)\|=\sqrt{e^{2x}(\cos^2(2y)+\sin^2(2y))}=e^x.$$ Daher $e^x=e^s$ und somit $x=s$.`,R`Kürze den gemeinsamen positiven Faktor $e^x$ in beiden Ausgabekomponenten. Es bleiben $\cos(2y)=\cos(2t)$ und $\sin(2y)=\sin(2t)$. Beide Winkel liegen in $(0,2\pi)$; ihre Differenz kann nur dann ein Vielfaches von $2\pi$ sein, wenn sie 0 ist. Also $2y=2t$ und $y=t$. Beide Eingaben stimmen überein: $f$ ist injektiv.`,R`Für die Bildmenge heißt die Ausgabe $(u,v)$. Ihr Radius ist $\rho=\sqrt{u^2+v^2}=e^x$. Weil $x\in\mathbb R$ beliebig ist, ist jeder Radius $\rho>0$ erreichbar: Wähle $x=\ln\rho$. Radius 0 ist unmöglich, also fehlt der Ursprung.`,R`Der Bildwinkel ist $2y\in(0,2\pi)$. Damit fehlt die Richtung nach rechts auf der horizontalen Achse; alle anderen Richtungen sind erlaubt. Folglich $$f(A)=\mathbb R^2\setminus\{(u,0):u\ge0\}.$$ $(u,0)$ bedeutet: horizontale Koordinate $u$, Höhe 0. Mit $u\ge0$ ist genau die rechte Halbachse samt Ursprung ausgeschlossen.`,R`Umgekehrt hat jeder Punkt dieser Menge einen Radius $\rho>0$ und Winkel $\theta\in(0,2\pi)$. Die Eingabe $(\ln\rho,\theta/2)$ liegt in $A$ und wird auf diesen Punkt abgebildet. Damit ist die Bildmenge vollständig bestimmt.`],
 [R`Der Bildpunkt $(0,2)$ hat Norm 2 und Winkel $\pi/2$. Also $e^x=2$ und $2y=\pi/2$. Das gesuchte Urbild ist $(\ln2,\pi/4)$.`,R`Setze $e^x=2$, $\cos(2y)=0$, $\sin(2y)=1$ in $Df$ ein: $$Df(\ln2,\pi/4)=\begin{pmatrix}0&-4\\2&0\end{pmatrix},\qquad\det=8.$$`,R`Diagonale vertauschen, andere Vorzeichen wechseln, durch 8 teilen: $$D(f^{-1})(0,2)=\frac18\begin{pmatrix}0&4\\-2&0\end{pmatrix}=\begin{pmatrix}0&1/2\\-1/4&0\end{pmatrix}.$$ Der Auswertungspunkt von $Df$ ist das Urbild, nicht $(0,2)$.`]],
 'p-ellipse':[
 [R`Zuerst die Nullstelle: $F(1,2)=1+2+4-7=0$. Alle Terme sind Polynome, also ist $F$ auf einer offenen Umgebung $C^1$.`,R`Gesucht ist $y=g(x)$. Dafür prüfst du $F_y=x+2y$, also $F_y(1,2)=1+4=5\ne0$. Der implizite Funktionensatz liefert lokal eindeutig eine $C^1$-Lösung mit $g(1)=2$.`],
 [R`Es gilt $F_x=2x+y$ und $F_x(1,2)=2+2=4$. Differenzieren von $F(x,g(x))=0$ liefert $F_x+F_y g'=0$. Daher $$g'(1)=-\frac45.$$`,R`Für die andere Richtung ist die gesuchte Variable $x$. Der Nenner ist deshalb $F_x(1,2)=4\ne0$. Es existiert lokal eindeutig $x=h(y)$ mit $h(2)=1$. Aus $F_x h'+F_y=0$ folgt $$h'(2)=-\frac54.$$`]],
 'p-sheet':[
 [R`Gesucht sind $x=g(y)$ und $u=h(y)$; frei bleibt $y$. Am angegebenen Punkt sollen $g(-1)=2$ und $h(-1)=1$ gelten. Die Funktion $f$ ist laut Angabe $C^1$, also auch $G$ und $H$ auf $\mathbb R^3$.`,
 R`$f(x,y)$ ist ein Funktionsterm in $G$; zum Einsetzen am Punkt verwendest du den gegebenen Wert $f(2,-1)=-1$. Beim Ableiten wird daraus $f_x$ nach $x$, $f_y$ nach $y$ und 0 nach $u$, weil $f$ nicht von $u$ abhängt. Der Nullstellencheck ist $$G(2,-1,1)=-1+1^2=0,\qquad H(2,-1,1)=1\cdot2+3(-1)^3+1^3=2-3+1=0.$$`,
 R`Die Spalten der Jacobi-Matrix gehören zu $x,y,u$: $$D(G,H)=\begin{pmatrix}f_x&f_y&2u\\u&9y^2&x+3u^2\end{pmatrix}.$$ Setze $(x,y,u)=(2,-1,1)$ ein. Gesucht sind $x,u$, daher nimm Spalte 1 und 3 für $A$; die übrige Spalte 2 ergibt $B$: $$A=\begin{pmatrix}f_x(2,-1)&2\\1&5\end{pmatrix},\qquad B=\binom{f_y(2,-1)}9.$$`,
 R`Die Bedingung des impliziten Satzes lautet $$\det A=5f_x(2,-1)-2\ne0,\quad\text{also }f_x(2,-1)\ne\frac25.$$ Dann existieren die gesuchten lokalen $C^1$-Funktionen eindeutig durch den angegebenen Punkt. In Teil (a) ist noch kein Zahlenwert für $f_x(2,-1)$ gegeben.`],
 [R`Zusätzlich gegeben ist in Teil (b) $$Df(2,-1)=(f_x(2,-1),f_y(2,-1))=(1,-3).$$ Daher setzt du $f_x(2,-1)=1$ und $f_y(2,-1)=-3$. Diese Werte werden nicht aus $f(2,-1)=-1$ berechnet.`,
 R`Die Zahlenblöcke aus (a) sind damit $$A=\begin{pmatrix}1&2\\1&5\end{pmatrix},\qquad B=\binom{-3}9,\qquad\det A=1\cdot5-2\cdot1=3\ne0.$$ Die Voraussetzung aus (a) ist erfüllt.`,
 R`Invertiere $A$: Vertausche 1 und 5 auf der Diagonale, aus 2 und 1 werden $-2$ und $-1$, teile durch 3. $$A^{-1}=\frac13\begin{pmatrix}5&-2\\-1&1\end{pmatrix}.$$`,
 R`Die Ableitungen stehen in derselben Reihenfolge wie die gesuchten Variablen $x,u$. Verwende $$\binom{g'(-1)}{h'(-1)}=A^{-1}(-B),\qquad -B=\binom3{-9}.$$ Zuerst Matrix mal Vektor: $$\begin{pmatrix}5&-2\\-1&1\end{pmatrix}\binom3{-9}=\binom{5\cdot3+(-2)(-9)}{(-1)\cdot3+1\cdot(-9)}=\binom{15+18}{-3-9}=\binom{33}{-12}.$$`,
 R`Den Vorfaktor hineinrechnen ergibt $$\binom{g'(-1)}{h'(-1)}=\frac13\binom{33}{-12}=\binom{11}{-4}.$$ Also $g'(-1)=11$ und $h'(-1)=-4$. Kontrolle: $A(11,-4)^T=(3,-9)^T=-B$.`]],
 'p-multifree':[
 [R`Einsetzen liefert $F_1(1,1,0,0)=1+1+0-2=0$ und $F_2(1,1,0,0)=1+2+0-3=0$. Die Funktionen sind Polynome, also glatt.`,R`Die gesuchten Variablen sind $(u,v)$. Ihre Ableitungen ergeben am Punkt $$A=\begin{pmatrix}2u&1\\1&2\end{pmatrix}_{u=1}=\begin{pmatrix}2&1\\1&2\end{pmatrix}.$$ Die Determinante ist $4-1=3\ne0$. Daher existiert lokal eindeutig $g(s,t)$ mit $g(0,0)=(1,1)$.`],
 [R`Nach den freien Variablen $(s,t)$ abgeleitet ist $B=\begin{pmatrix}1&0\\0&1\end{pmatrix}=I_2$. Gesucht ist $Dg(0,0)=A^{-1}(-B)$. Den Block $A$ und seine Determinante 3 haben wir bereits in (a) berechnet.`,R`Invertiere $A$ einmal: Diagonale vertauschen, die anderen Vorzeichen wechseln, durch 3 teilen. $$A^{-1}=\frac13\begin{pmatrix}2&-1\\-1&2\end{pmatrix}.$$`,R`Hier ist $-B=-I_2$, also kehren sich bei der Multiplikation alle Vorzeichen um: $$Dg(0,0)=\frac13\begin{pmatrix}2&-1\\-1&2\end{pmatrix}\begin{pmatrix}-1&0\\0&-1\end{pmatrix}=\frac13\begin{pmatrix}-2&1\\1&-2\end{pmatrix}=\begin{pmatrix}-2/3&1/3\\1/3&-2/3\end{pmatrix}.$$ Zeilen gehören zu $(u,v)$, Spalten zu $(s,t)$. Zur Kontrolle liefert $A\,Dg$ die Matrix $-I_2=-B$.`]],
 't-logexp':[
 [R`Das Definitionsgebiet $D=\{1+x+y^2>0\}$ enthält eine offene Umgebung von $(0,0)$; dort ist $f$ glatt. Der Entwicklungspunkt ist schon 0. Setze $\rho=\sqrt{x^2+y^2}$ und verwende die Tabellenzeilen für $\ln(1+w)$ und $e^w$.`,
 R`Im Logarithmus ist $w=x+y^2$. Setze den ganzen Ausdruck ein und multipliziere sein Quadrat aus: $$(x+y^2)^2=x^2+2xy^2+y^4.$$ $x^2$ hat Grad 2, $2xy^2$ Grad 3 und $y^4$ Grad 4. Daher bleibt bis Grad 2 $$\ln(1+x+y^2)=x+y^2-\frac{x^2}{2}+O(\rho^3).$$`,
 R`Im Exponentialterm ist $w=xy$ schon von Grad 2; $w^2=x^2y^2$ hat Grad 4. Also $e^{xy}=1+xy+O(\rho^4)$. Addieren ergibt $$T_2(x,y)=1+x-\frac{x^2}{2}+xy+y^2,\qquad f=T_2+R_2.$$ Es gilt $R_2=O(\rho^3)$: Die weggelassenen Terme beginnen frühestens bei Grad 3, und die glatte Funktion besitzt lokal eine Taylor-Restabschätzung dieser Ordnung.`],
 [R`Lies zuerst Konstante und lineare Terme ab: $f(0,0)=1$ und $\nabla f(0,0)=(1,0)^T$. Für den quadratischen Teil gilt $$\frac12(x,y)H(x,y)^T=\frac12H_{11}x^2+H_{12}xy+\frac12H_{22}y^2.$$ Vergleiche mit $-x^2/2+xy+y^2$: $H_{11}=2(-1/2)=-1$, $H_{12}=H_{21}=1$, $H_{22}=2\cdot1=2$.`,
 R`Damit lautet die verlangte Matrixform $$f(x,y)=1+\begin{pmatrix}1&0\end{pmatrix}\binom xy+\frac12\begin{pmatrix}x&y\end{pmatrix}\begin{pmatrix}-1&1\\1&2\end{pmatrix}\binom xy+R_2(x,y),$$ wobei $R_2(x,y)=O(\|(x,y)\|^3)$.`],
 [R`Die in (b) abgelesenen Einträge ergeben $$H_f(0,0)=\begin{pmatrix}-1&1\\1&2\end{pmatrix}.$$ Bei reinen Quadraten wird der Koeffizient verdoppelt; der Koeffizient von $xy$ steht unverändert an beiden gemischten Stellen. Teil (d) verlangt zusätzlich die Kontrolle durch direkte Ableitungen der ursprünglichen Funktion.`]],
 't-fraction':[
 [R`$D=\{z\ne1\}$ enthält eine offene Umgebung von 0, auf der $f$ glatt ist. Setze $\rho=\sqrt{x^2+y^2+z^2}$. Im Zähler liefert die Exponentialreihe $$e^{x+y}-1=x+y+\frac{(x+y)^2}{2}+O(\rho^3).$$ Der konstante Term 1 fällt wegen des $-1$ weg.`,
 R`Für den Nenner gilt $\frac1{1-z}=1+z+z^2+O(\rho^3)$. Weil der Zähler erst bei Grad 1 beginnt, erzeugt sein Produkt mit $z^2$ nur Terme ab Grad 3. Für $T_2$ genügen deshalb $$\left(x+y+\frac{(x+y)^2}{2}\right)(1+z).$$ Behalte $x+y$, $(x+y)^2/2$ und $(x+y)z$; das Produkt $(x+y)^2z/2$ hat schon Grad 3.`,
 R`Multipliziere die behaltenen Terme aus: $$\frac{e^{x+y}-1}{1-z}=x+y+\frac{x^2}{2}+xy+\frac{y^2}{2}+xz+yz+O(\rho^3).$$ Bei den übrigen Summanden ist $xz$ bereits von Grad 2, also $\sin(xz)=xz+O(\rho^6)$. Außerdem $y^2e^z=y^2(1+z+\ldots)=y^2+O(\rho^3)$.`,
 R`Addiere die drei Beiträge: $xz+xz=2xz$ und $y^2/2+y^2=3y^2/2$. Damit $$T_2=x+y+\frac{x^2}{2}+xy+\frac32y^2+2xz+yz,\qquad f=T_2+R_2.$$ Es gilt $R_2=O(\rho^3)$; die glatte Funktion hat lokal eine Restabschätzung dritter Ordnung. Reine $z$- und $z^2$-Terme entstehen hier nicht.`],
 [R`Die Konstante ist 0. Aus $x+y$ folgt $\nabla f(0)=(1,1,0)^T$. Mit den in (c) erläuterten Hesse-Einträgen lautet die Matrixform $$f(x,y,z)=\begin{pmatrix}1&1&0\end{pmatrix}\begin{pmatrix}x\\y\\z\end{pmatrix}+\frac12\begin{pmatrix}x&y&z\end{pmatrix}\begin{pmatrix}1&1&2\\1&3&1\\2&1&0\end{pmatrix}\begin{pmatrix}x\\y\\z\end{pmatrix}+R_2(x,y,z),$$ mit $R_2=O(\|(x,y,z)\|^3)$.`],
 [R`Für die Diagonale verdopple die Koeffizienten der reinen Quadrate: Aus $x^2/2$ wird $H_{11}=1$, aus $3y^2/2$ wird $H_{22}=3$. Es gibt keinen $z^2$-Term, also $H_{33}=0$.`,
 R`Die gemischten Koeffizienten werden unverändert übernommen: $xy$ liefert $H_{12}=H_{21}=1$, $2xz$ liefert $H_{13}=H_{31}=2$, und $yz$ liefert $H_{23}=H_{32}=1$. Also $$H_f(0)=\begin{pmatrix}1&1&2\\1&3&1\\2&1&0\end{pmatrix}.$$ Teil (d) kontrolliert diese Werte durch direktes Ableiten der ursprünglichen Funktion.`]],
 't-shift':[
 [R`Setze $u=x-1$, $v=y$ und $\rho=\sqrt{u^2+v^2}$. Die Funktion lautet jetzt $\ln(2+u+v^2)+e^{uv}$. Ihr Definitionsgebiet enthält eine offene Umgebung von $(u,v)=(0,0)$.`,R`Trenne die Konstante ab: $\ln(2+w)=\ln2+\ln(1+\frac w2)$. Mit $w=u+v^2$ entsteht $$\ln2+\frac{u+v^2}{2}-\frac{(u+v^2)^2}{8}+\ldots$$ Im Quadrat sind $2uv^2$ und $v^4$ schon von Grad 3 bzw. 4. Bis Grad 2 bleibt somit $\ln2+\frac u2+\frac{v^2}2-\frac{u^2}8$.`,R`Aus $e^{uv}$ bleiben $1+uv$, denn $(uv)^2$ hat Grad 4. Zusammen ergibt das $$T_2=1+\ln2+\frac u2-\frac{u^2}8+uv+\frac{v^2}2.$$ Für $f=T_2+R_2(x,y)$ gilt $R_2=O(\rho^3)$, weil $f$ nahe $(1,0)$ glatt ist.`],
 [R`Die linearen Koeffizienten sind $1/2$ und 0. Für die Hesse-Matrix verdopple die Koeffizienten von $u^2$ und $v^2$: $2(-1/8)=-1/4$ und $2(1/2)=1$. Der gemischte Koeffizient 1 kommt an beide anderen Stellen.`,R`$$\nabla f(1,0)=\binom{1/2}{0},\qquad H_f(1,0)=\begin{pmatrix}-1/4&1\\1&1\end{pmatrix}.$$ Mit $h=(x-1,y)^T$ lautet die Matrixform $$f(1+h_1,h_2)=1+\ln2+(1/2,0)h+\frac12h^TH_f(1,0)h+R_2(1+h_1,h_2),$$ wobei $R_2(1+h_1,h_2)=O(\|h\|^3)$.`]]
};
