const R=String.raw;
export default {id:'umkehrfunktionen',title:'Umkehrfunktionen',description:'Lokale Umkehrbarkeit, Injektivität und die inverse Ableitung.',priority:'Schwerpunkt',source:'Lecture Notes · §2.2; Blatt 4–5; Altklausur 2',visual:'inverse',generator:'inverse',goals:['Den Umkehrsatz vollständig wiedergeben.','Lokale und globale Injektivität unterscheiden.','Bildmengen geometrisch bestimmen.','Die Ableitung am richtigen Urbild invertieren.'],theory:[
{id:'bijective',kind:'Definition',title:'Injektiv, surjektiv, bijektiv',text:R`$f:X\to Y$ heißt injektiv, wenn $f(x)=f(x')\Rightarrow x=x'$. Sie heißt surjektiv, wenn $f(X)=Y$, und bijektiv, wenn beides gilt. Genau dann existiert eine Umkehrfunktion $f^{-1}:Y\to X$. Eine injektive Funktion ist immer bijektiv auf ihr Bild $f(X)$.`,source:'Grundlage für Lecture Notes · §2.2',checks:['Surjektivität bezieht sich auf den festgelegten Zielraum.']},
{id:'diffeo',kind:'Definition',title:'Homöomorphismus und Diffeomorphismus',text:R`Ein Homöomorphismus ist eine stetige Bijektion mit stetiger Umkehrfunktion. Für offene $U,V\subseteq\mathbb R^n$ ist $f:U\to V$ ein $C^1$-Diffeomorphismus, wenn $f$ bijektiv ist und $f,f^{-1}$ von Klasse $C^1$ sind. $f$ ist ein lokaler Diffeomorphismus bei $a$, wenn dies für passende offene Umgebungen von $a$ und $f(a)$ gilt.`,source:'Lecture Notes · Definition 2.16; T.5.1',checks:['Die Umkehrfunktion muss ebenfalls C¹ sein.','Lokal: Einschränkung auf Umgebungen.']},
{id:'inverse-theorem',kind:'Satz',title:'Satz über die Umkehrfunktion',text:R`Sei $U\subseteq\mathbb R^n$ offen, $f\in C^1(U,\mathbb R^n)$, $a\in U$ und $\det Df(a)\ne0$. Dann existieren offene Umgebungen $U_0\subseteq U$ von $a$ und $V_0$ von $f(a)$, sodass $f|_{U_0}:U_0\to V_0$ ein $C^1$-Diffeomorphismus ist. Für $g=(f|_{U_0})^{-1}$ gilt $$Dg(y)=\bigl(Df(g(y))\bigr)^{-1}\quad(y\in V_0).$$`,source:'Lecture Notes · Satz 2.17, S. 25; T.4.2; Altklausur 2(a)',checks:['Gleiche Dimension von Definitions- und Zielraum.','U offen, f von Klasse C¹.','Df(a) invertierbar.','Offene Umgebungen und C¹-Umkehrfunktion.'],note:'Eine überall invertierbare Ableitung garantiert keine globale Injektivität.'},
{id:'matrix-inverse',kind:'Rechenregel',title:'Eine 2 × 2-Matrix invertieren',text:R`Für $A=\begin{pmatrix}a&b\\c&d\end{pmatrix}$ und $ad-bc\ne0$ gilt $$A^{-1}=\frac1{ad-bc}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}.$$ Kontrolle: $AA^{-1}=I$.`,source:'Lineare Algebra für die Anwendungen',checks:['Zuerst Determinante prüfen.','Nicht jeden Matrixeintrag einzeln invertieren.']}
],exercises:[
{id:'polar',title:'Polarkoordinaten',source:'B.4.3',prompt:R`Für $f(r,\theta)=(r\cos\theta,r\sin\theta)$ berechne $Df$ und $\det Df$. Beschreibe $f([1,2]\times[0,\pi])$.`,hint:'r ist Radius, θ der Winkel.',steps:[R`$$Df=\begin{pmatrix}\cos\theta&-r\sin\theta\\\sin\theta&r\cos\theta\end{pmatrix},\qquad\det Df=r.$$`,R`Das Bild ist der abgeschlossene obere Halbring $\{(u,v):1\le\sqrt{u^2+v^2}\le2,\ v\ge0\}$. Beide Halbkreise und die beiden Strecken auf der x-Achse gehören dazu.`]},
{id:'complex-square',title:'Winkelverdopplung',source:'B.4.4 · a > 0',prompt:R`Sei $g(x,y)=(x^2-y^2,2xy)$. Berechne $Dg$, $\det Dg$ und das Bild von $S=\{(x,y):x^2+y^2\le a^2,\ x,y\ge0\}$ für $a>0$.`,hint:'Setze x = r cos θ, y = r sin θ.',steps:[R`$$Dg=\begin{pmatrix}2x&-2y\\2y&2x\end{pmatrix},\quad\det Dg=4(x^2+y^2).$$`,R`$g(r\cos\theta,r\sin\theta)=r^2(\cos2\theta,\sin2\theta)$. Für $0\le r\le a$, $0\le\theta\le\pi/2$ entsteht die abgeschlossene obere Halbkreisscheibe mit Radius $a^2$.`] },
{id:'inverse-exam',title:'Exponential-Polarkoordinaten',source:'B.4.5 = Altklausur 2(b) · 6 Punkte',points:6,prompt:R`Sei $f(x,y)=(e^x\cos y,e^x\sin y)$ und $A=\mathbb R\times(0,2\pi)$. (i) Zeige Injektivität auf $A$. (ii) Bestimme $B=f(A)$. (iii) Berechne $Dg(0,1)$ für $g=(f|_A)^{-1}$.`,hint:'Vergleiche zuerst die Normen. Bestimme vor der Matrixinversion das Urbild von (0,1).',steps:[R`Aus $f(x,y)=f(a,b)$ folgt durch Normvergleich $e^x=e^a$, also $x=a$. Setze nun $a=x$ in die beiden ursprünglichen Komponentengleichungen ein: $$e^x\cos y=e^x\cos b\quad\Longrightarrow\quad\cos y=\cos b.$$ $$e^x\sin y=e^x\sin b\quad\Longrightarrow\quad\sin y=\sin b.$$ Du darfst jeweils durch $e^x$ teilen, weil $e^x>0$. Kosinus und Sinus sind die beiden Koordinaten eines Punktes auf dem Einheitskreis. Stimmen beide überein, zeigen die Winkel auf denselben Punkt. Innerhalb von $(0,2\pi)$ kommt jeder solche Punkt höchstens einmal vor. Wegen $y,b\in(0,2\pi)$ folgt also $y=b$. Somit stimmen beide Eingaben überein und $f|_A$ ist injektiv. Entscheidend sind beide Gleichungen zusammen und der vorgegebene Winkelbereich.`,R`Jeder Radius $e^x>0$ tritt auf. Der Winkel $0$ modulo $2\pi$ fehlt. Deshalb $$B=\mathbb R^2\setminus\{(u,0):u\ge0\}.$$`,R`$g(0,1)=(0,\pi/2)$. Die Matrix $$Df(x,y)=e^x\begin{pmatrix}\cos y&-\sin y\\\sin y&\cos y\end{pmatrix}$$ hat Determinante $e^{2x}>0$. Der Umkehrsatz liefert lokale $C^1$-Inversen, die wegen Injektivität zur Umkehrfunktion auf $B$ zusammenpassen.`,R`$$Dg(0,1)=Df(0,\pi/2)^{-1}=\begin{pmatrix}0&-1\\1&0\end{pmatrix}^{-1}=\begin{pmatrix}0&1\\-1&0\end{pmatrix}.$$`],pitfall:'Die ausgeschlossene Halbgerade enthält den Ursprung. Die Ableitung wird am Urbild ausgewertet.'},
{id:'local-criterion',title:'Kriterium für lokale Diffeomorphismen',source:'B.5.1',prompt:R`Sei $f\in C^1(U,\mathbb R^n)$ auf offenem $U$. Zeige: $f$ ist bei $p$ genau dann ein lokaler $C^1$-Diffeomorphismus, wenn $\det Df(p)\ne0$.`,hint:'Für die notwendige Richtung differenziere g ∘ f = id.',steps:[R`Bei $\det Df(p)\ne0$ folgt die Behauptung aus dem Umkehrsatz.`,R`Ist $g$ eine lokale $C^1$-Umkehrfunktion, so liefert die Kettenregel $Dg(f(p))Df(p)=I$. Die quadratische Matrix $Df(p)$ ist deshalb invertierbar.`]},
{id:'power-map',title:'Eine Abbildung mit variablen Exponenten',source:'B.5.2',prompt:R`An welchen Punkten von $(0,\infty)^2$ ist $f(x,y)=(x^y,y^x)$ ein lokaler Diffeomorphismus?`,hint:'Schreibe x^y = exp(y log x).',steps:[R`$$Df=\begin{pmatrix}yx^{y-1}&x^y\log x\\y^x\log y&xy^{x-1}\end{pmatrix}.$$`,R`$$\det Df=x^y y^x(1-\log x\log y).$$ Da $f\in C^1$ und $x^yy^x>0$, gilt lokale Diffeomorphie genau bei $\log x\log y\ne1$.`]},
{id:'inverse-counter',title:'Bijektiv, aber inverse Ableitung fehlt',source:'B.6.4',prompt:R`Sei $f(x)=\|x\|^2x$ auf $\mathbb R^n$. Zeige $f\in C^\infty$, Bijektivität auf der Einheitskugel und fehlende Differenzierbarkeit der Umkehrfunktion in 0.`,hint:'Entlang jedes Strahls wird der Radius r auf r³ abgebildet.',steps:[R`Jede Komponente ist ein Polynom. Für $x=ru$, $r\ge0$, $\|u\|=1$, gilt $f(x)=r^3u$. Dies gibt auf der Einheitskugel eine Bijektion.`,R`Für $y\ne0$ ist $g(y)=\|y\|^{-2/3}y$, $g(0)=0$. Entlang eines Einheitsvektors $u$ gilt $g(tu)=t^{1/3}u$ für $t>0$.`,R`$\|g(tu)-g(0)\|/t=t^{-2/3}\to\infty$. Eine totale Ableitung in 0 ist unmöglich.`]}
]};
