const R=String.raw;
export default {id:'taylor',title:'Taylor',description:'Mehrdimensionale Entwicklungen, Restterme und Extremstellen.',priority:'Schwerpunkt',source:'Lecture Notes · §2.5–2.6; Blatt 7',visual:'taylor',generator:'taylor',goals:['Taylor mit Voraussetzungen und Restterm formulieren.','Gesamtgrad und Entwicklungspunkt beachten.','Entwicklungen aus bekannten eindimensionalen Reihen zusammensetzen.','Hesse-Matrix aus dem Polynom ablesen und prüfen.'],theory:[
{id:'multiindex',kind:'Definition',title:'Multiindizes',text:R`Für $\alpha=(\alpha_1,\ldots,\alpha_n)\in\mathbb N_0^n$ setzt man $|\alpha|=\sum_i\alpha_i$, $\alpha!=\prod_i\alpha_i!$, $h^\alpha=\prod_i h_i^{\alpha_i}$ und $D^\alpha=\partial_1^{\alpha_1}\cdots\partial_n^{\alpha_n}$. Der Gesamtgrad von $x^2y$ ist 3.`,source:'Lecture Notes · §2.5, S. 50',checks:['|α| ist Summe, α! Produkt der Fakultäten.']},
{id:'taylor-theorem',kind:'Satz',title:'Taylor mit Lagrange-Restterm',text:R`Sei $U\subseteq\mathbb R^n$ offen, $f\in C^{k+1}(U,\mathbb R)$, $a\in U$ und $a+th\in U$ für alle $t\in[0,1]$. Dann existiert $\theta\in(0,1)$ mit $$f(a+h)=\sum_{|\alpha|\le k}\frac{D^\alpha f(a)}{\alpha!}h^\alpha+\sum_{|\alpha|=k+1}\frac{D^\alpha f(a+\theta h)}{\alpha!}h^\alpha.$$ Der erste Summand ist $T_k(f;a)(a+h)$, der zweite der Restterm.`,source:'Lecture Notes · Satz 2.29, S. 52; T.7.2',checks:['C^(k+1) für diese Resttermform.','Die gesamte Verbindungsstrecke liegt in U.','Ein gemeinsames θ im Restterm.','Entwicklung in h = x − a.']},
{id:'taylor-second',kind:'Spezialfall',title:'Taylor zweiter Ordnung',text:R`Für $f\in C^2$ in einer offenen Umgebung von $a$ gilt für $h\to0$: $$f(a+h)=f(a)+\nabla f(a)\cdot h+\frac12h^\top H_f(a)h+o(\|h\|^2).$$ Für $h=(u,v)^\top$ ist der quadratische Teil $\frac12f_{xx}(a)u^2+f_{xy}(a)uv+\frac12f_{yy}(a)v^2$. Bei $f\in C^3$ in einer Umgebung von $a$ ist der Rest $O(\|h\|^3)$.`,source:'Lecture Notes · S. 54–55; B.7.2–B.7.3',checks:['Der gemischte Term hat keinen zusätzlichen Faktor 1/2.','o(‖h‖²) verlangt weniger Regularität als der Lagrange-Rest dritter Ordnung.']},
{id:'known-series',kind:'Rechenregeln',title:'Entwicklungen, die du kennen solltest',text:R`Für $t\to0$ gilt: $$e^t=1+t+\frac{t^2}2+\frac{t^3}6+O(t^4),$$ $$\log(1+t)=t-\frac{t^2}2+\frac{t^3}3+O(t^4),$$ $$\sin t=t-\frac{t^3}6+O(t^5),\qquad\cos t=1-\frac{t^2}2+O(t^4),$$ $$\frac1{1-t}=1+t+t^2+t^3+O(t^4).$$ Beim Einsetzen zusammengesetzter Terme den Gesamtgrad zählen.`,source:'Grundlagen für Blatt 7',checks:['Vorzeichen beim Logarithmus und Kosinus.','Konstanten und lineare Terme nicht vergessen.']},
{id:'extrema',kind:'Satz',title:'Kritische Punkte und Hesse-Kriterium',text:R`Hat $f:U\to\mathbb R$ auf offenem $U$ in $a$ ein lokales Extremum und ist dort differenzierbar, dann $\nabla f(a)=0$. Für $f\in C^2$ und $\nabla f(a)=0$ gilt: $H_f(a)$ positiv definit $\Rightarrow$ striktes lokales Minimum; negativ definit $\Rightarrow$ striktes lokales Maximum; indefinit $\Rightarrow$ kein lokales Extremum. Bei semidefiniter Hesse-Matrix ist das Kriterium nicht entscheidend.`,source:'Lecture Notes · §2.6; B.7.4–B.7.5',checks:['Notwendige und hinreichende Bedingungen unterscheiden.','Semidefinit: gesondert untersuchen.']}
],exercises:[
{id:'taylor-log-exp',title:'Logarithmus und Exponentialfunktion',source:'B.7.2',prompt:R`Bestimme $T_2$ von $f(x,y)=\log(1+x+y^2)+e^{xy}$ bei $(0,0)$, den Restterm und $H_f(0,0)$. Das natürliche Definitionsgebiet ist $\{1+x+y^2>0\}$.`,hint:'x + y² hat Terme unterschiedlichen Grades; xy hat bereits Grad 2.',steps:[R`$\log(1+x+y^2)=x+y^2-\frac12x^2+O(\|(x,y)\|^3)$; $e^{xy}=1+xy+O(\|(x,y)\|^4)$.`,R`$$T_2=1+x-\frac12x^2+xy+y^2,\qquad R_2=O(\|(x,y)\|^3).$$`,R`Daraus $f(0)=1$, $\nabla f(0)=(1,0)^\top$ und $$H_f(0)=\begin{pmatrix}-1&1\\1&2\end{pmatrix}.$$`,R`Kontrolle: $f_x=(1+x+y^2)^{-1}+ye^{xy}$, $f_y=2y/(1+x+y^2)+xe^{xy}$. Erneutes Ableiten und Einsetzen bei 0 liefert $f_{xx}=-1$, $f_{xy}=1$, $f_{yy}=2$.`]},
{id:'taylor-three',title:'Drei Variablen, zweiter Grad',source:'B.7.1(b)',prompt:R`Bestimme $T_2$ von $g(x,y,z)=e^{yz}(\cos x+\sin z)$ bei $(0,0,0)$.`,hint:'yz hat Grad 2. Produkte mit z können dadurch bereits Grad 3 haben.',steps:[R`$e^{yz}=1+yz+O(\|h\|^4)$ und $\cos x+\sin z=1+z-x^2/2+O(\|h\|^3)$, $h=(x,y,z)$.`,R`Multiplizieren und nur Gesamtgrad höchstens 2 behalten: $$T_2=1+z-\frac12x^2+yz.$$ Der Rest ist $O(\|h\|^3)$.`]},
{id:'taylor-fraction',title:'Quotient und gemischte Terme',source:'B.7.3',prompt:R`Für $f(x,y,z)=\frac{e^{x+y}-1}{1-z}+\sin(xz)+y^2e^z$ bestimme $T_2$ bei 0 und die Hesse-Matrix. Natürliches Gebiet: $z\ne1$.`,hint:'Multipliziere die Reihen nur so weit, wie der Gesamtgrad es erlaubt.',steps:[R`$(e^{x+y}-1)/(1-z)=x+y+\frac12(x+y)^2+xz+yz+O(\|h\|^3)$.`,R`$\sin(xz)=xz+O(\|h\|^6)$ und $y^2e^z=y^2+O(\|h\|^3)$. Somit $$T_2=x+y+\frac12x^2+xy+\frac32y^2+2xz+yz.$$`,R`$$\nabla f(0)=(1,1,0)^\top,\quad H_f(0)=\begin{pmatrix}1&1&2\\1&3&1\\2&1&0\end{pmatrix}.$$ Der Rest ist $O(\|h\|^3)$.`,R`Direkte Kontrolle: Setze $A=e^{x+y}$, $d=1-z$. Dann $f_{xx}=A/d-z^2\sin(xz)$, $f_{xy}=A/d$, $f_{xz}=A/d^2+\cos(xz)-xz\sin(xz)$, $f_{yy}=A/d+2e^z$, $f_{yz}=A/d^2+2ye^z$, $f_{zz}=2(A-1)/d^3-x^2\sin(xz)+y^2e^z$. In 0 ergeben sich der Reihe nach $1,1,2,3,1,0$.`]},
{id:'taylor-shift',title:'Entwicklung um einen anderen Punkt',source:'B.7.1(a) · Gebiet korrigiert',prompt:R`Verwende $f(x,y)=\log(1+x+y)$ auf $U=\{x+y>-1\}$ und bestimme $T_3$ bei $a=(0,1)$. Das auf dem Blatt angegebene Gebiet enthält a nicht.`,hint:'Setze u = x und v = y − 1. Dann 1 + x + y = 2 + u + v.',steps:[R`$\log(2+u+v)=\log2+\log(1+(u+v)/2)$.`,R`$$T_3=\log2+\frac{u+v}2-\frac{(u+v)^2}8+\frac{(u+v)^3}{24},\qquad u=x,\ v=y-1.$$ Der Rest ist $O(\|(u,v)\|^4)$.`],pitfall:'In Potenzen von x und y−1 entwickeln, nicht von x und y.'},
{id:'taylor-proof',title:'Taylor auf eine Variable zurückführen',source:'Lecture Notes · Beweis von Satz 2.29',prompt:'Erkläre den Beweis des mehrdimensionalen Taylor-Satzes mit Lagrange-Rest.',hint:'Betrachte die Funktion entlang der Strecke a + th.',steps:[R`Setze $g(t)=f(a+th)$. Aus der Kettenregel und Schwarz folgt $$g^{(j)}(t)=\sum_{|\alpha|=j}\frac{j!}{\alpha!}D^\alpha f(a+th)h^\alpha.$$`,R`Wende den eindimensionalen Taylor-Satz zwischen 0 und 1 an: $g(1)=\sum_{j=0}^k g^{(j)}(0)/j!+g^{(k+1)}(\theta)/(k+1)!$.`,R`Einsetzen der Ableitungen liefert genau die Multiindexformel. Die Strecke muss im Definitionsgebiet liegen, damit $g$ auf ganz $[0,1]$ definiert ist.`]},
{id:'extrema-curves',title:'Auf jeder Geraden ein Minimum?',source:'B.7.4',prompt:R`Sei $f(x,y)=2x^4-3x^2y+y^2$. Bestimme kritische Punkte. Zeige: In $(0,0)$ gibt es kein lokales Minimum, obwohl die Einschränkung auf jede Gerade durch 0 dort ein lokales Minimum hat.`,hint:'Die Kurve y = 3x²/2 ist aufschlussreicher als Geraden.',steps:[R`$\nabla f=(8x^3-6xy,-3x^2+2y)$. Aus $y=3x^2/2$ folgt $8x^3-9x^3=-x^3=0$. Einziger kritischer Punkt: $(0,0)$.`,R`Entlang $y=3x^2/2$ gilt $f=-x^4/4<0$ für $x\ne0$, aber entlang $y=0$ gilt $f=2x^4>0$. Also kein lokales Extremum.`,R`Auf der Geraden $(x,y)=t(a,b)$ gilt $f=2a^4t^4-3a^2bt^3+b^2t^2$. Für $b\ne0$ dominiert der positive Term $b^2t^2$ nahe 0. Für $b=0,a\ne0$ ist $2a^4t^4>0$. Jede Gerade hat daher ein striktes lokales Minimum.`]},
{id:'critical-points',title:'Kritische Punkte eines trigonometrischen Beispiels',source:'B.7.5(b)',prompt:R`Finde alle kritischen Punkte von $f(x,y,z)=x\sin y+z^2$.`,hint:'Löse alle Komponenten des Gradienten gleichzeitig.',steps:[R`$\nabla f=(\sin y,x\cos y,2z)$. Die Gleichung $\sin y=0$ liefert $y=k\pi$, $k\in\mathbb Z$.`,R`Dann ist $\cos y=(-1)^k\ne0$, also $x=0$; außerdem $z=0$. Die kritischen Punkte sind genau $(0,k\pi,0)$.`]}
]};
