import {types as extraTypes,markup as extraMarkup,draw as extraDraw} from './plots-extended.js';
import {chart as modernChart} from './plot-geometry.js';
const R=String.raw;
const fmt=n=>Math.abs(n)<1e-12?'0':Math.abs(n)<.001?Number(n).toExponential(2):Number(n).toFixed(3).replace(/\.?0+$/,'');
function chart(curves,{range=2.5,yrange=range,points=[],area='',labels='x,y'}={}){const W=500,H=330,px=x=>250+x/range*212,py=y=>165-y/yrange*130;let grid='';for(let i=-2;i<=2;i++){grid+=`<path class="grid" d="M${px(i)} 25V305 M25 ${py(i)}H475"/>`;if(i!==0)grid+=`<text x="${px(i)+4}" y="180">${i}</text>`;}const paths=curves.map((curve,i)=>{let d='';for(let j=0;j<=300;j++){const p=curve(j/300);if(p&&p.every(Number.isFinite)&&Math.abs(p[1])<yrange*2)d+=`${d?'L':'M'}${px(p[0]).toFixed(2)},${py(p[1]).toFixed(2)} `;else if(d)d+=' ';}return`<path d="${d}" class="${i?'secondary':'curve'}"/>`}).join('');return`<svg class="plot" viewBox="0 0 ${W} ${H}" role="img" aria-label="${labels.split(',').join(' und ')} Diagramm"><defs><clipPath id="plotclip"><rect x="25" y="25" width="450" height="280"/></clipPath></defs>${grid}<path class="axis" d="M25 165H478 M250 20V305"/><text x="480" y="157">${labels.split(',')[0]}</text><text x="260" y="22">${labels.split(',')[1]}</text><g clip-path="url(#plotclip)">${area}${paths}${points.map(p=>`<circle cx="${px(p[0])}" cy="${py(p[1])}" r="5" fill="${p[2]||'var(--accent)'}"/>`).join('')}</g></svg>`;}
export const plotTypes=['compact','derivative','inverse','implicit','higher','taylor','fixed',...extraTypes];
export function plotMarkup(type){if(extraTypes.includes(type))return extraMarkup(type);if(type==='compact')return R`<h3>Kreisscheiben und Grenzwerte</h3><label class="control">Menge <select data-param="mode"><option value="closed">Abgeschlossene Kreisscheibe</option><option value="open">Offene Kreisscheibe</option><option value="sequence">Folgenmenge ohne 0</option><option value="sequence0">Folgenmenge mit 0</option></select></label><label class="control">Folgenindex n <input data-param="n" type="range" min="2" max="60" value="6"><output>6</output></label>`;
if(type==='inverse')return R`<h3>Exponentielle Polarkoordinaten</h3><p class="small">$f(x,y)=(e^x\cos y,e^x\sin y)$</p><label class="control">x <input data-param="x" type="range" min="-1.5" max=".6" step=".05" value="0"><output>0</output></label><label class="control">Winkel y / π <input data-param="angle" type="range" min="0" max="4" step=".025" value=".5"><output>.5</output></label>`;
if(type==='implicit')return R`<h3>Die Kreisgleichung lokal auflösen</h3><p class="small">$F(x,y)=x^2+y^2-1=0$</p><label class="control">Winkel / π <input data-param="angle" type="range" min="0" max="2" step=".005" value=".35"><output>.35</output></label>`;
if(type==='taylor')return R`<h3>Taylor entlang einer Richtung</h3><p class="small">$f(x,y)=e^{x+y}$ entlang $(x,y)=t(\cos\varphi,\sin\varphi)$.</p><label class="control">Richtung φ <input data-param="angle" type="range" min="0" max="6.283185" step=".05" value="0"><output>0</output></label><label class="control">Grad <select data-param="degree"><option>1</option><option selected>2</option><option>3</option></select></label><label class="control">Auswertung t <input data-param="t" type="range" min="-1" max="1" step=".01" value=".5"><output>.5</output></label>`;
if(type==='higher')return R`<h3>Krümmung in einer Richtung</h3><p class="small">$f(x,y)=x^2+\lambda y^2$. Gezeigt wird $f(t\cos\varphi,t\sin\varphi)$.</p><label class="control">λ <input data-param="lambda" type="range" min="-2" max="2" step=".1" value="1"><output>1</output></label><label class="control">Richtung φ <input data-param="angle" type="range" min="0" max="3.14159" step=".05" value=".8"><output>.8</output></label>`;
if(type==='fixed')return R`<h3>Fixpunktiteration</h3><p class="small">$x_{n+1}=qx_n+1$, Startwert $x_0=0$.</p><label class="control">q <input data-param="q" type="range" min="0" max=".85" step=".05" value=".5"><output>.5</output></label><label class="control">Schritte <input data-param="n" type="range" min="1" max="20" value="5"><output>5</output></label>`;
return R`<h3>Lineare Näherung</h3><p class="small">$f(x)=x^2$ mit Tangente am Punkt a.</p><label class="control">a <input data-param="a" type="range" min="-1.5" max="1.5" step=".05" value=".7"><output>.7</output></label><label class="control">Schritt h <input data-param="h" type="range" min="-.8" max=".8" step=".02" value=".4"><output>.4</output></label>`;}
export function drawPlot(type,p){if(extraTypes.includes(type))return extraDraw(type,p);if(type==='compact'){const n=+p.n||6,mode=p.mode||'closed';if(mode.startsWith('sequence')){const points=Array.from({length:35},(_,i)=>[1/(i+1),0]);if(mode==='sequence0')points.push([0,0]);return{svg:modernChart([],{xMin:-.08,xMax:1.1,yMin:-.25,yMax:.25,points:[...points,[0,0,'var(--accent)',mode==='sequence'],[1/n,0,'#c86a38']],title:'Folgenmenge und Grenzwert 0'}),text:R`$x_n=1/n=${fmt(1/n)}\to0$. ${mode==='sequence0'?'0 gehört zur Menge. Die Menge ist kompakt.':'0 fehlt. Die Menge ist beschränkt, aber nicht abgeschlossen.'}`,legend:'Orange: ausgewähltes Folgenglied. Die Grafik zeigt nur endlich viele der unendlich vielen Punkte.'};}const px=250+(1-1/n)/2.5*212;return{svg:chart([],{yrange:130/84.8,area:`<ellipse cx="250" cy="165" rx="84.8" ry="84.8" fill="#244cdb10" stroke="var(--accent)" stroke-width="2" ${mode==='open'?'stroke-dasharray="5 5"':''}/><circle cx="${px}" cy="165" r="5" fill="#c86a38"/><circle cx="334.8" cy="165" r="4" fill="${mode==='open'?'var(--paper)':'var(--accent)'}" stroke="var(--accent)"/>`}),text:R`$z_n=(1-1/n,0)=(${fmt(1-1/n)},0)\to(1,0)$. ${mode==='closed'?'Der Grenzwert liegt in der Menge. Die abgeschlossene Kreisscheibe ist kompakt.':'Der Grenzwert fehlt. Die offene Kreisscheibe ist nicht kompakt.'}`,legend:'Gestrichelter Rand: nicht enthalten. Beide Achsen sind gleich skaliert.'};}
if(type==='inverse'){const x=+p.x||0,a=(+p.angle||0)*Math.PI,r=Math.exp(x),u=r*Math.cos(a),v=r*Math.sin(a);return{svg:chart([t=>[r*Math.cos(t*2*Math.PI),r*Math.sin(t*2*Math.PI)]],{range:2.1*212/130,yrange:2.1,points:[[u,v]],area:'<path d="M250 165H475" stroke="#c86a38" stroke-width="3" stroke-dasharray="5 5"/>'}),text:R`$e^x=${fmt(r)}$, $f(x,y)=(${fmt(u)},${fmt(v)})$, $\det Df=e^{2x}=${fmt(r*r)}>0$. ${a>0&&a<2*Math.PI?'Der Winkel liegt im injektiven Streifen 0 < y < 2π.':'Außerhalb des gewählten Streifens: Die Winkelperiodizität wird sichtbar.'}`,legend:'Orange: die aus dem Bild des offenen Streifens ausgeschlossene Halbgerade. Winkel y und y + 2π haben dasselbe Bild.'};}
if(type==='implicit'){const a=(Number(p.angle)||0)*Math.PI,x=Math.cos(a),y=Math.abs(Math.sin(a))<1e-12?0:Math.sin(a),ok=y!==0;const curves=[t=>[Math.cos(t*2*Math.PI),Math.sin(t*2*Math.PI)]];if(ok)curves.push(t=>{const xx=(t-.5)*3;return[xx,y-x/y*(xx-x)]});else curves.push(t=>[x,(t-.5)*3]);return{svg:chart(curves,{range:1.6,yrange:1.6*130/212,points:[[x,y]]}),text:R`$(x,y)=(${fmt(x)},${fmt(y)})$, $F_y=2y=${fmt(2*y)}$. ${ok?R`Lokal nach y auflösbar. $g'(x)=-x/y=${fmt(-x/y)}$.`:'Hier ist F_y = 0. Am seitlichen Kreispunkt ist kein C¹-Graph y = g(x) möglich; nach x kann aufgelöst werden.'}`,legend:'Blau: Nullstellenmenge. Orange: Tangente des lokalen Graphen. Ein lokaler Zweig ist keine globale Auflösung des gesamten Kreises.'};}
if(type==='taylor'){const a=Number(p.angle)||0,k=Number(p.degree)||2,t=Number(p.t)||0,c=Math.cos(a)+Math.sin(a);const poly=z=>{let sum=1,term=1;for(let j=1;j<=k;j++){term*=c*z/j;sum+=term;}return sum;};return{svg:chart([z=>{const u=(z-.5)*2.4;return[u,Math.exp(c*u)]},z=>{const u=(z-.5)*2.4;return[u,poly(u)]}],{range:1.4,yrange:4,points:[[t,Math.exp(c*t)],[t,poly(t),'#c86a38']],labels:'t,Wert'}),text:R`$c=\cos\varphi+\sin\varphi=${fmt(c)}$, $f(tv)=e^{ct}$. Bei $t=${fmt(t)}$: $f=${fmt(Math.exp(c*t))}$, $T_${k}=${fmt(poly(t))}$, absoluter Fehler $=${fmt(Math.abs(Math.exp(c*t)-poly(t)))}$.`,legend:'Blau: Funktion auf der Geraden. Orange: Taylorpolynom. Dies ist ein Schnitt einer zweidimensionalen Funktion, kein Beweis für alle Richtungen.'};}
if(type==='higher'){const l=Number(p.lambda),a=Number(p.angle),q=Math.cos(a)**2+l*Math.sin(a)**2;return{svg:chart([t=>{const x=(t-.5)*4;return[x,q*x*x]}],{yrange:4,labels:'t,f(tv)'}),text:R`$H_f=\begin{pmatrix}2&0\\0&${fmt(2*l)}\end{pmatrix}$, $\Delta f=${fmt(2+2*l)}$. ${l>0?'Positiv definite Hesse-Matrix: striktes Minimum in 0.':l<0?'Indefinite Hesse-Matrix: Sattelpunkt in 0.':'Semidefinite Hesse-Matrix. Hier ist 0 ein nichtstriktes Minimum; das allgemeine Kriterium entscheidet nicht.'}`,legend:'Ein einzelner Schnitt reicht nicht zur Klassifikation. Ändere die Richtung, um bei λ < 0 beide Krümmungsvorzeichen zu sehen.'};}
if(type==='fixed'){const q=Number(p.q),n=Number(p.n),target=1/(1-q);let x=0;const points=[[0,0]];for(let i=1;i<=n;i++){x=q*x+1;points.push([i,x]);}return{svg:modernChart([t=>[t*20,target]],{xMin:0,xMax:20,yMin:0,yMax:7.2,points,labels:['n','xₙ'],title:'Fixpunktiteration und Grenzwert'}),text:R`$x_{${n}}=${fmt(x)}$, $x_*=1/(1-q)=${fmt(target)}$, $|x_{${n}}-x_*|=${fmt(Math.abs(x-target))}$. Fehlerabschätzung: $q^n/(1-q)=${fmt(q**n/(1-q))}$ (hier exakt).`,legend:'Punkte: Iteration. Linie: eindeutiger Fixpunkt. Je näher q an 1 liegt, desto langsamer die Konvergenz.'};}
const a=Number(p.a),h=Number(p.h),lin=x=>a*a+2*a*(x-a);return{svg:chart([t=>{const x=(t-.5)*5;return[x,x*x]},t=>{const x=(t-.5)*5;return[x,lin(x)]}],{yrange:6,points:[[a,a*a],[a+h,(a+h)**2,'#c86a38']]}),text:R`$f'(a)=2a=${fmt(2*a)}$. $f(a+h)-f(a)-f'(a)h=h^2=${fmt(h*h)}$. Für $h\ne0$ ist der normierte Fehler $|h|$ und geht gegen 0. Bei h = 0 ist der Quotient nicht definiert.`,legend:'Blau: Parabel. Orange: Tangente. Bewege h gegen 0, um totale Differenzierbarkeit in einer Variablen zu sehen.'};}
